### ISSUE TITLE
Fix the 'NoneType' object has no attribute 'message' in login view

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1082]
This is a recurring error email, so I post it here to have it fixed someday soon!

2018-11-21 14:03:14,372 - flask.app - ERROR: Exception on /authorized [GET] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/login/views.py", line 71, in authorized
    oauth_response = google.authorized_response()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask_oauthlib/client.py", line 707, in authorized_response
    data = self.handle_oauth2_response(args)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask_oauthlib/client.py", line 692, in handle_oauth2_response
    type='invalid_response', data=data
flask_oauthlib.client.OAuthException: Invalid response from google

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/login/views.py", line 73, in authorized
    current_app.logger.warn(oauth_response.message)
AttributeError: 'NoneType' object has no attribute 'message'

**Comment by moonso** [comment]
Is this solved? Have not seen it in a while...

**Comment by northwestwitch** [comment]
I haven't touched it. Should we close and re-open the issue if it shows up
again?

**Comment by moonso** [comment]
Lets do that
