### ISSUE TITLE
Demo version has bam and bai files (MT reduced files) that are not found by IGV and Pileup

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1256]
I think that's the bug that you found @mikaell. I think you said you have it fixed on your branch? It would be nice if you could include it in #1255. :)

**Comment by northwestwitch** [comment]
Error message when you try to open the files in the viewers:

Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/py36/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/chiararasi/miniconda3/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/chiararasi/miniconda3/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/chiararasi/miniconda3/envs/py36/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/chiararasi/miniconda3/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/chiararasi/miniconda3/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/blueprints/alignviewers/views.py", line 25, in remote_static
    new_resp = send_file_partial(file_path)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/blueprints/alignviewers/partial.py", line 30, in send_file_partial
    return send_file(path)
  File "/Users/chiararasi/miniconda3/envs/py36/lib/python3.6/site-packages/flask/helpers.py", line 588, in send_file
    file = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/chiararasi/Documents/work/GITs/scout/scout/**server/scout/**demo/reduced_mt.bam.bai'

So the path to the files is built wrong apparently!

**Comment by mikaell** [comment]
I haven’t fixed it -just found it :)

I’ll do so right away.


/Mikael

**Comment by northwestwitch** [comment]
Ah ok! Let me know if you want to do it together! :)
