### ISSUE TITLE
Clinical and research SVs page doesn't work for some cases

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1261]
For instance: https://scout-stage.scilifelab.se/cust002/F0001356-14034-2/sv/variants?variant_type=research

It's a different error than #1237 

The error message here is: 
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/utils.py", line 17, in decorated_function
    context = f(*args, **kwargs)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/variants/views.py", line 227, in sv_variants
    if panel['is_default']:
KeyError: 'is_default'

**Comment by northwestwitch** [comment]
Ok. The problem here is a change in the structure of the database objects.

Before panels objects in cases looked like this:

![image](https://user-images.githubusercontent.com/28093618/60081607-6890f480-9732-11e9-9556-413d0524800f.png)
...
![image](https://user-images.githubusercontent.com/28093618/60081625-70509900-9732-11e9-9d79-30cdfff3eb9a.png)



Now they look like this:
![image](https://user-images.githubusercontent.com/28093618/60081533-3e3f3700-9732-11e9-8878-1a76ede40bfa.png)

**Comment by northwestwitch** [comment]
Recreated easily with demo case by removing the is_default from the default panel and adding the default_panels key to the case object:

![image](https://user-images.githubusercontent.com/28093618/60084991-d17b6b00-9738-11e9-955b-9b10b0e47f0b.png)
