### ISSUE TITLE
upload to scout for single cases fails

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/scout#1268]
Please see the attached error message during upload to Scout for a single sample case:

2019-07-02 07:13:49 hasta.scilifelab.se cg.cli.upload[161188] ERROR uploading family failed: abovepigeon
2019-07-02 07:13:49 hasta.scilifelab.se cg.cli.upload[161188] ERROR Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/upload.py", line 396, in auto
    context.invoke(upload, family_id=analysis_obj.family.internal_id)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/upload.py", line 75, in upload
    context.invoke(scout, family_id=family_id)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/upload.py", line 349, in scout
    scout_api.upload(scout_config, force=re_upload)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/apps/scoutapi.py", line 38, in upload
    load_scout(self, config_data)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/scout/load/all.py", line 104, in load_scout
    case_obj = adapter.load_case(config, update=update)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/scout/adapter/mongo/case.py", line 335, in load_case
    parsed_case = parse_case(config=config_data)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/scout/parse/case.py", line 297, in parse_case
    individuals = parse_individuals(config['samples'])
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/scout/parse/case.py", line 270, in parse_individuals
    father = parsed_ind['father']
KeyError: 'father'

**Comment by northwestwitch** [comment]
This is fixed, closing the issue!
