### ISSUE TITLE
Genes page crashes

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1319]
Error is likely this:

Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/py36/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/chiararasi/miniconda3/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/chiararasi/miniconda3/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/chiararasi/miniconda3/envs/py36/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/chiararasi/miniconda3/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/chiararasi/miniconda3/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/utils.py", line 17, in decorated_function
    context = f(*args, **kwargs)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/blueprints/genes/views.py", line 24, in genes
    gene_q = store.all_genes().limit(20)
AttributeError: 'generator' object has no attribute 'limit'

**Comment by northwestwitch** [comment]
I've grepped the same syntax and /scout/server/blueprints/genes/views.py is the only file where I've found all_genes().limit

**Comment by northwestwitch** [comment]
There is a test for that page with the bug. It doesn't fail because it's not actually collected from Travis. It has probably to do with its name, that doesn't start with 'test'. Because if you specifically run pytest giving it the file that the test fails with the right message:
 @genes_bp.route('/genes')
    @templated('genes/genes.html')
    def genes():
        """Render seach box for genes."""
        query = request.args.get('query', '')
        hgnc_id = None
        if '|' in query:
            try:
                hgnc_id = int(query.split(' | ', 1)[0])
            except ValueError:
                flash('Provided gene info could not be parsed!', 'warning')
        if hgnc_id:
            return redirect(url_for('.gene', hgnc_id=hgnc_id))
>       gene_q = store.all_genes().limit(20)
E       AttributeError: 'generator' object has no attribute 'limit'
