### ISSUE TITLE
Upload to Scout can't handle the value 1.0 of het_call_rate in file caseID_gatkcomb.peddy.ped

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/scout#1370]
Upload to Scout fails when the value of "het_call_rate" is 1.0 for a sample in file caseID_gatkcomb.peddy.ped. See error message below.

```2019-10-07 07:01:32 hasta.scilifelab.se cg.cli.upload[47438] ERROR uploading family failed: amusedman
2019-10-07 07:01:32 hasta.scilifelab.se cg.cli.upload[47438] ERROR Traceback (most recent call last):
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/upload.py", line 418, in auto
   context.invoke(upload, family_id=analysis_obj.family.internal_id)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
   return callback(*args, **kwargs)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
   return f(get_current_context(), *args, **kwargs)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/upload.py", line 76, in upload
   context.invoke(scout, family_id=family_id)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
   return callback(*args, **kwargs)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
   return f(get_current_context(), *args, **kwargs)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/upload.py", line 371, in scout
   scout_api.upload(scout_config, force=re_upload)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/apps/scoutapi.py", line 27, in upload
   config_data = parse_case_data(config=data)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/scout/parse/case.py", line 76, in parse_case_data
   add_peddy_information(config_data)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/scout/parse/case.py", line 111, in add_peddy_information
   for ind_info in parse_peddy_ped(file_handle):
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/scout/parse/peddy.py", line 29, in parse_peddy_ped
   ind_info['het_call_rate'] = convert_number(ind_info['het_call_rate'])
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/scout/utils/convert.py", line 32, in convert_number
   res = int(string)
ValueError: invalid literal for int() with base 10: '1.0' 
```

**Comment by northwestwitch** [comment]
Fixed by modifying the peddy file. Changed 1.0 to 1 and it works but it should be handled better in scout. Not urgent but it's a bug

**Comment by moonso** [comment]
I'll take this
