### ISSUE TITLE
Can not open General report

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#1444]
It is not possible to open General report in case 19200. It seems to work for other cases I have tried. Internal Server Error?

**Comment by northwestwitch** [comment]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 22, in decorated_function
    return render_template(template_name, **context)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/templates/cases/case_report.html", line 1067, in top-level template code
    <td><strong>{{ comment.content }}</strong></td>
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/templates/report_base.html", line 14, in top-level template code
    {% block body %}
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/templates/cases/case_report.html", line 53, in block "body"
    {% block content_main %}
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/templates/cases/case_report.html", line 63, in block "content_main"
    {{ dismissed_panel() }}
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/runtime.py", line 574, in _invoke
    rv = self._func(*arguments)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/templates/cases/case_report.html", line 448, in template
    <li>{{dismissed_options[reason|int]['description']}}
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: dict object has no element 0

**Comment by northwestwitch** [comment]
It took me a while to understand the reason of the error because the has something like 60 variants dismissed, but the last one looks like this: 
![image](https://user-images.githubusercontent.com/28093618/68199784-f58c6a00-ffbe-11e9-9a5a-3c3f8d4ffdb6.png)

And this is the reason why it's crashing. Working on it!

**Comment by 1ctw** [comment]
Sorry for that! I normally do not dismiss CNVs but I did in this case by mistake. I wanted to take the "dismiss tag" away. I managed to do that but it was still marked grey in the variant list which was a bit confusing. So that is why it crashed...

**Comment by northwestwitch** [comment]
No worries, it's not your fault, the program should be able to prevent these errors by itself. Do you want to remove the dismiss tag from the variant? I can do it from the database. Let me know!

**Comment by 1ctw** [comment]
Yes, please:)

**Comment by northwestwitch** [comment]
Removed. The general report should work for this case now!

**Comment by dnil** [comment]
Good job, both of you! @1ctw do you remember what you did when you tried to remove the tag? You are not supposed to be able to set it to that value.. 😆
