### ISSUE TITLE
Recast old rank_model_version floats as str for display - and make sure no new ones are loaded.

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1475]
Versions should always be strings (or more complex types) - floats are wrong. 1.10 is often better than 1.1.

2019-11-11 10:56:18,613 - scout.server.app - ERROR: Exception on /cust003/1 [GET] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 21, in decorated_function
   context = f(*args, **kwargs)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/views.py", line 92, in case
   data = controllers.case(store, institute_obj, case_obj)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/controllers.py", line 146, in case
   case_obj['rank_model_version'] + rank_model_link_postfix)
TypeError: must be str, not float

**Comment by dnil** [comment]
Would you have time to look at this one @moonso - you know the loading part best, and perhaps have the best recollection of how the conversion over to str from float was (not) handled last time?
