### ISSUE TITLE
Deleting empty filter fails, perhaps?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1479]
2019-11-11 11:06:11,907 - scout.server.app - ERROR: Exception on /cust003/19217/variants [POST] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 21, in decorated_function
   context = f(*args, **kwargs)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/views.py", line 42, in variants
   user_obj, category, request.form)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/controllers.py", line 423, in populate_filters_form
   filter_obj = store.delete_filter(filter_id, institute_id, current_user.email)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/adapter/mongo/filter.py", line 108, in delete_filter
  **user_id, filter_obj.get('display_name'), institute_id))**
**AttributeError: 'NoneType' object has no attribute 'get'**

**Comment by northwestwitch** [comment]
Is anyone working with this? Otherwise I can take the issue

**Comment by dnil** [comment]
But also pace yourself - don't feel forced to!

**Comment by northwestwitch** [comment]
It's Ok, I could use some programming, the course of today was quite basic
