### ISSUE TITLE
Don’t crash on weird input to dynamic Gene list

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1508]
```

2019-11-14 09:27:24,922 - scout.server.app - ERROR: Exception on /cust003/19230/phenotypes/actions [POST] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/views.py", line 583, in phenotypes_actions
   hgnc_symbol = int(hgnc_symbol_split.replace(' ', ''))
ValueError: invalid literal for int() with base 10: 'LPL'
```

**Comment by northwestwitch** [comment]
I think this is is the same of #1500

**Comment by dnil** [comment]
Looks veeeery similar. Sorry, trying out the GitHub phone app, and while it’s nice and pretty I still don’t quite get the overview of the full size web interface.. I’ll close this for now.

**Comment by northwestwitch** [comment]
It's ok, your title was more informative, so close the other if you want!
