### ISSUE TITLE
Case has no analysis date?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1513]
```
2019-11-14 17:18:28,869 - scout.server.app - ERROR: Exception on /cust002 [GET] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 26, in decorated_function
   return render_template(template_name, **context)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
   ctx.app,
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
   rv = template.render(context)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
   return original_render(self, *args, **kwargs)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
   return self.environment.handle_exception(exc_info, True)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
   raise value.with_traceback(tb)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/templates/cases/cases.html", line 285, in top-level template code
   <a href="{{ url_for('variant.sv_variant', institute_id=case.owner, case_name=case.display_name, variant_id=clinvar.local_id) }}" target="_blank">chr{{clinvar.chromosome}}:{{clinvar.breakpoint1}}_{{clinvar.var_type}}</a>
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/templates/layout_bs4.html", line 1, in top-level template code
   {% extends "bootstrap4.html" %}
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/templates/bootstrap4.html", line 18, in top-level template code
   {% block body %}
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/templates/bootstrap4.html", line 21, in block "body"
   {% block content %}
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/templates/layout_bs4.html", line 80, in block "content"
   {% block content_main %}{% endblock %}
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/templates/cases/cases.html", line 88, in block "content_main"
   <div class="table-responsive">{{ cases_table(group_name, case_group) }}</div>
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/runtime.py", line 574, in _invoke
   rv = self._func(*arguments)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/templates/cases/cases.html", line 180, in template
   {{ case_row(case) }}
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/runtime.py", line 574, in _invoke
   rv = self._func(*arguments)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/templates/cases/cases.html", line 220, in template
   {{ case.analysis_date.date() }}
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'date'
```

**Comment by emiliaol** [comment]
Är det caset jag precis laddade upp? Använde config enligt nedan (fick inte bifoga):
```owner: cust002
family: 'savingakita'
family_name: 'F0032163' 
samples: 
  - analysis_type: wes
    sample_id: ACC6317A21
    sample_name: 2019-26189-02
    phenotype: affected
    sex: female
    bam_path: /home/proj/production/housekeeper-bundles/savingakita/2019-11-05/ACC6317A21_lanes_1234_sorted_md_brecal.bam

analysis_date: datetime.datetime(2019, 11, 14, 16, 25, 35)
gene_panels: [OMIM-AUTO, Inherited cancer] 
default_gene_panels: [Inherited cancer] 
human_genome_build: grch37 
rank_model_version: '1.26'
vcf_snv_research: /home/proj/production/housekeeper-bundles/savingakita/2019-11-05/savingakita_gatkcomb_rhocall_vt_frqf_cadd_vep_parsed_snpeff_ranked.vcf.gz
vcf_snv: /home/proj/production/housekeeper-bundles/savingakita/2019-11-05/savingakita_gatkcomb_rhocall_vt_frqf_cadd_vep_parsed_snpeff_ranked.selected.vcf.gz 
peddy_sex: /home/proj/production/housekeeper-bundles/savingakita/2019-11-05/savingakita_gatkcomb.sex_check.csv
peddy_check: /home/proj/production/housekeeper-bundles/savingakita/2019-11-05/savingakita_gatkcomb.ped_check.csv```

**Comment by dnil** [comment]
Det skulle nog kunna stämma! Var kommer datumsträngen ifrån? Den ser ut som cg -p varianten? Dessa ska egentligen hanteras nu trodde jag - se #1458? @moonso

**Comment by dnil** [comment]
Rättar du den @emiliaol, eller vill du jag ska fixa det i databasen på en gång? Det lär blockera cust002 helt.. 🙈

**Comment by emiliaol** [comment]
Tänkte precis be dig fixa det i databasen så att vi kan se cust002

**Comment by dnil** [comment]
👍 Är ni ikapp med 4.8.3 i produktion nu?

**Comment by emiliaol** [comment]
Tack! 
Nope, vi har inte uppdaterat på hasta än om det var det du menade.

**Comment by emiliaol** [comment]
Funkar fint nu! 
Men det du säger är att om Scout hade varit uppdaterad på hasta när jag laddade upp caset med den här configen så hade det fungerat?

**Comment by dnil** [comment]
Så, fixat! Ja, det där hade vi sett en gång tidigare och ordnat. Jag ska kolla; minst inte om det bara hade funkat och varnat, eller om det hade vägrat ladda fallet..

**Comment by dnil** [comment]
Men, eh, var kom configen ifrån? Vanliga CG-vägen? Isf kanske vi måste kika igen för att få det rätt i båda ändar så att säga.

**Comment by dnil** [comment]
Jo; den borde ha gnällt lite i stil med:
```
       LOG.warning('Analysis date is on wrong format') 
       LOG.info('Setting analysis date to todays date')
```

**Comment by dnil** [comment]
En försiktig gissning är att laddningen gått lite annorlunda vid omanalys nu efter https://github.com/Clinical-Genomics/cg/issues/77? Utan #1458, och https://github.com/Clinical-Genomics/cg/issues/468 är kopplingen lite halvfärdig.

**Comment by emiliaol** [comment]
Configen kom från `cg upload scout -p savingakita` som ger följande output:
```
{'owner': 'cust002', 'family': 'savingakita', 'family_name': 'F0032163', 'samples': [{'analysis_type': 'wes', 'sample_id': 'ACC6317A21', 'capture_kit': None, 'father': None, 'mother': None, 'sample_name': '2019-26189-02', 'phenotype': 'affected', 'sex': 'female', 'bam_path': '/home/proj/production/housekeeper-bundles/savingakita/2019-11-05/ACC6317A21_lanes_1234_sorted_md_brecal.bam', 'mt_bam': None, 'vcf2cytosure': '/home/proj/production/housekeeper-bundles/savingakita/2019-11-05/savingakita_cyto.ACC6317A21.cgh'}], 'analysis_date': datetime.datetime(2019, 11, 14, 16, 25, 35), 'gene_panels': ['Inherited cancer', 'OMIM-AUTO'], 'default_gene_panels': ['Inherited cancer'], 'human_genome_build': 'grch37', 'rank_model_version': '1.26', 'sv_rank_model_version': '1.8', 'vcf_sv': '/home/proj/production/housekeeper-bundles/savingakita/2019-11-05/savingakita_comb_ann_vep_parsed_ranked.selected.vcf.gz', 'vcf_snv': '/home/proj/production/housekeeper-bundles/savingakita/2019-11-05/savingakita_gatkcomb_rhocall_vt_frqf_cadd_vep_parsed_snpeff_ranked.selected.vcf.gz', 'vcf_sv_research': '/home/proj/production/housekeeper-bundles/savingakita/2019-11-05/savingakita_comb_ann_vep_parsed_ranked.vcf.gz', 'vcf_snv_research': '/home/proj/production/housekeeper-bundles/savingakita/2019-11-05/savingakita_gatkcomb_rhocall_vt_frqf_cadd_vep_parsed_snpeff_ranked.vcf.gz', 'peddy_ped': '/home/proj/production/housekeeper-bundles/savingakita/2019-11-05/savingakita_gatkcomb.peddy.ped', 'peddy_sex': '/home/proj/production/housekeeper-bundles/savingakita/2019-11-05/savingakita_gatkcomb.sex_check.csv', 'peddy_check': '/home/proj/production/housekeeper-bundles/savingakita/2019-11-05/savingakita_gatkcomb.ped_check.csv'}
```

Den har jag sedan manuellt masserat för att scout ska acceptera den och för att ta bort sv-infor (eftersom det inte finns några sv varianter i det här fallet)

**Comment by dnil** [comment]
Japp, det är precis https://github.com/Clinical-Genomics/cg/issues/468! Då behöver du bara komma ihåg att ändra på datumet också till något som ser ut som ett datum för yaml. Eller installera senaste scout på hasta så länge så får du bara en varning. Efter att https://github.com/Clinical-Genomics/cg/issues/468 är fixad är förhoppningen att det ska funka fint även utan massage!

**Comment by emiliaol** [comment]
Toppen, tack!
