### ISSUE TITLE
Dependency conflict makes it impossible to install scout-stage on clinical-db

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1565]
Traceback (most recent call last):
File "/home/hiseq.clinical/miniconda//envs/prod-stage/bin/scout", line 11, in
load_entry_point('scout-browser', 'console_scripts', 'scout')()
File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/pkg_resources/init.py", line 489, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/pkg_resources/init.py", line 2852, in load_entry_point
return ep.load()
File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/pkg_resources/init.py", line 2443, in load
return self.resolve()
File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/pkg_resources/init.py", line 2449, in resolve
module = import(self.module_name, fromlist=['name'], level=0)
File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/commands/init.py", line 1, in
from .base import cli
File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/commands/base.py", line 10, in
from scout.server.app import create_app
File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/app.py", line 30, in
from . import extensions
File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/extensions.py", line 11, in
from scout.adapter import MongoAdapter
File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/adapter/init.py", line 1, in
from scout.adapter.mongo.base import MongoAdapter
File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/adapter/mongo/init.py", line 1, in
from .base import MongoAdapter
File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/adapter/mongo/base.py", line 35, in
from .case import CaseHandler
File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/adapter/mongo/case.py", line 11, in
from scout.parse.case import parse_case
File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/parse/case.py", line 7, in
from path import Path
ModuleNotFoundError: No module named 'path'

**Comment by northwestwitch** [comment]
Also this:
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda//envs/prod-stage/bin/scout", line 11, in <module>
    load_entry_point('scout-browser', 'console_scripts', 'scout')()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/commands/__init__.py", line 1, in <module>
    from .base import cli
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/commands/base.py", line 10, in <module>
    from scout.server.app import create_app
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/app.py", line 30, in <module>
    from . import extensions
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/extensions.py", line 11, in <module>
    from scout.adapter import MongoAdapter
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/adapter/__init__.py", line 1, in <module>
    from scout.adapter.mongo.base import MongoAdapter
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/adapter/mongo/__init__.py", line 1, in <module>
    from .base import MongoAdapter
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/adapter/mongo/base.py", line 35, in <module>
    from .case import CaseHandler
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/adapter/mongo/case.py", line 11, in <module>
    from scout.parse.case import parse_case
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/parse/case.py", line 7, in <module>
    from path import Path
ModuleNotFoundError: No module named 'path'
