### ISSUE TITLE
Update individuals - or update stage - out of alignment

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1589]
```2019-12-12 21:31:48,294 - scout.server.app - ERROR: Exception on /cust002/F0032094 [GET] [in /home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/utils.py", line 26, in decorated_function
   return render_template(template_name, **context)
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
   ctx.app,
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
   rv = template.render(context)
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
   return original_render(self, *args, **kwargs)
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
   return self.environment.handle_exception(exc_info, True)
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
   raise value.with_traceback(tb)
 File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/cases/templates/cases/case.html", line 954, in top-level template code
   <option value="{{ panel.panel_id }}" {% if panel.is_default %} selected {% endif %}>{{ panel.display_name }}</option>
 File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/templates/layout_bs4.html", line 1, in top-level template code
   {% extends "bootstrap4.html" %}
 File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/templates/bootstrap4.html", line 18, in top-level template code
   {% block body %}
 File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/templates/bootstrap4.html", line 21, in block "body"
   {% block content %}
 File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/templates/layout_bs4.html", line 80, in block "content"
   {% block content_main %}{% endblock %}
 File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/cases/templates/cases/case.html", line 36, in block "content_main"
   {{ case_page() }}
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/jinja2/runtime.py", line 574, in _invoke
   rv = self._func(*arguments)
 File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/cases/templates/cases/case.html", line 58, in template
   <div class="col-xs-12 col-md-12">{{ individuals_table(case, institute, tissue_types) }}</div>
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/jinja2/runtime.py", line 574, in _invoke
   rv = self._func(*arguments)
 File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/cases/templates/cases/utils.html", line 2, in template
   <form method="POST" action="{{ url_for('cases.update_individual', institute_id=institute._id, case_name=case.display_name) }}">
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/helpers.py", line 370, in url_for
   return appctx.app.handle_url_build_error(error, endpoint, values)
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 2215, in handle_url_build_error
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
   endpoint, values, method=method, force_external=external
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/werkzeug/routing.py", line 2020, in build
   raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'cases.update_individual' with values ['case_name', 'institute_id']. Did you mean 'cases.update_clinical_filter_hpo' instead?
```

After updating scout stage to either a new feature branch, or similarly with update to current master. Both branch and master are ok in this respect locally. I think I'll leave it at that for now - next would be to test a manual scout-stage update procedure and compare.

**Comment by northwestwitch** [comment]
There was somd problem with the update stage script, have you tried supervisorctl restart scout-stage?

**Comment by dnil** [comment]
Yep, that would indeed explain it. Checking..

**Comment by dnil** [comment]
👍
