### ISSUE TITLE
Travis CI skips coverage check

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1604]
Before there were 3 checks and now it looks like the coverage check is skipped. 

Maybe it's just some change in Travis CI, I don't know, but now the checks are always green even if the coverage goes 50% down.. I don't like it!

**Comment by northwestwitch** [comment]
Could this be the cause: https://github.com/z4r/python-coveralls/issues/73 ??

**Comment by dnil** [comment]
Yeah, the errors match with the rest of this segment of the world.
```
$ coveralls --ignore-errors
1512Traceback (most recent call last):
1513  File "/home/travis/virtualenv/python3.6.7/bin/coveralls", line 10, in <module>
1514    sys.exit(wear())
1515  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/coveralls/__init__.py", line 78, in wear
1516    from coveralls.control import coveralls
1517  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/coveralls/control.py", line 2, in <module>
1518    from coveralls.report import CoverallsReporter
1519  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/coveralls/report.py", line 6, in <module>
1520    from coverage.report import Reporter
1521ImportError: cannot import name 'Reporter'
```

**Comment by northwestwitch** [comment]
It works if you freeze the version of coverage to 4.5.4. I'm doing it on my new PR and it works.
