### ISSUE TITLE
panel submission not working

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1661]
I can not upload an update of my panel.
the file is not uploaded. even testet with your tenplate file.

:(

Michela

**Comment by northwestwitch** [comment]
Tested on a demo and uploading a test csv panel works. I'll take a look in the error logs

**Comment by northwestwitch** [comment]
The demo panel works both for creating a new panel and for updating an existing one.

**Comment by northwestwitch** [comment]
When you read this could you send me the panel you are trying to upload by email, so I'll test with that, thanks!

**Comment by dnil** [comment]
I guess this explains it; but @northwestwitch is already on to this, right?
```
2020-01-29 09:40:41,390 - scout.server.app - ERROR: Exception on /panels/5d9ddb08124f636bef70e4be/update [POST] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/panels/views.py", line 138, in panel_update
   new_panel_id = store.apply_pending(panel_obj, update_version)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/adapter/mongo/panel.py", line 457, in apply_pending
   inserted_id = self.panel_collection.insert_one(new_panel).inserted_id
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/collection.py", line 683, in insert_one
   session=session),
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/collection.py", line 599, in _insert
   bypass_doc_val, session)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/collection.py", line 580, in _insert_one
   _check_write_command_response(result)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/helpers.py", line 207, in _check_write_command_response
   _raise_last_write_error(write_errors)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/helpers.py", line 188, in _raise_last_write_error
   raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: scout.gene_panel index: panel_name_1_version_1 dup key: { : "PID", : 17.0 }
```

**Comment by northwestwitch** [comment]
I am!

**Comment by northwestwitch** [comment]
This error could be different from the one she had yesterday, because of the update of the genes from this morning. I'll try to understand what's wrong here

**Comment by northwestwitch** [comment]
Hi @4WGH we finally understood what's wrong the the panel update error. 
Apparently your file (the title) starts with 3 extra byte of information (EF BB BF characters), which causes an error. I could re-create the error locally and I've fixed it by removing the title and saving the file (with a text editor, not Excel from Windows), then uploading the file without the title.  You could give it a try if you are in a hurry to update your panel, and in the meanwhile I'll see if we could handle this situation server-side.

**Comment by 4WGH** [comment]
not understnding where this EF BB BF carachter are but now it is workinng,

thanks

**Comment by northwestwitch** [comment]
From Windows, it reformats the file with a lot of weird characters without you noticing!
