### ISSUE TITLE
Error when creating general report

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1737]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 28, in decorated_function
    return render_template(template_name, **context)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/templates/cases/case_report.html", line 1110, in top-level template code
    {% for comment in variant.comments %}
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/templates/report_base.html", line 14, in top-level template code
    {% block body %}
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/templates/cases/case_report.html", line 58, in block "body"
    {{ pinned_panel() }}
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/templates/cases/case_report.html", line 300, in template
    {{ sv_variant_content(pinned, loop.index) }}
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/templates/cases/case_report.html", line 986, in template
    <thead>
ValueError: too many values to unpack (expected 2)

**Comment by hassanfa** [comment]
To Chiara: https://i.imgur.com/XleZ71U.gifv  :-)

**Comment by northwestwitch** [comment]
I can't reproduce the error with the default demo sample, must something related to the specific case(s)

**Comment by dnil** [comment]
And perhaps with a macro that is shared through "utils"? Renaming those into more object like hierarchies at some point will shed some light on many things.

**Comment by northwestwitch** [comment]
But in theory general report should not be importing stuff from other files. All the used macros are there in the file already

**Comment by dnil** [comment]
Oooh, interesting!

**Comment by northwestwitch** [comment]
Ok it has to do with SVs, reproduced by marking a SV as causative

**Comment by dnil** [comment]
😊

**Comment by northwestwitch** [comment]
It's this loop:

[image: image.png]

**Comment by dnil** [comment]
I can't see your picture, but SVs and unexpectedly many values to unpack does hint at an array of gene names..

**Comment by northwestwitch** [comment]
Sorry, this loop here:

![image](https://user-images.githubusercontent.com/28093618/74946146-26bb6980-53f9-11ea-814a-b722096d4143.png)

Apparently we are unpacking just 2 items for each element of the list

But each tuple has 3.

[('GnomAD', 'NA', None), ('1000G(left)', 0.000998400035314262, None), ('1000G(right)', 0.000998400035314262, None)]

**Comment by northwestwitch** [comment]
What's this None that appears now?

**Comment by dnil** [comment]
Sorry, was over at paper resubmission. Something brand new it seems! Will check!

**Comment by dnil** [comment]
```
from .utils import (
    add_gene_info,
    callers,
    clinsig_human,
    default_panels,
    end_position,
    evaluation,
**frequency,**
    is_affected,
    predictions,
**frequencies,**
)
```

...

```
variant_obj.update(get_variant_links(variant_obj, int(genome_build)))
    variant_obj["frequencies"] = **frequencies**(variant_obj)
    if variant_type in ["snv", "cancer"]:
        # This is to convert a summary of frequencies to a string
        variant_obj["frequency"] = **frequency**(variant_obj)
```
There is no way this could go wrong. ⛑

**Comment by northwestwitch** [comment]
The code was actually changed some days ago:

![image](https://user-images.githubusercontent.com/28093618/74951895-5621a480-5400-11ea-97ec-fe9960ce51c0.png)

In here: https://github.com/Clinical-Genomics/scout/commit/e5468f439ee9c89fe68280ebb3cffe76611a53d7#diff-d9cb1085635fe83b6a8e3b4b9677c9d2

**Comment by northwestwitch** [comment]
@moonso shall we have this link item in the frequencies or we can remove it? In this case the report will work if we leave it unchanged.

**Comment by northwestwitch** [comment]
> ```
> from .utils import (
>     add_gene_info,
>     callers,
>     clinsig_human,
>     default_panels,
>     end_position,
>     evaluation,
> **frequency,**
>     is_affected,
>     predictions,
> **frequencies,**
> )
> ```
> 
> ...
> 
> ```
> variant_obj.update(get_variant_links(variant_obj, int(genome_build)))
>     variant_obj["frequencies"] = **frequencies**(variant_obj)
>     if variant_type in ["snv", "cancer"]:
>         # This is to convert a summary of frequencies to a string
>         variant_obj["frequency"] = **frequency**(variant_obj)
> ```
> 
> There is no way this could go wrong. ⛑

Where is this?

**Comment by dnil** [comment]
in utils ofcourse, where else? 😜

**Comment by dnil** [comment]
server.blueprints.variant.utils

**Comment by dnil** [comment]
Note to self and others: there are other variant types that cancer, snv and sv now..

**Comment by northwestwitch** [comment]
I'm very tired at the moment and I feel like whatever I touch has the potential to go wrong. I'll continue tomorrow!

**Comment by dnil** [comment]
Which is ofcourse the same as you linked. I am also quite tired - that adrenaline is wearing off.. 😅

**Comment by northwestwitch** [comment]
Tomorrow then!

**Comment by dnil** [comment]
I'll just test your PR, then call it a day. After reading this it seems it should cover most of what worked before.
