### ISSUE TITLE
loqus-related subprocess error

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1813]
We've been seeing this error since quite some time, so I'll just drop it here:

```
2020-03-19 12:42:36,105 - scout.server.app - ERROR: Exception on /cust003/20045/4d9e1dc578dcd0f97c193206f1f23e72 [GET] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 23, in decorated_function
    context = f(*args, **kwargs)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variant/views.py", line 56, in variant
    store, loqusdb, data["case"], data["variant"]
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variant/controllers.py", line 263, in observations
    obs_data = loqusdb.get_variant(variant_query) or {}
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/extensions/loqus_extension.py", line 142, in get_variant
    raise err
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/extensions/loqus_extension.py", line 139, in get_variant
    output = execute_command(variant_call)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/extensions/loqus_extension.py", line 28, in execute_command
    raise err
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/extensions/loqus_extension.py", line 25, in execute_command
    output = subprocess.check_output(cmd, shell=False)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/hiseq.clinical/miniconda/envs/P_loqusdb/bin/loqusdb', '--config', '/home/hiseq.clinical/servers/config/clinical-db.scilifelab.se/loqusdb.yaml', 'variants', '--to-json', '--variant-id', '2_109381037_G_C', '--case-count']' returned non-zero exit status 1

```

**Comment by dnil** [comment]
Good! Are we sure this is failing noticably to the user, or might there be silent fails where local frequency just goes blank once in many attempts?

**Comment by northwestwitch** [comment]
I don't know because unfortunately it never happened to me. I suspect that the user might notice because it reflects in the blueprints, but I can't tell for sure!

**Comment by moonso** [comment]
I'm closing this as we do not know how to reproduce and we don't see it coming back. Let's investigate further if it shows up again

**Comment by dnil** [comment]
A further clue from the Scout log: when the process fails, this appears in the connection log:
```
2020-08-26 15:59:07 clinical-db.scilifelab.se mongo_adapter.client[21845] INFO Connecting to uri:mongodb://loqusdb:******@localhost:27019
2020-08-26 15:59:07 clinical-db.scilifelab.se loqusdb.commands.cli[21845] WARNING Seems like mongod is not running
Aborted!
```
But for calls from seconds before and after work. So still looks more like a temporary resource or interaction issue: might be possible to test by adding more debug info and scripting a large number of parallel requests.

**Comment by moonso** [comment]
I'm convinced that this has to do with our sub optimal setup with heavy workload on the only one running mongod process

**Comment by dnil** [comment]
Possible, connection setup is different from continuous query I guess, but it may also have to do with other other system resources like socket reuse? I’m very tempted to try making a simple wsgi json interface for loqus and try it. Ideally there should be a simple complete click-to-gRPC-interface-cast: Erik S mentioned he saw a student announcing work on that, but nothing official out yet..
