### ISSUE TITLE
Key error triggered by individual = individuals[sample_obj.get("sample_id")]

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1823]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 23, in decorated_function
    context = func(*args, **kwargs)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variant/views.py", line 42, in variant
    data = variant_controller(store, institute_id, case_name, variant_id=variant_id)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variant/controllers.py", line 157, in variant
    is_affected(variant_obj, case_obj)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variant/utils.py", line 361, in is_affected
    individual = individuals[sample_obj.get("sample_id")]
KeyError: 'ACC3320A1'

**Comment by dnil** [comment]
False alarm; that's just due to the similarity between case "2" and "2 (wgs)". I dont particularly approve of the family naming in the latter case, but I dont have to give an opinion on that. :)

**Comment by northwestwitch** [comment]
Ok, good! 👍
