### ISSUE TITLE
customized coverage woth 10X täcknig not matching

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1874]
Hi in fam 18260-1 Iäve done a customized coverage report. For genes CDCA8, DUOX1, DUOX2, DUOXA2, FOXE1, GLIS3, IYD, JAG1, NKX2-1, NKX2-5, PAX8, SLC26A4, SLC5A5, TG, TPO, TSHR, SLC26A7 (14629, 3062, 13273,   32698, 3806, 28510, 21071, 6188, 11825, 2488, 8622, 8818, 11040, 11764,   12015, 12373, 14467)

the results  in "Allmänt viktiga mått" for 10X is 100% but at the same time for "täckning av transkript vid: 10X" the results is 95%.

Something is wrong or I'm missing something ?
![bild](https://user-images.githubusercontent.com/12525201/79230683-443f0980-7e65-11ea-9cd8-fb541c4ca7ce.png)

**Comment by dnil** [comment]
Sorry, I'm a little slow today. Ahem, even slower than usual then. 😉 Could you try to describe what the problem is once more?

The first panel describes fractions of bases covered, the second panel fractions of transcript completely covered to 100% (1 - 2/40 = 38/40 = 95%) It would be enough with one base not being covered completely to 10x to cause the latter, so 10x cover could round to 100.00% depening on the gene size and still be ok. Theoretically. Practically, I did note a log error for CDCA8 earlier today, so probably I'm just not getting your message right?


```2020-04-14 13:23:17,861 - scout.server.app - ERROR: Exception on /reports/report [POST] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/chanjo_report/server/blueprints/report/views.py", line 73, in report
   gene_ids = [int(gene_id.strip()) for gene_id in raw_gene_ids.split(',')]
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/chanjo_report/server/blueprints/report/views.py", line 73, in <listcomp>
   gene_ids = [int(gene_id.strip()) for gene_id in raw_gene_ids.split(',')]
ValueError: invalid literal for int() with base 10: 'CDCA8'```

**Comment by 4WGH** [comment]
thank!
it was me a bit slow :)
and misunderstood the result table :)
