### ISSUE TITLE
Fix one or more forms, affected by some update in Flask during last week or so

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1880]
On a clean installation , python=3.6, there is at least a test failing:
tests/server/blueprints/variants/test_variants_utils.py::test_modal_prompt_filter_name 

with this message:
```
cls = <class 'wtforms.fields.core.IntegerField'>, validators = [<wtforms.validators.Optional object at 0x109cfaa20>, <class 'wtforms.fields.core.IntegerField'>]

    @classmethod
    def check_validators(cls, validators):
        if validators is not None:
            for validator in validators:
                if not callable(validator):
                    raise TypeError("{} is not a valid validator because it is not "
                                    "callable".format(validator))
    
                if inspect.isclass(validator):
                    raise TypeError("{} is not a valid validator because it is a class, "
>                                   "it should be an instance".format(validator))
E                   TypeError: <class 'wtforms.fields.core.IntegerField'> is not a valid validator because it is a class, it should be an instance

../../../../miniconda3/envs/appo/lib/python3.6/site-packages/wtforms/fields/core.py:172: TypeError
```

This is likely to reflect on the web interface as well. Do not freeze Flask but fix the WTF (no, not that one, the flask one) because something in there must have become obsolete.

**Comment by dnil** [comment]
WTForms did update three days ago, for the first time in a couple of years..

**Comment by northwestwitch** [comment]
I could work on this, if nobody started yet!

**Comment by betadayz** [comment]
raise TypeError("{} is not a valid validator because it is not "
TypeError: None is not a valid validator because it is not callable
i need solution to it

**Comment by dnil** [comment]
Hi there! 👋🏻 Whazzup? Did you intend to leave a message here, and if so could you be a little more precise, as well as give a bit more context to your question or comment? 😊Cheers!

**Comment by betadayz** [comment]
c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\flask_sqlalchemy\__init__.py:833: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  warnings.warn(FSADeprecationWarning(
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\flask\cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\flask\cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\flask\cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\flask\cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "C:\Users\User\Desktop\large_blog\app.py", line 5, in <module>
    from myproject.forms import LoginForm,RegistrationForm
  File "C:\Users\User\Desktop\large_blog\myproject\forms.py", line 12, in <module>
    class RegistrationForm(FlaskForm):
  File "C:\Users\User\Desktop\large_blog\myproject\forms.py", line 16, in RegistrationForm
    pass_confirm = PasswordField('Confirm Password',validators=[None])
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\wtforms\fields\core.py", line 43, in __new__
    return UnboundField(cls, *args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\wtforms\fields\core.py", line 365, in __init__
    self.field_class.check_validators(validators)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\wtforms\fields\core.py", line 167, in check_validators
    raise TypeError("{} is not a valid validator because it is not "
TypeError: None is not a valid validator because it is not callable

**Comment by betadayz** [comment]
Please I need a solution to this problem

**Comment by betadayz** [comment]
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField
from wtforms.validators import DataRequired,Email,EqualTo
from wtforms import ValidationError


class LoginForm(FlaskForm):
    email = StringField('Email',validators=[DataRequired(),Email()])
    password = PasswordField('Password',validators=[DataRequired()])
    submit = SubmitField('Log in')

class RegistrationForm(FlaskForm):
    email = StringField('Email',validators=[DataRequired(),Email()])
    username = StringField('Username',validators=[DataRequired()])
    password = PasswordField('Password',validators=[DataRequired(),EqualTo('pass_confirm',message='Passwords must match!')])
    pass_confirm = PasswordField('Confirm Password',validators=[None])
    submit = SubmitField('Register!')
    
    def check_email(self,field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Your email has been already registered!')
        
    def check_username(self,field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Username is taken!')

**Comment by dnil** [comment]
Ok, then just head over to Flask-WTF and ask - Im sure they know best and would be happy to help! A few things changed with that update (https://wtforms.readthedocs.io/en/2.3.x/changes/#version-2-3-1) so if this was old code that worked before you updated your environment, you may need to take a new look on your validators! Good luck!

**Comment by israel-oye** [comment]
> from flask_wtf import FlaskForm from wtforms import StringField,PasswordField,SubmitField from wtforms.validators import DataRequired,Email,EqualTo from wtforms import ValidationError
> 
> class LoginForm(FlaskForm): email = StringField('Email',validators=[DataRequired(),Email()]) password = PasswordField('Password',validators=[DataRequired()]) submit = SubmitField('Log in')
> 
> class RegistrationForm(FlaskForm): email = StringField('Email',validators=[DataRequired(),Email()]) username = StringField('Username',validators=[DataRequired()]) password = PasswordField('Password',validators=[DataRequired(),EqualTo('pass_confirm',message='Passwords must match!')]) pass_confirm = PasswordField('Confirm Password',validators=[None]) submit = SubmitField('Register!')
> 
> ```
> def check_email(self,field):
>     if User.query.filter_by(email=field.data).first():
>         raise ValidationError('Your email has been already registered!')
>     
> def check_username(self,field):
>     if User.query.filter_by(username=field.data).first():
>         raise ValidationError('Username is taken!')    
> ```

Were you able to resolve this issue?

**Comment by dnil** [comment]
Hi! I think you may have stumbled onto the wrong repo? Check out FlaskForm perhaps?

The issue we had was resolved - see fix above - a change of convention of the Validator I think, but again, depending on where your issue is the Flask / WTF / FlaskForm might be right - or the repo where you copied that code from? Cheers!
