### ISSUE TITLE
Turning gene names (strings) into integers makes the app crash

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1881]
This can be solved in a combo with #1880, because it should be around the same code.

Error message:

```
/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/views.py", line 771, in case_diagnosis
    remove=remove,
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/adapter/mongo/case_events.py", line 408, in diagnose
    omim_number = int(omim_id.split(":")[-1])
ValueError: invalid literal for int() with base 10: 'SAMD9L'
```

**Comment by northwestwitch** [comment]
Maybe it's not there and I'm confusing this error with another error message that is recurrent. This must be fixed anyway. I'll find the other bug.
