### ISSUE TITLE
Another string parsing to int error, in report page this time

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1885]
Error:

```
2020-04-21 14:26:23,858 - scout.server.app - ERROR: Exception on /reports/report [POST] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/chanjo_report/server/blueprints/report/views.py", line 73, in report
    gene_ids = [int(gene_id.strip()) for gene_id in raw_gene_ids.split(',')]
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/chanjo_report/server/blueprints/report/views.py", line 73, in <listcomp>
    gene_ids = [int(gene_id.strip()) for gene_id in raw_gene_ids.split(',')]
ValueError: invalid literal for int() with base 10: 'IDU
```

**Comment by northwestwitch** [comment]
I've just realized that this bug occurrs in chanjo-report. Fixing it there!

**Comment by dnil** [comment]
That would be really excellent; I'm sure we have an old issue about that somewhere as well. 🧐

**Comment by northwestwitch** [comment]
There are no issues in chanjo-report. And I can't create a new one. 🤔

**Comment by dnil** [comment]
Ah, it is still just-another-fork I guess. Ping @moonso - I guess you own it? Could you enable Issue handling for it? Cheers!

**Comment by moonso** [comment]
Should work now

**Comment by northwestwitch** [comment]
Thanks @moonso, moving this issue to chanjio-report: https://github.com/Clinical-Genomics/chanjo-report/issues/5
