### ISSUE TITLE
Bug when creating a clinvar submission

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1903]
```
/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/utils.py", line 23, in decorated_function
    context = func(*args, **kwargs)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/variant/views.py", line 285, in clinvar
    data = clinvar_export(store, institute_id, case_name, variant_id)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/variant/controllers.py", line 391, in clinvar_export
    for gene in pinned_var.get("genes"):
TypeError: 'NoneType' object is not iterable

```

I've triggered it while starting the clinVar submission process from a variant of a very old case. It's very easy to fix, change:
`    for gene in pinned_var.get("genes"):` 

to 
`    for gene in pinned_var.get("genes",[]):`

**Comment by northwestwitch** [comment]
Test the fix on stage with this case: https://scout-stage.scilifelab.se/cust000/643594-300M/ and its current pinned variant. 
Master branch doesn't work at the moment
