### ISSUE TITLE
Bug in events for a partial causative variant

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1909]
Error is the following:

```
2020-05-11 16:07:40,366 - scout.server.app - ERROR: Exception on /cust002/F0034492/ce01677fc16ee2f21390064919c6ac61/False/causative [POST] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/views.py", line 1093, in mark_causative
    institute_obj, case_obj, user_obj, link, variant_obj
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/adapter/mongo/variant_events.py", line 471, in unmark_partial_causative
    del partial_causatives[variant["_id"]]
KeyError: 'ce01677fc16ee2f21390064919c6ac61'
```

**Comment by northwestwitch** [comment]
Closing this. The error is likely caused by trying to remove a causative variant instead (#1912 )
