### ISSUE TITLE
authlib.integrations.base_client.errors.MismatchingStateError

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1985]
Yesterday the following exception occurred:
```
2020-07-09 18:09:26,845 - scout.server.app - ERROR: Exception on /authorized [GET] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/login/views.py", line 103, in authorized
    token = oauth_client.google.authorize_access_token()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/authlib/integrations/flask_client/remote_app.py", line 74, in authorize_access_token
    params = self.retrieve_access_token_params(flask_req, request_token)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/authlib/integrations/base_client/base_app.py", line 144, in retrieve_access_token_params
    params = self._retrieve_oauth2_access_token_params(request, params)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/authlib/integrations/base_client/base_app.py", line 125, in _retrieve_oauth2_access_token_params
    raise MismatchingStateError()
authlib.integrations.base_client.errors.MismatchingStateError: mismatching_state: CSRF Warning! State not equal in request and response.
```

I'm not sure what caused it but I think it's not a big deal. The authentication works as it should. Perhaps someone trying to login again from a stale page? Anyway the error should be caught a bit more gracefully, hence the issue.

**Comment by northwestwitch** [comment]
Closing this, as it's a duplicate of #2589
