### ISSUE TITLE
scout export database error

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#1991]
When trying to export collections using the export database command this error occurs:
```
scout export database --out /home/proj/stage/backup/clinical-db/mongo/scout/archive-date-"$(date +%Y-%m-%d)"
2020-08-04 15:14:13 hasta.scilifelab.se scout.commands.base[20602] INFO Running scout version 4.19
2020-08-04 15:14:13 hasta.scilifelab.se scout.commands.base[20602] DEBUG Debug logging enabled.
2020-08-04 15:14:13 hasta.scilifelab.se scout.commands.export.export_command[20602] INFO Running scout export
2020-08-04 15:14:13 hasta.scilifelab.se scout.commands.export.database[20602] INFO Running scout export database
2020-08-04 15:14:13 hasta.scilifelab.se scout.commands.export.database[20602] INFO Excluding variants collection
2020-08-04 15:14:13 hasta.scilifelab.se scout.commands.export.database[20602] INFO Excluding exons collection
2020-08-04 15:14:13 hasta.scilifelab.se scout.commands.export.database[20602] INFO Excluding transcripts collection
2020-08-04 15:14:13 hasta.scilifelab.se scout.commands.export.database[20602] INFO Excluding hgnc_gene collection
2020-08-04 15:14:13 hasta.scilifelab.se scout.commands.export.database[20602] INFO Excluding hpo_terms collection
2020-08-04 15:14:13 hasta.scilifelab.se scout.commands.export.database[20602] INFO Excluding disease_terms collection
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/S_main/bin/scout", line 11, in <module>
    sys.exit(cli())
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/scout/commands/export/database.py", line 71, in database
    output = subprocess.run(dump_command, shell=False)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/subprocess.py", line 466, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/subprocess.py", line 1516, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mongodump': 'mongodump'
```

**Comment by dnil** [comment]
You need the mongodump binary in your path to do this. See http://www.clinicalgenomics.se/scout/admin-guide/backup/
Move the issue to servers, perhaps, and we can arrange that on the hasta stage env as well?
