### ISSUE TITLE
Rerun already pending error raised inside an internal routine makes the app interface crash

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1994]
2020-07-17 15:29:58,805 - scout.server.app - ERROR: Exception on /cust003/19010/rerun [POST] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/views.py", line 851, in rerun
    controllers.rerun(store, mail, current_user, institute_id, case_name, sender, recipient)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/controllers.py", line 511, in rerun
    store.request_rerun(institute_obj, case_obj, user_obj, link)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/adapter/mongo/case_events.py", line 275, in request_rerun
    raise ValueError("rerun already pending")
ValueError: rerun already pending

**Comment by northwestwitch** [comment]
It would be nice if the message "rerun already pending" is displayed as a flash on the web page, instead.

**Comment by northwestwitch** [comment]
Fixed by #1995 , closing!
