### ISSUE TITLE
NoneType on filter get - deleting filter twice

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2060]
Cater for the case of deleting last filter for an institute / same filter twice?

```
2020-09-01 14:01:23,660 - scout.server.app - ERROR: Exception on /cust002/F0035385/variants [POST] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 23, in decorated_function
   context = func(*args, **kwargs)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/views.py", line 57, in variants
   store, institute_obj, case_obj, user_obj, category, request.form
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/controllers.py", line 621, in populate_filters_form
   filter_obj = store.delete_filter(filter_id, institute_id, current_user.email)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/adapter/mongo/filter.py", line 122, in delete_filter
   user_id, filter_obj.get("display_name"), institute_id
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by northwestwitch** [comment]
@dnil If you haven't started working on this I can.  Could you describe exactly how to reproduce this? Because I don't see it in the demo, but perhaps I don't do the right thing

**Comment by dnil** [comment]
Great! No, I'm not sure, but it appears related to the last of the filters I create for the clinic being wiped by one of the doctors who want to be sure they are looking at all variants.. ;-)

**Comment by northwestwitch** [comment]
Yes, but how do I trigger it? because if I go on the variants page F0035385 then I see no filters to delete.. 🤔

**Comment by northwestwitch** [comment]
And if I add one filter and then I delete it I don't see any problem..

**Comment by dnil** [comment]
Is it perhaps possible to have an old window open with the filter left and click delete there as well after it has been deleted properly in another window?

**Comment by dnil** [comment]
I guess we need a default / check for that get?

**Comment by dnil** [comment]
Ah, no, sorry, misread that - check for the object that is.

**Comment by northwestwitch** [comment]
> Is it perhaps possible to have an old window open with the filter left and click delete there as well after it has been deleted properly in another window?

AAAh now I get it! Ok!

**Comment by dnil** [comment]
Yep, that is the thing. Open two windows, create filter in one and have both ready on the variants page. Then delete in one, then the other. You could think of it as mimicking two users, although I think it is probably the same person.. 😊

**Comment by northwestwitch** [comment]
There is also the situation when in one of the 2 windows you delete a filter and in the other window you load it..

**Comment by dnil** [comment]
Yes.. At the very least add a flash perhaps? Let me know if you want me to do it - I think that is my lack of imagination shining through the code..

**Comment by northwestwitch** [comment]
Naa it's fine, almost done, but perhaps you might review!
