### ISSUE TITLE
TypeError when running "scout setup database"

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2157]
I've been testing another PR and runned into this error (also on current master). When running the command:
`scout setup database (--api-key blabla):`

```
2020-10-09 08:36:59 n129-p71.local scout.load.hgnc_gene[10982] INFO Loading genes build 37
2020-10-09 08:36:59 n129-p71.local scout.adapter.mongo.hgnc[10982] INFO Loading gene bulk with length 0
Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/py38new/bin/scout", line 33, in <module>
    sys.exit(load_entry_point('scout-browser', 'console_scripts', 'scout')())
  File "/Users/chiararasi/miniconda3/envs/py38new/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38new/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38new/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/chiararasi/miniconda3/envs/py38new/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chiararasi/miniconda3/envs/py38new/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chiararasi/miniconda3/envs/py38new/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chiararasi/miniconda3/envs/py38new/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38new/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38new/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38new/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38new/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/commands/setup/setup_scout.py", line 170, in database
    setup_scout(
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/load/setup.py", line 142, in setup_scout
    hgnc_genes = load_hgnc_genes(
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/load/hgnc_gene.py", line 158, in load_hgnc_genes
    adapter.load_hgnc_bulk(gene_objects)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/adapter/mongo/hgnc.py", line 40, in load_hgnc_bulk
    result = self.hgnc_collection.insert_many(gene_objs)
  File "/Users/chiararasi/miniconda3/envs/py38new/lib/python3.8/site-packages/pymongo/collection.py", line 746, in insert_many
    raise TypeError("documents must be a non-empty list")
TypeError: documents must be a non-empty list
```

**Comment by northwestwitch** [comment]
This is not a big actually. I'm testing with current master, pymongo<3.7, mongodb version 3.6 and it works. So I'm closing it. Perhaps it had to do that I was testing with pymongo 3.11 (PR #2152 )

**Comment by northwestwitch** [comment]
![image](https://user-images.githubusercontent.com/28093618/95578981-1530db80-0a35-11eb-896e-4b694db7af77.png)

**Comment by northwestwitch** [comment]
Tested again from #2152 branch, after re-installing scout (pymongo 3.11) and the command work. Must have been   one of the remote files needed in the setup that was not available at the moment!
