### ISSUE TITLE
Dismiss variant bug

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2183]
Full error:

```
2020-11-04 16:23:42,629 - scout.server.app - ERROR: Exception on /cust004/120701400232fam/variants [POST] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 23, in decorated_function
    context = func(*args, **kwargs)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/views.py", line 70, in variants
    request.form.getlist("dismiss_choices"),
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/controllers.py", line 904, in dismiss_variant_list
    institute_obj, case_obj, user_obj, link, variant_obj, dismiss_reasons
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/adapter/mongo/variant_events.py", line 704, in update_dismiss_variant
    variant["dismiss_variant"], variant["display_name"]
KeyError: 'dismiss_variant'
```

**Comment by northwestwitch** [comment]
I've just realized that was already fixed in #2151 (by me! 😆 ) Perhaps we should plan a release next week? We have some fixes and new features that are not in production yet!

**Comment by dnil** [comment]
True that! Let's! I'll try to get bump the STR filter part up in the prio list to get that bug fix in as well. Otw we just hot fix it as well.

**Comment by northwestwitch** [comment]
I think It's fine to wait and include as many fixes as possible. Haven't seen the bug of today in more than one month

**Comment by dnil** [comment]
..and the number of attempts to submit variants that dont survive reruns to clinvar is hopefully not going to explode either.

**Comment by northwestwitch** [comment]
Nope
