### ISSUE TITLE
Handle better when a case/variant is loading with an unknown associated event

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2229]
Because right now it's crashing:

```
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 23, in decorated_function
    context = func(*args, **kwargs)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/views.py", line 71, in case
    data = controllers.case(store, institute_obj, case_obj)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/controllers.py", line 180, in case
    event["verb"] = VERBS_MAP[event["verb"]]
KeyError: 'remove_variants'
```

**Comment by dnil** [comment]
I think its this, right: https://github.com/Clinical-Genomics/scout/issues/2103
