### ISSUE TITLE
Error creating link -->  AMINO_ACID_RESIDUE_3_TO_1.get(m.group(1), None)

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2231]
```
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 24, in decorated_function
    context = func(*args, **kwargs)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variant/views.py", line 48, in variant
    data = variant_controller(store, institute_id, case_name, variant_id=variant_id)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variant/controllers.py", line 115, in variant
    variant_obj = add_gene_info(store, variant_obj, gene_panels=panels, genome_build=genome_build)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variant/utils.py", line 181, in add_gene_info
    update_transcripts_information(variant_gene, hgnc_gene, variant_obj, genome_build)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variant/utils.py", line 101, in update_transcripts_information
    add_tx_links(transcript, genome_build, hgnc_symbol)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/links.py", line 256, in add_tx_links
    tx_obj["cbioportal_link"] = cbioportal(hgnc_symbol, tx_obj.get("protein_sequence_name"))
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/links.py", line 514, in cbioportal
    protein_change = amino_acid_residue_change_3_to_1(protein_sequence_name)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/utils/convert.py", line 55, in amino_acid_residue_change_3_to_1
    ref = AMINO_ACID_RESIDUE_3_TO_1.get(m.group(1), None)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by dnil** [comment]
Right.. Do you have a variant that fails?

**Comment by northwestwitch** [comment]
This one:

https://scout.scilifelab.se/cust002/F0011796-4/c373c26e066a42b981170fb094c782ef

**Comment by dnil** [comment]
Yep, or this: https://scout.scilifelab.se/cust002/F0033216/9bf2696ba6b1a8063036272547616ed7
most non-three letter codes, likely.. 🙄

**Comment by northwestwitch** [comment]
I didn't think about it either!
