### ISSUE TITLE
Old(?) similar cases call detected?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2260]
the get_similar_cases call was renamed in the case adapter in august - did we miss one call or have we messed with the history?

```
2020-12-15 14:50:53,294 - scout.server.app - ERROR: Exception on /cust003/gene_variants [POST] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 24, in decorated_function
   context = func(*args, **kwargs)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/institutes/views.py", line 218, in gene_variants
   query=form.data, institute_id=institute_id, category="snv", variant_type=variant_type
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/adapter/mongo/variant.py", line 326, in gene_variants
   variant_type=variant_type,
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/adapter/mongo/query.py", line 140, in build_variant_query
   similar_cases = self.get_similar_cases(case_obj)
AttributeError: 'MongoAdapter' object has no attribute 'get_similar_cases'
```

**Comment by northwestwitch** [comment]
Are you working on this @dnil? Otherwise I could check

**Comment by dnil** [comment]
I was just checking it out, but feel free - it may simply just be an oversight from it was renamed, but got me a little nervous.. 😄

**Comment by northwestwitch** [comment]
Yes it's weird, but we might simply have forgotten to rename all occurrences, let's see

**Comment by northwestwitch** [comment]
Yes, I think we just forgot that call. It's a search that is not used often, that's why we see the bug for the first time now!

**Comment by dnil** [comment]
Yeah, its stuff like that that makes me worried about deleting indexes etc. Anyway, good; I'll have a look later!
