### ISSUE TITLE
Bug when serializing case.chromograph_prefixes to json

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2265]
2020-12-16 08:47:45,747 - scout.server.app - ERROR: Exception on /cust000/AMG-Ashkenazim [GET] [in /home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/utils.py", line 29, in decorated_function
    return render_template(template_name, **context)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/cases/templates/cases/case.html", line 425, in top-level template code
    value="{{ button_value if button_value }}"
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/templates/layout_bs4.html", line 1, in top-level template code
    {% extends "bootstrap4.html" %}
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/templates/bootstrap4.html", line 18, in top-level template code
    {% block body %}
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/templates/bootstrap4.html", line 26, in block "body"
    {% block scripts %}
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/cases/templates/cases/case.html", line 456, in block "scripts"
    {{case.chromograph_prefixes|tojson}},
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/json/__init__.py", line 376, in tojson_filter
    return Markup(htmlsafe_dumps(obj, **kwargs))
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/json/__init__.py", line 290, in htmlsafe_dumps
    dumps(obj, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Undefined' is not JSON serializable

**Comment by northwestwitch** [comment]
No worries, it's on stage and not in prod yet!

**Comment by mikaell** [comment]
I'll have a look.

**Comment by mikaell** [comment]
Bugfix should be ready for review: #2266

**Comment by dnil** [comment]
Closed by #2266, right?

**Comment by mikaell** [comment]
> Closed by #2266, right?

Yes!
