### ISSUE TITLE
Potential bug on variant utils

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2317]
I was looking inside the error messages from Scout and found this one from 4 hours ago. I didn't notice it before because it was in between other emails I got when testing some code on stage.

But this comes from production and it's a potential bug:

```
2021-01-28 10:44:28,886 - scout.server.app - ERROR: Exception on /evaluations/5eff48cc124f638aba8def0d [POST] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 24, in decorated_function
    context = func(*args, **kwargs)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variant/views.py", line 231, in evaluation
    evaluation_controller(store, evaluation_obj)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variant/utils.py", line 368, in evaluation
    evaluation_obj["institute"] = store.institute(evaluation_obj["institute_id"])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by dnil** [comment]
Great, then we can't immediately tell if we have an issue with the new shared annotations or if it's this old thing. 😆

**Comment by northwestwitch** [comment]
This should happen if an ACMG classification id created (either manually of with the tool) then removed from the variant page.
If the variant page is not reloaded then the classification still shows and if the user clicks on the link leading to the missing classification, the the evaluation object is none and the page crashes. Will fix!
