### ISSUE TITLE
Cant see created genepanels in cancer scout? 

### ISSUE THREAD

**Issue by heronikdin** [Clinical-Genomics/scout#2400]
hi! 

I cant see one of the genepanels which I have created here: 
![image](https://user-images.githubusercontent.com/62098218/109309452-98679800-7843-11eb-9bf4-c9e11ce52088.png)

these are the current gene panels: 

![image](https://user-images.githubusercontent.com/62098218/109309537-b0d7b280-7843-11eb-96c3-82c217db0389.png)

Eventhough I choose to display the genepanels under settings, specifically this panel does not work... 
![image](https://user-images.githubusercontent.com/62098218/109309904-2ba0cd80-7844-11eb-8fb4-4ac5ef7cbdc5.png)

I keep getting this error message: 

![image](https://user-images.githubusercontent.com/62098218/109309841-1461e000-7844-11eb-976c-5d1df89e310a.png)

**Comment by dnil** [comment]
Thank you - we see it too. It's the dot in the panel label apparently. We'll fix it, but in general, the versioning is well handled by the application, so you should never have to do that with static strings. You can manually edit the automatically suggested version increments when updating the panel if you feel they don't correspond to your own system. I have changed the panel name for you now, but we will either solve it with an error if you try to create a new one with a dot, or add escapes that work. Sorry about that, and thanks again for reporting!

```
2021-02-26 15:05:13,507 - scout.server.app - ERROR: Exception on /overview/cust087/settings [POST] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/institutes/views.py", line 241, in institute_settings
   institute_obj = controllers.update_institute_settings(store, institute_obj, request.form)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/institutes/controllers.py", line 140, in update_institute_settings
   loqusdb_id=form.get("loqusdb_id"),
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/adapter/mongo/institute.py", line 165, in update_institute
   return_document=pymongo.ReturnDocument.AFTER,
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/collection.py", line 3248, in find_one_and_update
   session=session, **kwargs)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/collection.py", line 2972, in __find_and_modify
   write_concern.acknowledged, _find_and_modify, session)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1498, in _retryable_write
   return self._retry_with_session(retryable, func, s, None)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1384, in _retry_with_session
   return self._retry_internal(retryable, func, session, bulk)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1416, in _retry_internal
   return func(session, sock_info, retryable)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/collection.py", line 2966, in _find_and_modify
   user_fields=_FIND_AND_MODIFY_DOC_FIELDS)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/collection.py", line 253, in _command
   user_fields=user_fields)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/pool.py", line 694, in command
   exhaust_allowed=exhaust_allowed)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/network.py", line 161, in command
   parse_write_concern_error=parse_write_concern_error)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/helpers.py", line 164, in _check_command_response
   raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: The dotted field 'Lymfoid_genepanel_v1.0' in 'gene_panels.Lymfoid_genepanel_v1.0' is not valid for storage., full error: {'ok': 0.0, 'errmsg': "The dotted field 'Lymfoid_genepanel_v1.0' in 'gene_panels.Lymfoid_genepanel_v1.0' is not valid for storage.", 'code': 57}
```

**Comment by heronikdin** [comment]
Thank you for the quick help!! 🥇
