### ISSUE TITLE
KeyError: 'end_chrom'

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2422]
Fresh bug from today:

```
2021-03-08 09:32:19,598 - scout.server.app - ERROR: Exception on /cust003/17006/def684dbe6ad6eca77d599f2fb710154 [GET] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 24, in decorated_function
    context = func(*args, **kwargs)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variant/views.py", line 48, in variant
    data = variant_controller(store, institute_id, case_name, variant_id=variant_id)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variant/controllers.py", line 198, in variant
    variant_obj.update(get_variant_links(variant_obj, int(genome_build)))
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/links.py", line 371, in get_variant_links
    decipher_link=decipher_link(variant_obj, build),
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/links.py", line 437, in decipher_link
    if variant_obj["chromosome"] != variant_obj["end_chrom"]:
KeyError: 'end_chrom'
```

**Comment by northwestwitch** [comment]
This is fixed now: https://scout.scilifelab.se/cust003/17006/def684dbe6ad6eca77d599f2fb710154
