### ISSUE TITLE
ValueError: invalid literal for int() with base 10 in managed variants

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2466]
```
2021-03-23 13:21:23,790 - scout.server.app - ERROR: Exception on /managed_variant [POST] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 24, in decorated_function
    context = func(*args, **kwargs)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/managed_variants/views.py", line 35, in managed_variants
    managed_variants_query = store.managed_variants(category=category, query_options=query_options)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/adapter/mongo/managed_variant.py", line 139, in managed_variants
    query_with_options = self.add_options(query, query_options)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/adapter/mongo/managed_variant.py", line 169, in add_options
    query["end"] = {"$gte": int(query_options["position"])}
ValueError: invalid literal for int() with base 10: '44,473,301'
```

**Comment by dnil** [comment]
🙄 Ok, need another validator for these.
