### ISSUE TITLE
Bug when filtering variants by MT chromosome

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2503]
Whoops! 

```
Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/utils.py", line 29, in decorated_function
    return render_template(template_name, **context)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/blueprints/variants/templates/variants/variants.html", line 159, in top-level template code
    data-content="{{ svs_table(institute, case, variant.overlapping[:20]) }}">Overlapping SVs</a>
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/templates/layout_bs4.html", line 1, in top-level template code
    {% extends "bootstrap4.html" %}
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/templates/bootstrap4.html", line 20, in top-level template code
    {% block body %}
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/templates/bootstrap4.html", line 23, in block "body"
    {% block content %}
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/templates/layout_bs4.html", line 82, in block "content"
    {% block content_main %}{% endblock %}
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/blueprints/variants/templates/variants/variants.html", line 86, in block "content_main"
    {{ mark_heteroplasmic_mt(case.individuals, variant.samples) }}
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/blueprints/variants/templates/variants/utils.html", line 7, in template
    {% if gt.alt_frequency < 0.9 and gt.alt_frequency != -1 %}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'alt_frequency'
```

**Comment by northwestwitch** [comment]
This is caused indirectly by #2485. I'll fix!
