### ISSUE TITLE
Update HPO etc

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2543]
https://github.com/obophenotype/human-phenotype-ontology/releases/tag/v2021-04-13

**Comment by northwestwitch** [comment]
**03-06-21**.

- Updated HPO on stage: 🆗 

![image](https://user-images.githubusercontent.com/28093618/120704009-54290b00-c4b6-11eb-9a05-ce3983501ad7.png)

- Updated HPO on prod: 🆗 

![image](https://user-images.githubusercontent.com/28093618/120704176-8fc3d500-c4b6-11eb-98a5-aec2b08ba83a.png)

- Updated OMIM-auto panel on stage: 🆗 

![image](https://user-images.githubusercontent.com/28093618/120704714-3c05bb80-c4b7-11eb-9237-1e926b60805a.png)

- Updated OMIM-auto panel on prod: 🆗 

![image](https://user-images.githubusercontent.com/28093618/120705094-a9195100-c4b7-11eb-8abb-fda681257818.png)

- Update diseases (OMIM) on stage: 🆗 

![image](https://user-images.githubusercontent.com/28093618/120705355-03b2ad00-c4b8-11eb-800c-a39314de3381.png)

- Update diseases (OMIM) on prod: 🆗 

![image](https://user-images.githubusercontent.com/28093618/120705531-3d83b380-c4b8-11eb-9922-9da2cb10b8fa.png)

- Update genes on stage: --- ERROR ⛔ -----

```
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda//envs/prod-stage/bin/scout", line 8, in <module>
    sys.exit(cli())
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/scout/commands/update/genes.py", line 106, in genes
    transcripts = load_transcripts(adapter, ensembl_transcripts, genome_build, ensembl_genes)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/scout/load/transcript.py", line 35, in load_transcripts
    transcripts_dict = parse_transcripts(transcripts_lines)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/scout/parse/ensembl.py", line 119, in parse_transcripts
    tx_id = tx["ensembl_transcript_id"]
KeyError: 'ensembl_transcript_id'
```

Thank goodness it failed when testing on stage!

I won't try to update prod until we understand what happened and we fix it!
