### ISSUE TITLE
scout update genes fails on emsebl gene end (server ok?)

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2546]
```
(stage) [hiseq.clinical@hippocampus ~]$ scout update genes --api-key VERY_SECRET

2021-04-15 16:12:58 clinical-db.scilifelab.se urllib3.connectionpool[5644] DEBUG https://www.ensembl.org:443 "GET /biomart/martservice?query=%3C?xml%20version=%221.0%22%20encoding=%22UTF-8%22?%3E%0A%3C!DOCTYPE%20Query%3E%0A%3CQuery%20%20virtualSchemaName%20=%20%22default%22%20formatter%20=%20%22TSV%22%20header%20=%20%220%22%20uniqueRows%20=%20%220%22%20count%20=%20%22%22%20datasetConfigVersion%20=%20%220.6%22%20completionStamp%20=%20%221%22%3E%0A%0A%09%3CDataset%20name%20=%20%22hsapiens_gene_ensembl%22%20interface%20=%20%22default%22%20%3E%0A%09%09%3CFilter%20name%20=%20%22chromosome_name%22%20value%20=%20%221,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y,MT%22/%3E%0A%09%09%3CAttribute%20name%20=%20%22chromosome_name%22%20/%3E%0A%09%09%3CAttribute%20name%20=%20%22start_position%22%20/%3E%0A%09%09%3CAttribute%20name%20=%20%22end_position%22%20/%3E%0A%09%09%3CAttribute%20name%20=%20%22ensembl_gene_id%22%20/%3E%0A%09%09%3CAttribute%20name%20=%20%22hgnc_symbol%22%20/%3E%0A%09%09%3CAttribute%20name%20=%20%22hgnc_id%22%20/%3E%0A%09%3C/Dataset%3E%0A%3C/Query%3E HTTP/1.1" 500 10633
...
2021-04-15 16:12:58 clinical-db.scilifelab.se scout.utils.link[5644] DEBUG Ensembl gene None is missing hgnc id. Skipping
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda//envs/prod-stage/bin/scout", line 8, in <module>
    sys.exit(cli())
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/scout/commands/update/genes.py", line 98, in genes
    build=build,
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/scout/load/hgnc_gene.py", line 135, in load_hgnc_genes
    genemap_lines=genemap_lines,
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/scout/utils/link.py", line 211, in link_genes
    add_ensembl_info(genes, ensembl_lines)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/scout/utils/link.py", line 65, in add_ensembl_info
    for ensembl_gene in ensembl_genes:
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/scout/parse/ensembl.py", line 171, in parse_ensembl_genes
    yield parse_ensembl_line(line, header)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/scout/parse/ensembl.py", line 41, in parse_ensembl_line
    ensembl_info["gene_end"] = int(value)
ValueError: invalid literal for int() with base 10: '</section>    </section>'
```

**Comment by northwestwitch** [comment]
See also #2294. This whole process of updating the database should be revisited I think. We must first check that the updates file is available, then we drop the existing collections

**Comment by dnil** [comment]
Ok, this is now ok on stage, but we still need to fix it, presumably by adding a `--files` option to the update commands to pair with `download everything`. Closing for now, as there is already #2294.
