### ISSUE TITLE
Fresh bug on stage environment (for now..)

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2547]
```
2021-04-15 16:24:27,803 - scout.server.app - ERROR: Exception on /cust002/cases [GET] [in /home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/utils.py", line 26, in decorated_function
    context = func(*args, **kwargs)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/institutes/views.py", line 105, in cases
    data = controllers.cases(store, all_cases, prioritized_cases, limit)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/institutes/controllers.py", line 189, in cases
    case_obj = populate_case_obj(case_obj)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/institutes/controllers.py", line 185, in populate_case_obj
    case_obj["display_track"] = TRACKS[case_obj.get("track", "rare")]
KeyError: None
```

**Comment by dnil** [comment]
Its just two old cases with track: null. Ive updated them. But we should probably update that code anyway: the intention was to have a fallback to rare in case of no value - and value: null kind of should be treated the same?

**Comment by northwestwitch** [comment]
Yes we should fix it, Perhaps it occurs also on prod if one decides to show a high number of cases

**Comment by dnil** [comment]
There are none right now, and your latest fix should have blocked at least one avenue to having one, so no rush! Lets fix at low prio.

**Comment by dnil** [comment]
For future reference: https://docs.mongodb.com/manual/tutorial/query-for-null-fields/#std-label-faq-developers-query-for-nulls

**Comment by dnil** [comment]
Ok, this is now appearing in more cases on stage. Likely from old non-track cases being revisited and updated with track:null. It could be a matter of time before one of these blocks the case view in prod. Slightly higher prio now! 😅

**Comment by northwestwitch** [comment]
![image](https://user-images.githubusercontent.com/28093618/115006400-1f7ed700-9ea9-11eb-95ff-743dad49bc6c.png)

**Comment by dnil** [comment]
![Slackbot panic](https://i.kym-cdn.com/photos/images/original/000/644/709/d4a.gif)
