### ISSUE TITLE
Broken dashboard slice - missing value again?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2550]
2021-04-16 14:37:15,544 - scout.server.app - ERROR: Exception on /dashboard [POST] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/dashboard/views.py", line 76, in index
   data = get_dashboard_info(store, institute_id, slice_query)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/dashboard/controllers.py", line 31, in get_dashboard_info
   adapter, institute_id=institute_id, slice_query=slice_query
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/dashboard/controllers.py", line 186, in get_general_case_info
   cases = adapter.cases(owner=institute_id, name_query=name_query)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/adapter/mongo/case.py", line 329, in cases
   order = self._populate_name_query(query, name_query, owner, collaborator)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/adapter/mongo/case.py", line 159, in _populate_name_query
   query_term = name_query[name_query.index(":") + 1 :].strip()
ValueError: substring not found

**Comment by dnil** [comment]
This is new, right?

**Comment by northwestwitch** [comment]
> This is new, right?

Unfortunately yes.
