### ISSUE TITLE
variant other_causative unset?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2575]
Oopsie..

```
2021-04-27 12:43:27,029 - scout.server.app - ERROR: Exception on /cust002/F0039441/6300928d5b48e26e48cb6eb31d9dce8c [GET] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 26, in decorated_function
   context = func(*args, **kwargs)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variant/views.py", line 44, in variant
   data = variant_controller(store, institute_id, case_name, variant_id=variant_id)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variant/controllers.py", line 186, in variant
   causative for causative in store.other_causatives(case_obj, variant_obj)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variant/controllers.py", line 186, in <listcomp>
   causative for causative in store.other_causatives(case_obj, variant_obj)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/adapter/mongo/variant.py", line 608, in other_causatives
   yield other_causative
UnboundLocalError: local variable 'other_causative' referenced before assignment
```

**Comment by dnil** [comment]
My bad. I could have just declared it None first or made a safer structure - was too impressed with simplification. PR incoming.

**Comment by northwestwitch** [comment]
> My bad. I could have just declared it None first or made a safer structure - was too impressed with simplification. PR incoming.

No problem, we can create a quick hotfix release!
