### ISSUE TITLE
Export variants feature crashing when one of the variants has no primary transcripts gene key

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2585]
```
2021-04-29 14:39:17,293 - scout.server.app - ERROR: Exception on /cust099/30/variants [POST] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 26, in decorated_function
    context = func(*args, **kwargs)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/views.py", line 124, in variants
    return controllers.download_variants(store, case_obj, variants_query)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/controllers.py", line 383, in download_variants
    export_lines = variant_export_lines(store, case_obj, variant_objs.limit(500))
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/controllers.py", line 430, in variant_export_lines
    gene_info = variant_export_genes_info(store, gene_list, case_obj.get("genome_build"))
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/controllers.py", line 520, in variant_export_genes_info
    gene_canonical_txs, gene_primary_txs = match_gene_txs_variant_txs(gene_obj, hgnc_gene)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/controllers.py", line 486, in match_gene_txs_variant_txs
    if tx_refseq in hgnc_gene.get("primary_transcripts"):
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by northwestwitch** [comment]
Dang such a stupid error! 😩

**Comment by northwestwitch** [comment]
We're getting a number of emails with this error today. Time to make a new release!
