### ISSUE TITLE
hgnc_symbols may not be defined for STRs

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2626]
To reproduce, an STR causative on stage and visit the Causatives page. Switch to current master and:
```
2021-05-17 15:09:14,266 - scout.server.app - ERROR: Exception on /cust002/causatives [GET] [in /home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/utils.py", line 26, in decorated_function
   context = func(*args, **kwargs)
 File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/institutes/views.py", line 140, in causatives
   variants.sort("hgnc_symbols", pymongo.ASCENDING)
 File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/institutes/views.py", line 140, in <lambda>
   variants.sort("hgnc_symbols", pymongo.ASCENDING)
KeyError: 'hgnc_symbols'
```
Compare old release version 4.33.1, where it works..
![Screenshot 2021-05-17 at 15 20 30](https://user-images.githubusercontent.com/758570/118495410-76cfcb80-b723-11eb-8ada-ba1db7e7a64a.png)

**Comment by dnil** [comment]
Just use a `.get` in the lambda function..
