### ISSUE TITLE
master version issue (not in prod): attempting to fetch classification from missing variant?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2655]
2021-05-24 10:12:23,542 - scout.server.app - ERROR: Exception on /cust000/F0005756-mip7 [GET] [in /home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/utils.py", line 26, in decorated_function
   context = func(*args, **kwargs)
 File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/cases/views.py", line 66, in case
   data = controllers.case(store, institute_obj, case_obj)
 File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/cases/controllers.py", line 96, in case
   _populate_acmg(causatives)
 File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/cases/controllers.py", line 244, in _populate_acmg
   if isinstance(variant.get("acmg_classification"), int):
AttributeError: 'str' object has no attribute 'get'

**Comment by northwestwitch** [comment]
@dnil do you have time to work on this? Otherwise I can take it

**Comment by dnil** [comment]
I think it is fine, but I can take a little help with testing. Two minutes!

**Comment by dnil** [comment]
Ok, its on stage now. Looks good so far, but if you could check the ones you found earlier that'd be great! I think I have found one, which is now ok.
