### ISSUE TITLE
Handle Loqus CalledProcessError Exception to avoid variant page crashing

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2725]
This error is causing variants page to crash. I recall that some try/catch block was in place when running queries on LoqusDB cli, but it's not working for the following error:

```subprocess.CalledProcessError: Command '['/home/hiseq.clinical/miniconda/envs/P_loqusdb/bin/loqusdb', '--config', '/home/hiseq.clinical/servers/config/clinical-db.scilifelab.se/loqusdb.yaml', 'variants', '--to-json', '--variant-id', '5_138283171_C_T', '--case-count']' died with <Signals.SIGSEGV: 11>.```

**Comment by mikaell** [comment]
I can have a look at this.

**Comment by mikaell** [comment]
Loqusdb requires a module named *cyvcf2* which seems to be missing in the python environment. This causes Loqusdb to crash on ClinicalDB. However, on Hasta where cyvcf2 is installed, the command works.


```
$ loqusdb --config /home/hiseq.clinical/servers/config/clinical-db.scilifelab.se/loqusdb.yaml variants --to-json --variant-id 5_138283171_C_T --case-count
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/bin/loqusdb", line 7, in <module>
    from loqusdb.__main__ import base_command
  File "/home/hiseq.clinical/miniconda/lib/python2.7/site-packages/loqusdb/__main__.py", line 14, in <module>
    from loqusdb.commands import base_command
  File "/home/hiseq.clinical/miniconda/lib/python2.7/site-packages/loqusdb/commands/__init__.py", line 4, in <module>
    from .load import load as load_command
  File "/home/hiseq.clinical/miniconda/lib/python2.7/site-packages/loqusdb/commands/load.py", line 8, in <module>
    from loqusdb.utils import load_database
  File "/home/hiseq.clinical/miniconda/lib/python2.7/site-packages/loqusdb/utils/__init__.py", line 4, in <module>
    from .load import (load_variants, load_family, load_database)
  File "/home/hiseq.clinical/miniconda/lib/python2.7/site-packages/loqusdb/utils/load.py", line 8, in <module>
    from loqusdb.vcf_tools import (get_formated_variant, get_vcf)
  File "/home/hiseq.clinical/miniconda/lib/python2.7/site-packages/loqusdb/vcf_tools/__init__.py", line 1, in <module>
    from .vcf import get_vcf
  File "/home/hiseq.clinical/miniconda/lib/python2.7/site-packages/loqusdb/vcf_tools/vcf.py", line 4, in <module>
    from cyvcf2 import VCF
ImportError: No module named cyvcf2
[hiseq.clinical@hippocampus ~]$ python
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import cyvcf2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named cyvcf2
>>>
```

Checking Conda, Hasta:
```
[0|0|141] [mikael.laaksonen@hasta:~] [S_main] 6m11s $ conda list |grep vcf
cyvcf2                    0.9.0                     <pip>
vcftoolbox                1.5                       <pip>
```

Checking Conda, Clinicaldb:
```
[hiseq.clinical@hippocampus ~]$ conda list |grep vcf
vcftoolbox                1.5                       <pip>
```

I don't know what happened to the cyvcf module…

**Comment by mikaell** [comment]
There seems to be several different reasons why calling Loqusdb with Subprocess has failed the past months. One is related to the too strict ulimit previously set stoping creation of new process. The other reasons are not clear because of insufficient log messages.

I have created a patch that:
a. Will make Scout continue execution -even though the subprocess call fails for some reason
b. Adds stack trace to the error message printed in the logs (for finding the the bug(s))
