### ISSUE TITLE
Individual not found for a case triggers error

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2915]
2021-10-08 16:20:34,052 - scout.server.app - ERROR: Exception on /cust003/21236/85f1d30e06c224c8d2733a17bc6b0f48 [GET] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 39, in decorated_function
    context = func(*args, **kwargs)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variant/views.py", line 44, in variant
    data = variant_controller(store, institute_id, case_name, variant_id=variant_id)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variant/controllers.py", line 242, in variant
    is_affected(variant_obj, case_obj)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variant/utils.py", line 395, in is_affected
    individual = individuals[sample_obj.get("sample_id")]
KeyError: 'ACC8431A7'

**Comment by northwestwitch** [comment]
This is quite weird. The error is triggered by the request of a NF1 variant for the case 21236 (gladurchin). This case doesn't have the variant in question, that actually belongs to another case (21240, stilllizard)-> https://scout.scilifelab.se/cust003/21240/85f1d30e06c224c8d2733a17bc6b0f48.

I have no idea how the user ended up on that wrong link (could also be that they manually modified the URL, perhaps trying to display a variant id on the wrong sample). In this case I think I'd just make the pages redirect to the variants list, displaying an error.
