### ISSUE TITLE
Deprecated wtforms.TextField and problem with flask-ldap3-login after WTForms upgrade

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2961]
TextField was removed in wtforms v.3.0.0 (released yesterday Nov 7th). Now all the imports of this element are broken and should be replaced by wtforms.StringField. https://wtforms.readthedocs.io/en/3.0.x/whats_new/?highlight=textfield

**Comment by northwestwitch** [comment]
The fixed looked quite straightforward but here comes a problem: we are using a library named flask_ldap3_login to handle LDAP logins. flask_ldap3_login is also using the deprecated TextField and it's bugged at the moment. I'll try to create a PR in the other repo to fix the issue!


```
(py38) chiararasi@ChiaraRMBP:~/Documents/work/GITs/scout$ scout --demo serve
Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/py38/bin/scout", line 33, in <module>
    sys.exit(load_entry_point('scout-browser', 'console_scripts', 'scout')())
  File "/Users/chiararasi/miniconda3/envs/py38/bin/scout", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/commands/__init__.py", line 1, in <module>
    from .base import cli
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/commands/base.py", line 25, in <module>
    from scout.server.app import create_app
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/app.py", line 13, in <module>
    from .blueprints import (
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/blueprints/login/__init__.py", line 2, in <module>
    from .views import login_bp
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/blueprints/login/views.py", line 17, in <module>
    from flask_ldap3_login.forms import LDAPLoginForm
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask_ldap3_login/forms.py", line 15, in <module>
    class LDAPLoginForm(FlaskForm):
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask_ldap3_login/forms.py", line 26, in LDAPLoginForm
    username = wtforms.StringField('Username', validators=[validators.Required()])
AttributeError: module 'wtforms.validators' has no attribute 'Required'
```

**Comment by northwestwitch** [comment]
Check this issue for reference: https://github.com/nickw444/flask-ldap3-login/issues/75

**Comment by northwestwitch** [comment]
Created a PR in the other repo: https://github.com/nickw444/flask-ldap3-login/pull/96

**Comment by dnil** [comment]
Im sure its been among the test deprecation warnings for some time.. 🙄

**Comment by northwestwitch** [comment]
> Im sure its been among the test deprecation warnings for some time..

Yes, I've seen it so many times!
