### ISSUE TITLE
Panel deleted - another NoneType not subscriptable (variants - controllers)..

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2982]
Case variants not viewable when default panel missing
```
2021-11-17 14:26:24,920 - scout.server.app - ERROR: Exception on /cust087/movedferret/cancer/variants [GET] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 39, in decorated_function
   context = func(*args, **kwargs)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/views.py", line 380, in cancer_variants
   page=page,
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/controllers.py", line 717, in cancer_variants
   gene_panel_lookup = store.gene_to_panels(case_obj)  # build variant object
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/adapter/mongo/panel.py", line 295, in gene_to_panels
   for gene in panel_obj["genes"]:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by northwestwitch** [comment]
I'm trying to reproduce the same error locally. Loaded the demo case and then removed the only panel available. variants page still works..

**Comment by dnil** [comment]
Hmmm, ok, so something more complicated then. I remember that panel vaguely - there were several variants created with like the same or almost the same name.

**Comment by northwestwitch** [comment]
It's definitely happening for cancer variants, so perhaps removing a gene panel that has TP53 could break it?

**Comment by northwestwitch** [comment]
Yeah, I could reproduce it by using a TP53 gene panel, check the fix PR howto!
