### ISSUE TITLE
scout.server.app - ERROR: Exception on /api/v1/genes

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3028]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/genes/views.py", line 54, in api_genes
    json_out = controllers.genes_to_json(store, query, build)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/genes/controllers.py", line 65, in genes_to_json
    for gene in gene_query
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/genes/controllers.py", line 58, in <dictcomp>
    json_terms = {
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/cursor.py", line 1207, in next
    if len(self.__data) or self._refresh():
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/cursor.py", line 1124, in _refresh
    self.__send_message(q)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/cursor.py", line 1001, in __send_message
    address=self.__address)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1372, in _run_operation_with_response
    exhaust=exhaust)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1471, in _retryable_read
    return func(session, server, sock_info, slave_ok)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1366, in _cmd
    unpack_res)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/server.py", line 135, in run_operation_with_response
    _check_command_response(first, sock_info.max_wire_version)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/pymongo/helpers.py", line 164, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Regular expression is invalid: missing ), full error: {'operationTime': Timestamp(1638883226, 2392), 'ok': 0.0, 'errmsg': 'Regular expression is invalid: missing )', 'code': 51091, 'codeName': 'Location51091', '$clusterTime': {'clusterTime': Timestamp(1638883226, 2392), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'keyId': 0}}}

**Comment by northwestwitch** [comment]
Somebody is likely trying to get the genes using the API and is failing because of this error

**Comment by dnil** [comment]
Yes; is there a stage version of the react app up somewhere? Or what about the chanjo2 dev stuff?

**Comment by dnil** [comment]
Anyway, we probably shouldn't fail that way even if the query isn't perfect, right?

**Comment by northwestwitch** [comment]
I don't know where the query comes from, but let's make it return either the genes or an error decently formatted
