### ISSUE TITLE
update gene panel - server error

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#3043]
Hello!

We're attempting to update our gene panels but we keep getting a server error. Any idea when this will work? :) We tried with the sample file and last year's file too, so it shouldn't be a file format issue.

Also, I'm a little confused regarding the required file format. The instructions in https://clinical-genomics.github.io/scout/user-guide/panels/#uploading-a-new-gene-panel-version says to use a tab or semi colon separated file, but when I click on the edit button in https://scout.scilifelab.se/panels a CSV file is requested:
![image](https://user-images.githubusercontent.com/57791644/145539500-6e52ff58-20b3-42a3-baa3-c80da3735dc4.png)

Thank you!

**Comment by dnil** [comment]
Thank you! It seems to be an inadvertent issue from the latest update with hiding/deleting gene panels. We'll fix soonish; we were just about to release some other bug fixes though.

**Comment by dnil** [comment]
```
2021-12-10 09:03:05,026 - scout.server.app - ERROR: Exception on /panels [POST] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 39, in decorated_function
   context = func(*args, **kwargs)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/panels/views.py", line 24, in panels
   controllers.panel_create_or_update(store, request)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/panels/controllers.py", line 74, in panel_create_or_update
   panel_obj = store.gene_panel(request.form["panel_name"], include_hidden=current_user.is_admin)
TypeError: gene_panel() got an unexpected keyword argument 'include_hidden'
```

**Comment by 4WGH** [comment]
can we proceed now with submission?

**Comment by dnil** [comment]
Hi! Are you are asking if the new version is out on the Solna server? Not yet, but we will try to wrap this one up soon.

**Comment by 4WGH** [comment]
We need to update our panel and wonder when can I procced :) 
 I will wait for your mail then :)

Michela
