### ISSUE TITLE
Error: Managed variant has to have chr, pos, ref and alt.

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3059]
```
2021-12-16 16:21:42,973 - scout.server.app - ERROR: Exception on /upload_csv [POST] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/build/managed_variant.py", line 24, in build_managed_variant
    chromosome=str(managed_variant_info["chromosome"]),
KeyError: 'chromosome'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/managed_variants/views.py", line 46, in upload_managed_variants
    result = controllers.upload_managed_variants(store, lines, institutes, current_user._id)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/managed_variants/controllers.py", line 136, in upload_managed_variants
    managed_variant_obj = build_managed_variant(managed_variant_info)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/build/managed_variant.py", line 37, in build_managed_variant
    raise KeyError("Managed variant has to have chr, pos, ref and alt.")
KeyError: 'Managed variant has to have chr, pos, ref and alt.'
```

**Comment by dnil** [comment]
An error flash would be a lot nicer. On a possibly connected issue, the docs link points to gene panel rather than variant csv. Should also be updated! 😊
