### ISSUE TITLE
TypeError: 'NoneType' object is not iterable when exporting variants

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3077]
```
2022-01-04 14:15:41,596 - scout.server.app - ERROR: Exception on /verified [GET] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/views.py", line 541, in download_verified
    if controllers.verified_excel_file(store, user_institutes, temp_excel_dir):
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/controllers.py", line 1223, in verified_excel_file
    cust_verified = export_verified_variants(verif_vars, unique_callers)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/export/variant.py", line 102, in export_verified_variants
    for gene in variant.get("genes"):  # this will be a unique long field in the document
TypeError: 'NoneType' object is not iterable
```

**Comment by northwestwitch** [comment]
This error should have been triggered by the "Download verified variants" option present in the dashboard:

![image](https://user-images.githubusercontent.com/28093618/148738166-7c623337-40bd-4e8d-95d3-d6e9b913fee8.png)
