### ISSUE TITLE
Problem with pedigree svg permissions

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3096]
```
2022-01-19 13:57:10,291 - scout.server.app - ERROR: Exception on /cust003/21330/pdf_report [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
   response = self.full_dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
   rv = self.dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
 File "/home/worker/app/scout/server/blueprints/cases/views.py", line 232, in pdf_case_report
   with open(os.path.join(cases_bp.static_folder, "madeline.svg"), "w") as temp_madeline:
PermissionError: [Errno 13] Permission denied: '/home/worker/app/scout/server/blueprints/cases/static/madeline.svg'
```

**Comment by dnil** [comment]
Could be the same fix as for #3093!
