### ISSUE TITLE
ModuleNotFoundError: No module named 'defusedxml'

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3135]
The error occurs when you launch the containerized app via `docker-compose up`

```
scout-cli    | Traceback (most recent call last):
scout-cli    |   File "/venv/bin/scout", line 33, in <module>
scout-cli    |     sys.exit(load_entry_point('scout-browser', 'console_scripts', 'scout')())
scout-cli    |   File "/venv/bin/scout", line 25, in importlib_load_entry_point
scout-cli    |     return next(matches).load()
scout-cli    |   File "/usr/local/lib/python3.8/importlib/metadata.py", line 77, in load
scout-cli    |     module = import_module(match.group('module'))
scout-cli    |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
scout-cli    |     return _bootstrap._gcd_import(name[level:], package, level)
scout-cli    |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
scout-cli    |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
scout-cli    |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
scout-cli    |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
scout-cli    |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
scout-cli    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
scout-cli    |   File "/home/worker/app/scout/commands/__init__.py", line 1, in <module>
scout-cli    |     from .base import cli
scout-cli    |   File "/home/worker/app/scout/commands/base.py", line 12, in <module>
scout-cli    |     from scout.commands.convert import convert
scout-cli    |   File "/home/worker/app/scout/commands/convert.py", line 8, in <module>
scout-cli    |     from scout.server.extensions import store
scout-cli    |   File "/home/worker/app/scout/server/extensions/__init__.py", line 14, in <module>
scout-cli    |     from .loqus_extension import LoqusDB
scout-cli    |   File "/home/worker/app/scout/server/extensions/loqus_extension.py", line 13, in <module>
scout-cli    |     from scout.utils.scout_requests import get_request_json as api_get
scout-cli    |   File "/home/worker/app/scout/utils/scout_requests.py", line 9, in <module>
scout-cli    |     from defusedxml import ElementTree
scout-cli    | ModuleNotFoundError: No module named 'defusedxml'
```

**Comment by northwestwitch** [comment]
Mmm, I can't reproduce any more. Perhaps I've removed some dependency while testing a new PR? Closing!

**Comment by dnil** [comment]
I saw the same for 'defusedxml' a little while back; have the searches left in history, but I can't remember for what env. 😊 
Might be related to that old deprecation warning by any chance? https://github.com/Clinical-Genomics/scout/pull/1293

**Comment by northwestwitch** [comment]
Ah yes, it is mentioned in that issue. Let's keep an eye open!

**Comment by northwestwitch** [comment]
You know what I did to cause the error? I've removed Weasyprint and Flask_weasyprint from requirements.txt..

**Comment by dnil** [comment]
Ooh, it was probably the same for me then when testing to release the weasyprint version! Its a freeze now, so cascades into freezing that as well.. It was possible to thaw in the end though.

**Comment by northwestwitch** [comment]
It is a freeze and that's why it was complaining for deprecated stuff

**Comment by dnil** [comment]
Yeah, here: #3111. Unfreezing failed with docker, but worked with conda. Since it didn't give nice reports anyway, I didn't go any deeper.

**Comment by dnil** [comment]
Looks like there is a new defusedxml 0.8 on its way, but not quite out yet?

**Comment by northwestwitch** [comment]
> It is a freeze and that's why it was complaining for deprecated stuff



> Looks like there is a new defusedxml 0.8 on its way, but not quite out yet?

Check #3136. If you remove Flask-WeasyPrint you need to install defusedxml. But you don't need to freeze it!
