### ISSUE TITLE
Bug in chanjo-report

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3137]
2022-02-04 14:30:20,824 - scout.server.app - ERROR: Exception on /reports/report [POST] [in /venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/venv/lib/python3.8/site-packages/chanjo_report/server/blueprints/report/views.py", line 131, in report
    return render_template("report/report.html", **data)
TypeError: render_template() argument after ** must be a mapping, not str

**Comment by dnil** [comment]
Yes, presumably, though its not clear what caused it. It is also a bug in 4.47. That particular part may or may not have updated on main, with the change of PDF library.

**Comment by northwestwitch** [comment]
Right! Before we release a new version, we need to replace WeasyPrint also in chanjo-report! 😫

**Comment by northwestwitch** [comment]
Ok, I'm moving this issue in there now!
