### ISSUE TITLE
genes_to_phenotype.txt file not found when downloading resources to update database genes

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3191]
Missing resource: https://ci.monarchinitiative.org/view/hpo/job/hpo.annotations/lastSuccessfulBuild/artifact/rare-diseases/util/annotation/genes_to_phenotype.txt

```
2022-02-28 11:19:37 ChiaraRMBP.local scout.utils.scout_requests[22869] INFO Fetching HPO information from http://compbio.charite.de
2022-02-28 11:19:37 ChiaraRMBP.local scout.utils.scout_requests[22869] INFO Requesting https://ci.monarchinitiative.org/view/hpo/job/hpo.annotations/lastSuccessfulBuild/artifact/rare-diseases/util/annotation/genes_to_phenotype.txt
2022-02-28 11:19:37 ChiaraRMBP.local urllib3.connectionpool[22869] DEBUG Starting new HTTPS connection (1): ci.monarchinitiative.org:443
2022-02-28 11:19:37 ChiaraRMBP.local urllib3.connectionpool[22869] DEBUG https://ci.monarchinitiative.org:443 "GET /view/hpo/job/hpo.annotations/lastSuccessfulBuild/artifact/rare-diseases/util/annotation/genes_to_phenotype.txt HTTP/1.1" 404 554
2022-02-28 11:19:37 ChiaraRMBP.local scout.utils.scout_requests[22869] WARNING Something went wrong, perhaps the api key is not valid?
Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/py38/bin/scout", line 33, in <module>
    sys.exit(load_entry_point('scout-browser', 'console_scripts', 'scout')())
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/cli.py", line 600, in main
    return super().main(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/commands/download/everything.py", line 35, in everything
    ctx.invoke(hpo, out_dir=out_dir)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/commands/download/hpo.py", line 70, in hpo
    hpo_info = fetch_hpo_files(**kwargs)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/utils/scout_requests.py", line 230, in fetch_hpo_files
    hpo_files["genes_to_phenotype"] = fetch_genes_to_hpo_to_disease()
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/utils/scout_requests.py", line 192, in fetch_genes_to_hpo_to_disease
    return fetch_resource(url)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/utils/scout_requests.py", line 152, in fetch_resource
    response = get_request(url)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/utils/scout_requests.py", line 121, in get_request
    raise err
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/utils/scout_requests.py", line 117, in get_request
    response.raise_for_status()
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ci.monarchinitiative.org/view/hpo/job/hpo.annotations/lastSuccessfulBuild/artifact/rare-diseases/util/annotation/genes_to_phenotype.txt

```

**Comment by dnil** [comment]
:( They were down last week as well, but then also the hpo.jax.org web-page so I assumed the two were connected. The latter is up now though.

**Comment by northwestwitch** [comment]
The working link is: https://ci.monarchinitiative.org/job/hpo.annotations/lastSuccessfulBuild/artifact/rare-diseases/util/annotation/genes_to_phenotype.txt

**Comment by dnil** [comment]
hpo.jax.org has this as the official redirect on their page:
[http://purl.obolibrary.org/obo/hp/hpoa/genes_to_phenotype.tx](http://purl.obolibrary.org/obo/hp/hpoa/genes_to_phenotype.txt)
Perhaps it would be more stable?
