### ISSUE TITLE
Bug related to assigning OMIM terms?

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3260]
2022-03-23 09:39:22,645 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /cust003/18073/73747e36c973f9b3036ed2d92f147461 [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/worker/app/scout/server/utils.py", line 76, in decorated_function
    return render_template(template_name, **context)
  File "/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/worker/app/scout/server/blueprints/variant/templates/variant/variant.html", line 416, in top-level template code
    {% if current_variant %}
  File "/home/worker/app/scout/server/templates/layout_bs4.html", line 1, in top-level template code
    {% extends "bootstrap4.html" %}
  File "/home/worker/app/scout/server/templates/bootstrap4.html", line 57, in top-level template code
    {% block body %}
  File "/home/worker/app/scout/server/templates/bootstrap4.html", line 60, in block 'body'
    {% block content %}
  File "/home/worker/app/scout/server/templates/layout_bs4.html", line 82, in block 'content'
    {% block content_main %}{% endblock %}
  File "/home/worker/app/scout/server/blueprints/variant/templates/variant/variant.html", line 189, in block 'content_main'
    {{ modal_causative(case, institute, variant) }}
  File "/venv/lib/python3.8/site-packages/jinja2/runtime.py", line 828, in _invoke
    rv = self._func(*arguments)
  File "/home/worker/app/scout/server/blueprints/variant/templates/variant/utils.html", line 40, in template
    {% if 'disease_nr' in omim_term %}
TypeError: argument of type 'int' is not iterable

**Comment by northwestwitch** [comment]
This is also probably due to the change of OMIM objects, I'll fix after lunch!
