### ISSUE TITLE
Bug when exporting vars to Matchmaker

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3261]
```
2022-03-23 09:44:23,515 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /cust101/A1383/mme_add [POST] [in /venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/worker/app/scout/server/blueprints/cases/views.py", line 124, in matchmaker_add
    controllers.matchmaker_add(request, institute_id, case_name)
  File "/home/worker/app/scout/server/blueprints/cases/controllers.py", line 1172, in matchmaker_add
    disorders = omim_terms(store, case_obj) if "disorders" in request.form else []
  File "/home/worker/app/scout/parse/matchmaker.py", line 55, in omim_terms
    omim_term = store.disease_term(disorder)
  File "/home/worker/app/scout/adapter/mongo/omim.py", line 115, in disease_term
    disease_identifier = int(disease_identifier)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'
```

**Comment by dnil** [comment]
Hm, could it be the old style objects?

**Comment by northwestwitch** [comment]
Could be, that's why the "Possible" in the title :)

**Comment by northwestwitch** [comment]
> Hm, could it be the old style objects?

It was exactly that!
