### ISSUE TITLE
New Jinja2 release breaks the containerized app

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3271]
There was a new Jinja2 release yesterday: https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0

Something (I highly suspect the change in WithExtension) breaks the code, so when you try to install the container on cg-vm1, or even run docker-compose up locally, the app won't launch.

Error I see locally with `docker-compose up`:

```
scout_scout-web_1 exited with code 3
scout-cli    | Traceback (most recent call last):
scout-cli    |   File "/venv/bin/scout", line 33, in <module>
scout-cli    |     sys.exit(load_entry_point('scout-browser', 'console_scripts', 'scout')())
scout-cli    |   File "/venv/bin/scout", line 25, in importlib_load_entry_point
scout-cli    |     return next(matches).load()
scout-cli    |   File "/usr/local/lib/python3.8/importlib/metadata.py", line 77, in load
scout-cli    |     module = import_module(match.group('module'))
scout-cli    |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
scout-cli    |     return _bootstrap._gcd_import(name[level:], package, level)
scout-cli    |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
scout-cli    |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
scout-cli    |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
scout-cli    |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
scout-cli    |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
scout-cli    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
scout-cli    |   File "/home/worker/app/scout/commands/__init__.py", line 1, in <module>
scout-cli    |     from .base import cli
scout-cli    |   File "/home/worker/app/scout/commands/base.py", line 12, in <module>
scout-cli    |     from scout.commands.convert import convert
scout-cli    |   File "/home/worker/app/scout/commands/convert.py", line 8, in <module>
scout-cli    |     from scout.server.extensions import store
scout-cli    |   File "/home/worker/app/scout/server/extensions/__init__.py", line 19, in <module>
scout-cli    |     toolbar = DebugToolbarExtension()
scout-cli    |   File "/venv/lib/python3.8/site-packages/flask_debugtoolbar/__init__.py", line 50, in __init__
scout-cli    |     self.jinja_env = Environment(
scout-cli    |   File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 363, in __init__
scout-cli    |     self.extensions = load_extensions(self, extensions)
scout-cli    |   File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 117, in load_extensions
scout-cli    |     extension = t.cast(t.Type["Extension"], import_string(extension))
scout-cli    |   File "/venv/lib/python3.8/site-packages/jinja2/utils.py", line 149, in import_string
scout-cli    |     return getattr(__import__(module, None, None, [obj]), obj)
scout-cli    | AttributeError: module 'jinja2.ext' has no attribute 'with_'
```

**Comment by northwestwitch** [comment]
The problem was caused by an external lib (flask-debugtoolbar) that we import among other extensions:

https://github.com/flask-debugtoolbar/flask-debugtoolbar/pull/157

Since we are not using the debug bar any more I'll write a PR to remove any reference to it!
