### ISSUE TITLE
A new version of Werkzeug breaks the code

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3278]
You get: `ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security'`  while running tests

https://werkzeug.palletsprojects.com/en/2.1.x/changes/#version-2-1-0

**Comment by northwestwitch** [comment]
I'm trying to understand how to fix this without freezing Werkzeug to v. 2.0

**Comment by northwestwitch** [comment]
It's not only the tests: you can't even launch the browser:

```
(py38) chiararasi@ChiaraRMBP:~/Documents/work/GITs/scout$ scout --demo serve
Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/py38/bin/scout", line 33, in <module>
    sys.exit(load_entry_point('scout-browser', 'console_scripts', 'scout')())
  File "/Users/chiararasi/miniconda3/envs/py38/bin/scout", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/commands/__init__.py", line 1, in <module>
    from .base import cli
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/commands/base.py", line 12, in <module>
    from scout.commands.convert import convert
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/commands/convert.py", line 8, in <module>
    from scout.server.extensions import store
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/extensions/__init__.py", line 5, in <module>
    from flask_login import LoginManager
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask_login/__init__.py", line 16, in <module>
    from .login_manager import LoginManager
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask_login/login_manager.py", line 24, in <module>
    from .utils import (login_url as make_login_url, _create_identifier,
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask_login/utils.py", line 13, in <module>
    from werkzeug.security import safe_str_cmp
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/werkzeug/security.py)
```

**Comment by northwestwitch** [comment]
The problem is in flask_login. It has been fixed already but looks like the changes have not been released yet:

https://github.com/maxcountryman/flask-login/blob/264ae9707ef3597c9377016e1cd2bf3f1a3ccc39/CHANGES#L21

**Comment by northwestwitch** [comment]
Let's freeze werkzeug until the new version of flask_login is out!

**Comment by northwestwitch** [comment]
There is an issue about this already: https://github.com/maxcountryman/flask-login/issues/636
