### ISSUE TITLE
Logging in to the 4.51 release candidate appears broken!

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3288]
2022-03-31 14:30:07,417 - scout.server.app - ERROR: Exception on /authorized [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
   response = self.full_dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
   rv = self.dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
 File "/home/worker/app/scout/server/blueprints/login/views.py", line 106, in authorized
   google_user = oauth_client.google.parse_id_token(token)
TypeError: parse_id_token() missing 1 required positional argument: 'nonce'

**Comment by dnil** [comment]
Logout and try logging in again..

**Comment by northwestwitch** [comment]
> Logout and try logging in again..

I'm afraid to do so! 😆

**Comment by dnil** [comment]
Remember to leave one browser logged in! 😅
