### ISSUE TITLE
Standardize OMIM info in case documents before case export

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3301]
Some oldish cases contain OMIM diagnoses as a list of integers, some newer cases save OMIM terms as a list of dictionaries. Some downstream applications (CG - https://github.com/Clinical-Genomics/cg/pull/1464) might be strict on parsing the output of the case export functionality, so it would be best to first modify the case and save the OMIM diagnoses in the new format before exporting cases

**Comment by dnil** [comment]
Speaking of that, it would be cool to support https://github.com/phenopackets/phenopacket-schema for export as well. I guess we just need a use case first... 😁

**Comment by northwestwitch** [comment]
> Speaking of that, it would be cool to support https://github.com/phenopackets/phenopacket-schema for export as well. I guess we just need a use case first... 😁

YES!

**Comment by dnil** [comment]
Well timed: this just came in on slack (@jemten).

```
----------------- UPLOAD -----------------------
Fetch latest version from bundle inferret
uploading case inferret to scout
Running command /home/proj/bin/conda/envs/S_scout/bin/scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml export cases --json --case-id inferret
Validating case inferret
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/S_main/bin/cg", line 8, in <module>
    sys.exit(base())
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/cg/cli/upload/scout.py", line 47, in scout
    context.invoke(upload_case_to_scout, case_id=case_id, re_upload=re_upload)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/cg/cli/upload/scout.py", line 140, in upload_case_to_scout
    scout_api.upload(scout_load_config=scout_config_file.full_path, force=re_upload)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/cg/apps/scout/scoutapi.py", line 35, in upload
    case_id=scout_load_config_object.family
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/cg/apps/scout/scoutapi.py", line 140, in get_case
    cases: List[ScoutExportCase] = self.get_cases(case_id=case_id)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/cg/apps/scout/scoutapi.py", line 183, in get_cases
    case_obj = ScoutExportCase(**case_export)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ScoutExportCase
diagnosis_phenotypes -> 0
  value is not a valid integer (type=type_error.integer)```

**Comment by northwestwitch** [comment]
I can fix the case export if you haven't started yet @dnil

**Comment by dnil** [comment]
Sounds great - I have preparations for a lecture I should focus on. 😅
