### ISSUE TITLE
Can't deploy and run Scout using Docker

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3315]
I've tried to install on scout stage a bunch of branches that we have as opened PR, but I'm failing. Some weird error message related a port already in use (used by beacon service? 🤔 )

**Comment by northwestwitch** [comment]
```
[hiseq.clinical@cg-vm1 ~]$ journalctl --user -xe
Apr 25 15:54:08 cg-vm1.scilifelab.se conmon[1451775]: Traceback (most recent call last):
Apr 25 15:54:08 cg-vm1.scilifelab.se conmon[1451775]:   File "/venv/bin/gunicorn", line 8, in <module>
Apr 25 15:54:08 cg-vm1.scilifelab.se conmon[1451775]:     sys.exit(run())
Apr 25 15:54:08 cg-vm1.scilifelab.se conmon[1451775]:   File "/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
Apr 25 15:54:08 cg-vm1.scilifelab.se conmon[1451775]:     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
Apr 25 15:54:08 cg-vm1.scilifelab.se conmon[1451775]:   File "/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
Apr 25 15:54:08 cg-vm1.scilifelab.se conmon[1451775]:     super().run()
Apr 25 15:54:08 cg-vm1.scilifelab.se conmon[1451775]:   File "/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
Apr 25 15:54:08 cg-vm1.scilifelab.se conmon[1451775]:     Arbiter(self).run()
Apr 25 15:54:08 cg-vm1.scilifelab.se conmon[1451775]:   File "/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 229, in run
Apr 25 15:54:08 cg-vm1.scilifelab.se conmon[1451775]:     self.halt(reason=inst.reason, exit_status=inst.exit_status)
Apr 25 15:54:08 cg-vm1.scilifelab.se conmon[1451775]:   File "/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 342, in halt
Apr 25 15:54:08 cg-vm1.scilifelab.se conmon[1451775]:     self.stop()
Apr 25 15:54:08 cg-vm1.scilifelab.se conmon[1451775]:   File "/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 393, in stop
Apr 25 15:54:08 cg-vm1.scilifelab.se conmon[1451775]:     time.sleep(0.1)
Apr 25 15:54:08 cg-vm1.scilifelab.se conmon[1451775]:   File "/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
Apr 25 15:54:08 cg-vm1.scilifelab.se conmon[1451775]:     self.reap_workers()
Apr 25 15:54:08 cg-vm1.scilifelab.se conmon[1451775]:   File "/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
Apr 25 15:54:08 cg-vm1.scilifelab.se conmon[1451775]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
Apr 25 15:54:08 cg-vm1.scilifelab.se conmon[1451775]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Apr 25 15:54:08 cg-vm1.scilifelab.se systemd[1553]: scout@auth_serve_files.service: Main process exited, code=exited, status=1/FAILURE
Apr 25 15:54:08 cg-vm1.scilifelab.se systemd[1553]: scout@auth_serve_files.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- The unit UNIT has entered the 'failed' state with result 'exit-code'.
Apr 25 15:54:14 cg-vm1.scilifelab.se systemd[1553]: Started podman-1451859.scope.
-- Subject: Unit UNIT has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit UNIT has finished starting up.
--
-- The start-up result is done.
Apr 25 15:54:14 cg-vm1.scilifelab.se systemd[1553]: podman-1451859.scope: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- The unit UNIT has successfully entered the 'dead' state.
```

**Comment by northwestwitch** [comment]
Tested the Docker configuration with docker-compose locally. Thank goodness it fails so it gives a hint of what's wrong: some Flask-Alchy thing:


```
mongodb      | {"t":{"$date":"2022-04-25T14:16:39.175+00:00"},"s":"I",  "c":"INDEX",    "id":20345,   "ctx":"LogicalSessionCacheRefresh","msg":"Index build: done building","attr":{"buildUUID":null,"namespace":"config.system.sessions","index":"_id_","commitTimestamp":{"$timestamp":{"t":0,"i":0}}}}
mongodb      | {"t":{"$date":"2022-04-25T14:16:39.176+00:00"},"s":"I",  "c":"INDEX",    "id":20345,   "ctx":"LogicalSessionCacheRefresh","msg":"Index build: done building","attr":{"buildUUID":null,"namespace":"config.system.sessions","index":"lsidTTLIndex","commitTimestamp":{"$timestamp":{"t":0,"i":0}}}}
scout-web_1  | [2022-04-25 14:16:39 +0000] [7] [DEBUG] Current configuration:
scout-web_1  |   config: ./gunicorn.conf.py
scout-web_1  |   wsgi_app: None
scout-web_1  |   bind: ['0.0.0.0:8000']
scout-web_1  |   backlog: 2048
scout-web_1  |   workers: 1
scout-web_1  |   worker_class: sync
scout-web_1  |   threads: 1
scout-web_1  |   worker_connections: 1000
scout-web_1  |   max_requests: 0
scout-web_1  |   max_requests_jitter: 0
scout-web_1  |   timeout: 400
scout-web_1  |   graceful_timeout: 30
scout-web_1  |   keepalive: 2
scout-web_1  |   limit_request_line: 4094
scout-web_1  |   limit_request_fields: 100
scout-web_1  |   limit_request_field_size: 8190
scout-web_1  |   reload: False
scout-web_1  |   reload_engine: auto
scout-web_1  |   reload_extra_files: []
scout-web_1  |   spew: False
scout-web_1  |   check_config: False
scout-web_1  |   print_config: False
scout-web_1  |   preload_app: False
scout-web_1  |   sendfile: None
scout-web_1  |   reuse_port: False
scout-web_1  |   chdir: /home/worker/app
scout-web_1  |   daemon: False
scout-web_1  |   raw_env: []
scout-web_1  |   pidfile: None
scout-web_1  |   worker_tmp_dir: None
scout-web_1  |   user: 1000
scout-web_1  |   group: 1000
scout-web_1  |   umask: 0
scout-web_1  |   initgroups: False
scout-web_1  |   tmp_upload_dir: None
scout-web_1  |   secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
scout-web_1  |   forwarded_allow_ips: ['10.0.2.100', '127.0.0.1']
scout-web_1  |   accesslog: -
scout-web_1  |   disable_redirect_access_to_syslog: False
scout-web_1  |   access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
scout-web_1  |   errorlog: -
scout-web_1  |   loglevel: debug
scout-web_1  |   capture_output: False
scout-web_1  |   logger_class: gunicorn.glogging.Logger
scout-web_1  |   logconfig: None
scout-web_1  |   logconfig_dict: {}
scout-web_1  |   syslog_addr: udp://localhost:514
scout-web_1  |   syslog: True
scout-web_1  |   syslog_prefix: None
scout-web_1  |   syslog_facility: user
scout-web_1  |   enable_stdio_inheritance: False
scout-web_1  |   statsd_host: None
scout-web_1  |   dogstatsd_tags:
scout-web_1  |   statsd_prefix:
scout-web_1  |   proc_name: None
scout-web_1  |   default_proc_name: scout.server.auto:app
scout-web_1  |   pythonpath: None
scout-web_1  |   paste: None
scout-web_1  |   on_starting: <function OnStarting.on_starting at 0x7f23b7c83280>
scout-web_1  |   on_reload: <function OnReload.on_reload at 0x7f23b7c833a0>
scout-web_1  |   when_ready: <function WhenReady.when_ready at 0x7f23b7c834c0>
scout-web_1  |   pre_fork: <function Prefork.pre_fork at 0x7f23b7c835e0>
scout-web_1  |   post_fork: <function Postfork.post_fork at 0x7f23b7c83700>
scout-web_1  |   post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f23b7c83820>
scout-web_1  |   worker_int: <function WorkerInt.worker_int at 0x7f23b7c83940>
scout-web_1  |   worker_abort: <function WorkerAbort.worker_abort at 0x7f23b7c83a60>
scout-web_1  |   pre_exec: <function PreExec.pre_exec at 0x7f23b7c83b80>
scout-web_1  |   pre_request: <function PreRequest.pre_request at 0x7f23b7c83ca0>
scout-web_1  |   post_request: <function PostRequest.post_request at 0x7f23b7c83d30>
scout-web_1  |   child_exit: <function ChildExit.child_exit at 0x7f23b7c83e50>
scout-web_1  |   worker_exit: <function WorkerExit.worker_exit at 0x7f23b7c83f70>
scout-web_1  |   nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f23b7c1a0d0>
scout-web_1  |   on_exit: <function OnExit.on_exit at 0x7f23b7c1a1f0>
scout-web_1  |   proxy_protocol: True
scout-web_1  |   proxy_allow_ips: ['127.0.0.1']
scout-web_1  |   keyfile: None
scout-web_1  |   certfile: None
scout-web_1  |   ssl_version: 2
scout-web_1  |   cert_reqs: 0
scout-web_1  |   ca_certs: None
scout-web_1  |   suppress_ragged_eofs: True
scout-web_1  |   do_handshake_on_connect: False
scout-web_1  |   ciphers: None
scout-web_1  |   raw_paste_global_conf: []
scout-web_1  |   strip_header_spaces: False
scout-web_1  | [2022-04-25 14:16:39 +0000] [7] [INFO] Starting gunicorn 20.1.0
scout-web_1  | [2022-04-25 14:16:39 +0000] [7] [DEBUG] Arbiter booted
scout-web_1  | [2022-04-25 14:16:39 +0000] [7] [INFO] Listening at: http://0.0.0.0:8000 (7)
scout-web_1  | [2022-04-25 14:16:39 +0000] [7] [INFO] Using worker: sync
scout-web_1  | [2022-04-25 14:16:39 +0000] [9] [INFO] Booting worker with pid: 9
scout-web_1  | [2022-04-25 14:16:39 +0000] [7] [DEBUG] 1 workers
scout-web_1  | [2022-04-25 14:16:42 +0000] [9] [ERROR] Exception in worker process
scout-web_1  | Traceback (most recent call last):
scout-web_1  |   File "/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
scout-web_1  |     worker.init_process()
scout-web_1  |   File "/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
scout-web_1  |     self.load_wsgi()
scout-web_1  |   File "/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
scout-web_1  |     self.wsgi = self.app.wsgi()
scout-web_1  |   File "/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
scout-web_1  |     self.callable = self.load()
scout-web_1  |   File "/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
scout-web_1  |     return self.load_wsgiapp()
scout-web_1  |   File "/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
scout-web_1  |     return util.import_app(self.app_uri)
scout-web_1  |   File "/venv/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
scout-web_1  |     mod = importlib.import_module(module)
scout-web_1  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
scout-web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
scout-web_1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
scout-web_1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
scout-web_1  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
scout-web_1  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
scout-web_1  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
scout-web_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
scout-web_1  |   File "/home/worker/app/scout/server/auto.py", line 4, in <module>
scout-web_1  |     from .app import create_app
scout-web_1  |   File "/home/worker/app/scout/server/app.py", line 39, in <module>
scout-web_1  |     from chanjo_report.server.app import configure_template_filters
scout-web_1  |   File "/venv/lib/python3.8/site-packages/chanjo_report/server/app.py", line 5, in <module>
scout-web_1  |     from .config import DefaultConfig
scout-web_1  |   File "/venv/lib/python3.8/site-packages/chanjo_report/server/config.py", line 2, in <module>
scout-web_1  |     from .blueprints import report_bp, index_bp
scout-web_1  |   File "/venv/lib/python3.8/site-packages/chanjo_report/server/blueprints/__init__.py", line 2, in <module>
scout-web_1  |     from .index import index_bp
scout-web_1  |   File "/venv/lib/python3.8/site-packages/chanjo_report/server/blueprints/index/__init__.py", line 2, in <module>
scout-web_1  |     from .views import index_bp
scout-web_1  |   File "/venv/lib/python3.8/site-packages/chanjo_report/server/blueprints/index/views.py", line 7, in <module>
scout-web_1  |     from chanjo_report.server.extensions import api
scout-web_1  |   File "/venv/lib/python3.8/site-packages/chanjo_report/server/extensions.py", line 8, in <module>
scout-web_1  |     api = Alchy(Model=BASE)
scout-web_1  |   File "/venv/lib/python3.8/site-packages/flask_alchy.py", line 28, in __init__
scout-web_1  |     super(Alchy, self).__init__(
scout-web_1  |   File "/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 738, in __init__
scout-web_1  |     session_options.setdefault('scopefunc', connection_stack.__ident_func__)
scout-web_1  | AttributeError: 'LocalStack' object has no attribute '__ident_func__'
scout-web_1  | [2022-04-25 14:16:42 +0000] [9] [INFO] Worker exiting (pid: 9)
scout-web_1  | [2022-04-25 14:16:42 +0000] [7] [INFO] Shutting down: Master
scout-web_1  | [2022-04-25 14:16:42 +0000] [7] [INFO] Reason: Worker failed to boot.
scout_scout-web_1 exited with code 3
scout-cli    | Traceback (most recent call last):
scout-cli    |   File "/venv/bin/scout", line 33, in <module>
scout-cli    |     sys.exit(load_entry_point('scout-browser', 'console_scripts', 'scout')())
scout-cli    |   File "/venv/bin/scout", line 25, in importlib_load_entry_point
scout-cli    |     return next(matches).load()
scout-cli    |   File "/usr/local/lib/python3.8/importlib/metadata.py", line 77, in load
scout-cli    |     module = import_module(match.group('module'))
scout-cli    |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
scout-cli    |     return _bootstrap._gcd_import(name[level:], package, level)
scout-cli    |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
scout-cli    |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
scout-cli    |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
scout-cli    |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
scout-cli    |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
scout-cli    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
scout-cli    |   File "/home/worker/app/scout/commands/__init__.py", line 1, in <module>
scout-cli    |     from .base import cli
scout-cli    |   File "/home/worker/app/scout/commands/base.py", line 25, in <module>
scout-cli    |     from scout.server.app import create_app
scout-cli    |   File "/home/worker/app/scout/server/app.py", line 39, in <module>
scout-cli    |     from chanjo_report.server.app import configure_template_filters
scout-cli    |   File "/venv/lib/python3.8/site-packages/chanjo_report/server/app.py", line 5, in <module>
scout-cli    |     from .config import DefaultConfig
scout-cli    |   File "/venv/lib/python3.8/site-packages/chanjo_report/server/config.py", line 2, in <module>
scout-cli    |     from .blueprints import report_bp, index_bp
scout-cli    |   File "/venv/lib/python3.8/site-packages/chanjo_report/server/blueprints/__init__.py", line 2, in <module>
scout-cli    |     from .index import index_bp
scout-cli    |   File "/venv/lib/python3.8/site-packages/chanjo_report/server/blueprints/index/__init__.py", line 2, in <module>
scout-cli    |     from .views import index_bp
scout-cli    |   File "/venv/lib/python3.8/site-packages/chanjo_report/server/blueprints/index/views.py", line 7, in <module>
scout-cli    |     from chanjo_report.server.extensions import api
scout-cli    |   File "/venv/lib/python3.8/site-packages/chanjo_report/server/extensions.py", line 8, in <module>
scout-cli    |     api = Alchy(Model=BASE)
scout-cli    |   File "/venv/lib/python3.8/site-packages/flask_alchy.py", line 28, in __init__
scout-cli    |     super(Alchy, self).__init__(
scout-cli    |   File "/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 738, in __init__
scout-cli    |     session_options.setdefault('scopefunc', connection_stack.__ident_func__)
scout-cli    | AttributeError: 'LocalStack' object has no attribute '__ident_func__'
scout-cli exited with code 1
```

**Comment by dnil** [comment]
Fixed in https://github.com/Clinical-Genomics/chanjo-report/pull/32 - tested ok on stage after rebuilding a scout PR branch:
```
81566520d870  docker.io/clinicalgenomics/scout-server-stage:panels_alpha      /bin/sh -c gunico...  2 seconds ago   Up 2 seconds ago   0.0.0.0:7073->8000/tcp  scout-panels_alpha
```

**Comment by dnil** [comment]
Well done @northwestwitch; closing this!
