### ISSUE TITLE
Case search bug

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3354]
```
2022-05-24 09:42:39,492 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /cust004/cases [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/worker/app/scout/server/utils.py", line 85, in decorated_function
    context = func(*args, **kwargs)
  File "/home/worker/app/scout/server/blueprints/institutes/views.py", line 55, in cases
    return controllers.cases(store, request, institute_id)
  File "/home/worker/app/scout/server/blueprints/institutes/controllers.py", line 333, in cases
    for nr_cases, case_obj in enumerate(all_cases.limit(limit), 1):
  File "/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "/venv/lib/python3.8/site-packages/pymongo/server.py", line 130, in run_operation
    _check_command_response(first, sock_info.max_wire_version)
  File "/venv/lib/python3.8/site-packages/pymongo/helpers.py", line 167, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Regular expression is invalid: nothing to repeat, full error: {'operationTime': Timestamp(1653378155, 1), 'ok': 0.0, 'errmsg': 'Regular expression is invalid: nothing to repeat', 'code': 51091, 'codeName': 'Location51091', '$clusterTime': {'clusterTime': Timestamp(1653378155, 1), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'keyId': 0}}}
```

**Comment by northwestwitch** [comment]
This is caused when you type special chars in the case search:

For instance:

<img width="329" alt="image" src="https://user-images.githubusercontent.com/28093618/169989400-1397b18c-13bf-4f0e-b4fc-3b6c6ef902f7.png">

**Comment by dnil** [comment]
Oooh, that sounds like fun! Any nice evil tricks one can do? 😁

**Comment by northwestwitch** [comment]
It was probably a typo of sime user looking for a case, but it shouldn't crash. I've opened a PR to fix it
