### ISSUE TITLE
None gene_caption is not subscriptable (bug in gene variants)

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3358]
2022-05-25 14:00:18,885 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /cust003/gene_variants [POST] [in /venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/worker/app/scout/server/utils.py", line 85, in decorated_function
    context = func(*args, **kwargs)
  File "/home/worker/app/scout/server/blueprints/institutes/views.py", line 137, in gene_variants
    data = controllers.gene_variants(store, variants_query, result_size, page)
  File "/home/worker/app/scout/server/blueprints/institutes/controllers.py", line 471, in gene_variants
    gene_symbols = [gene_caption["hgnc_symbol"]]
TypeError: 'NoneType' object is not subscriptable

**Comment by northwestwitch** [comment]
This needs an urgent fix. I could branch out from the current release branch and create a quick patch perhaps? I'll do that!

**Comment by northwestwitch** [comment]
I don't think this a super urgent fix after all. Let's include it in the next release instead of creating a patch version
