### ISSUE TITLE
Problem creating a PDF report

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3362]
```
2022-05-30 10:56:03,951 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /cust000/SWEDAC-2019-HG-05-Trio-NovaSeq/pdf_report [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1455]


Traceback (most recent call last):
  File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 1693, in feed
    self.parser.Parse(data, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/worker/app/scout/server/blueprints/cases/views.py", line 231, in pdf_case_report
    svg2png(
  File "/venv/lib/python3.8/site-packages/cairosvg/__init__.py", line 55, in svg2png
    return surface.PNGSurface.convert(
  File "/venv/lib/python3.8/site-packages/cairosvg/surface.py", line 127, in convert
    tree = Tree(
  File "/venv/lib/python3.8/site-packages/cairosvg/parser.py", line 390, in __init__
    tree = ElementTree.fromstring(
  File "/venv/lib/python3.8/site-packages/defusedxml/common.py", line 126, in fromstring
    parser.feed(text)
  File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 1695, in feed
    self._raiseerror(v)
  File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 1602, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
```

**Comment by northwestwitch** [comment]
Can be tested also on stage with this case: https://scout-stage.scilifelab.se/cust000/SWEDAC-2019-HG-05-Trio-NovaSeq

**Comment by northwestwitch** [comment]
I'm starting to suspect that it's the cases missing a madeline picture, where instead it is found a string like this: 

<img width="528" alt="image" src="https://user-images.githubusercontent.com/28093618/170976969-51eeed70-707d-46c7-b3c5-e188e4592715.png">

I think PDFKit tries to read data from the path to the xml file displayed in the report 😐 

:neutral_face:
--


<br class="Apple-interchange-newline">
