### ISSUE TITLE
Sanger order error

### ISSUE THREAD

**Issue by sofievonlanthen** [Clinical-Genomics/scout#3376]
Ordering Sanger using the Sanger order button on the variant page results in error. The "verification ordered" shows up on the summary page, but no email was sent and a error page comes up.

**Comment by dnil** [comment]
It boils down to a new-ish issue with authentication on the smtp server. Perhaps our posting account simply changed their password? @patrikgrenfeldt @Mropat 
```
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]: 2022-06-02 17:56:37 6ff45033f262 scout.server.app[7] ERROR Exception on /cust087/F0046103/a638295cab1697cc7ca88050429fa704/True [POST]
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]: Traceback (most recent call last):
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:   File "/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:     response = self.full_dispatch_request()
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:   File "/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:     rv = self.handle_user_exception(e)
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:   File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:   File "/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:     rv = self.dispatch_request()
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:   File "/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:   File "/home/worker/app/scout/server/blueprints/variant/views.py", line 327, in verify
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:     variant_verification(
Jun 02 17:56:37 cg-vm1.scilifelab.se conmon[3145470]:   File "/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:   File "/home/worker/app/scout/server/blueprints/variant/verification_controllers.py", line 222, in variant_verification
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:     mail.send(message)
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:   File "/venv/lib/python3.8/site-packages/flask_mail.py", line 491, in send
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:     with self.connect() as connection:
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:   File "/venv/lib/python3.8/site-packages/flask_mail.py", line 144, in __enter__
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:     self.host = self.configure_host()
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:   File "/venv/lib/python3.8/site-packages/flask_mail.py", line 165, in configure_host
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:     host.login(self.mail.username, self.mail.password)
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:   File "/usr/local/lib/python3.8/smtplib.py", line 748, in login
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:     raise last_exception
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:   File "/usr/local/lib/python3.8/smtplib.py", line 737, in login
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:     (code, resp) = self.auth(
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:   File "/usr/local/lib/python3.8/smtplib.py", line 660, in auth
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:     raise SMTPAuthenticationError(code, resp)
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]: smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials h17-20020a056512221100b0047255d21151sm1089949lfu.128 - gsmtp')
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]: : None,
Jun 02 17:56:37 cg-vm1.scilifelab.se podman[3145413]:             
```

**Comment by dnil** [comment]
Ok, the login method we apparently used for sending emails is now closed by google since a few days.
<img width="824" alt="Screenshot 2022-06-03 at 09 23 12" src="https://user-images.githubusercontent.com/758570/171807842-79f90a9d-e8c5-42b7-ac3f-7842369024a6.png">
We'll find an alternative!

**Comment by dnil** [comment]
Ok, try now @sofievonlanthen. It is now possible to send Sanger verification email on my end again: just reopen if its not working for you! Thanks for reporting!
