### ISSUE TITLE
Regular expression is invalid: \  in cases search

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3407]
A current bug in prod. Apparently #3356 didn't fix all these cases?

```
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/worker/app/scout/server/utils.py", line 85, in decorated_function
    context = func(*args, **kwargs)
  File "/home/worker/app/scout/server/blueprints/institutes/views.py", line 59, in cases
    return controllers.cases(store, request, institute_id)
  File "/home/worker/app/scout/server/blueprints/institutes/controllers.py", line 328, in cases
    all_cases = store.cases(
  File "/home/worker/app/scout/adapter/mongo/case.py", line 352, in cases
    order = self._populate_name_query(query, name_query, owner, collaborator)
  File "/home/worker/app/scout/adapter/mongo/case.py", line 239, in _populate_name_query
    query["assignees"] = {"$in": [user["email"] for user in users]}
  File "/home/worker/app/scout/adapter/mongo/case.py", line 239, in <listcomp>
    query["assignees"] = {"$in": [user["email"] for user in users]}
  File "/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "/venv/lib/python3.8/site-packages/pymongo/server.py", line 130, in run_operation
    _check_command_response(first, sock_info.max_wire_version)
  File "/venv/lib/python3.8/site-packages/pymongo/helpers.py", line 167, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Regular expression is invalid: \ at end of pattern, full error: {'operationTime': Timestamp(1655129981, 3), 'ok': 0.0, 'errmsg': 'Regular expression is invalid: \\ at end of pattern', 'code': 51091, 'codeName': 'Location51091', '$clusterTime': {'clusterTime': Timestamp(1655129981, 3), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'keyId': 0}}}
```

**Comment by northwestwitch** [comment]
> Or perhaps this one appeared fresh with it? That seems like a common escape character.

Possibly. Tried to trigger the same problem locally or on stage but couldn't. Who knows what they were typing!

**Comment by dnil** [comment]
Yeah, that was not simple - wonder who it was.. But Searching for `\ ` - dont miss the space - reproduces it! 😸

**Comment by northwestwitch** [comment]
I don't think this is very high and perhaps we don't have to include a fix in the new release.. What do you say @dnil ?

**Comment by dnil** [comment]
No, does not seem pressing; let's keep it on the list to fix for later. A mistake in handling escaping may in turn be a security issue.

**Comment by northwestwitch** [comment]
Perhaps let's include a fix also for this one in today's release? I see it recurring under the last few days!

**Comment by dnil** [comment]
I wonder who and why, but yes, good!
