### ISSUE TITLE
Update HPO command crashes

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3430]
After the latest HPO release, when you run `scout update hpo` you get the following error:

```
2022-06-15 11:26:03 ChiaraRMBP.local scout.build.hpo[56137] DEBUG Building hpo term HP:5000047
2022-06-15 11:26:03 ChiaraRMBP.local scout.build.hpo[56137] DEBUG Building hpo term part_of

Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/py38/bin/scout", line 33, in <module>
    sys.exit(load_entry_point('scout-browser', 'console_scripts', 'scout')())
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/cli.py", line 579, in main
    return super().main(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/cli.py", line 427, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/commands/update/hpo.py", line 54, in hpo
    load_hpo_terms(adapter, hpo_lines=hpoterms, hpo_gene_lines=hpo_to_genes)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/load/hpo.py", line 116, in load_hpo_terms
    hpo_bulk.append(build_hpo_term(hpo_info))
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/build/hpo.py", line 35, in build_hpo_term
    hpo_obj = HpoTerm(
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/models/phenotype_term.py", line 30, in __init__
    self["hpo_number"] = int(hpo_id.split(":")[-1])
ValueError: invalid literal for int() with base 10: 'part_of'
(py38) chiararasi@ChiaraRMBP:~/Documents/work/GITs/scout$
```

Thanks again @leahkemp for reporting the error! I'll look into it!

**Comment by leahkemp** [comment]
No problem, thanks for the speedy fix! It's working for me now :)
