### ISSUE TITLE
Error while updating gene panel

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3473]
```
2022-06-23 15:27:07,839 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /panels [POST] [in /venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/worker/app/scout/server/utils.py", line 85, in decorated_function
    context = func(*args, **kwargs)
  File "/home/worker/app/scout/server/blueprints/panels/views.py", line 41, in panels
    redirect_panel_id = controllers.panel_create_or_update(store, request)
  File "/home/worker/app/scout/server/blueprints/panels/controllers.py", line 132, in panel_create_or_update
    redirect_id = update_existing_panel(store, request, lines)
  File "/home/worker/app/scout/server/blueprints/panels/controllers.py", line 108, in update_existing_panel
    return panel_obj.get("_id")
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by northwestwitch** [comment]
Duplicate, closing this issue!
