### ISSUE TITLE
gene_caption["hgnc_symbol"] causes page to crash on gene variants page

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3524]
```
022-08-12 10:42:18,061 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /cust064/gene_variants [POST] [in /venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/worker/app/scout/server/utils.py", line 85, in decorated_function
    context = func(*args, **kwargs)
  File "/home/worker/app/scout/server/blueprints/institutes/views.py", line 149, in gene_variants
    data = controllers.gene_variants(store, variants_query, result_size, page)
  File "/home/worker/app/scout/server/blueprints/institutes/controllers.py", line 550, in gene_variants
    gene_symbols = [gene_caption["hgnc_symbol"]]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by northwestwitch** [comment]
I've realized this is a bug we saw before. This is the fix I've already written: #3359

I'll try to understand how to reproduce the bug, so we can test the fix on stage!
