### ISSUE TITLE
"regular expression is invalid: \\ at end of pattern" error still not fixed. 

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3571]
```
2022-09-06 18:46:23,386 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /cust003/cases [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/worker/app/scout/server/utils.py", line 85, in decorated_function
    context = func(*args, **kwargs)
  File "/home/worker/app/scout/server/blueprints/institutes/views.py", line 76, in cases
    return controllers.cases(store, request, institute_id)
  File "/home/worker/app/scout/server/blueprints/institutes/controllers.py", line 399, in cases
    all_cases = store.cases(
  File "/home/worker/app/scout/adapter/mongo/case.py", line 346, in cases
    order = self._populate_name_query(query, name_query, owner, collaborator)
  File "/home/worker/app/scout/adapter/mongo/case.py", line 235, in _populate_name_query
    query["assignees"] = {"$in": [user["email"] for user in users]}
  File "/home/worker/app/scout/adapter/mongo/case.py", line 235, in <listcomp>
    query["assignees"] = {"$in": [user["email"] for user in users]}
  File "/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "/venv/lib/python3.8/site-packages/pymongo/server.py", line 130, in run_operation
    _check_command_response(first, sock_info.max_wire_version)
  File "/venv/lib/python3.8/site-packages/pymongo/helpers.py", line 167, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Regular expression is invalid: \ at end of pattern, full error: {'operationTime': Timestamp(1662482778, 1), 'ok': 0.0, 'errmsg': 'Regular expression is invalid: \\ at end of pattern', 'code': 51091, 'codeName': 'Location51091', '$clusterTime': {'clusterTime': Timestamp(1662482778, 1), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'keyId': 0}}}
```

Perhaps we should introduce a debug message to try to understand what they are typing, to reproduce the error?

**Comment by dnil** [comment]
Hm, isn't it more that we re-introduced it when removing all the escapes? We could also probably fix it by adding the right ones back carefully. 😊

**Comment by northwestwitch** [comment]
I haven't seen this thing in a very long time. Let's close the issue!

**Comment by dnil** [comment]
😆 Someone beat me to checking that it it still was there it seems..
```
2023-02-07 15:41:38,651 - scout.server.app - ERROR: Exception on /cust109/cases [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
   response = self.full_dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
   rv = self.dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
 File "/home/worker/app/scout/server/utils.py", line 85, in decorated_function
   context = func(*args, **kwargs)
 File "/home/worker/app/scout/server/blueprints/institutes/views.py", line 66, in cases
   return controllers.cases(store, request, institute_id)
 File "/home/worker/app/scout/server/blueprints/institutes/controllers.py", line 411, in cases
   all_cases = store.cases(
 File "/home/worker/app/scout/adapter/mongo/case.py", line 411, in cases
   order = self._populate_name_query(query, name_query, owner, collaborator)
 File "/home/worker/app/scout/adapter/mongo/case.py", line 235, in _populate_name_query
   query["assignees"] = {"$in": [user["email"] for user in users]}
 File "/home/worker/app/scout/adapter/mongo/case.py", line 235, in <listcomp>
   query["assignees"] = {"$in": [user["email"] for user in users]}
 File "/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1280, in next
   if len(self.__data) or self._refresh():
 File "/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1195, in _refresh
   self.__send_message(q)
 File "/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1078, in __send_message
   response = client._run_operation(
 File "/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1515, in _run_operation
   return self._retryable_read(
 File "/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1617, in _retryable_read
   return func(session, server, sock_info, secondary_ok)
 File "/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1511, in _cmd
   return server.run_operation(
 File "/venv/lib/python3.8/site-packages/pymongo/server.py", line 133, in run_operation
   _check_command_response(first, sock_info.max_wire_version)
 File "/venv/lib/python3.8/site-packages/pymongo/helpers.py", line 180, in _check_command_response
   raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Regular expression is invalid: \ at end of pattern, full error: {'operationTime': Timestamp(1675780897, 4), 'ok': 0.0, 'errmsg': 'Regular expression is invalid: \\ at end of pattern', 'code': 51091, 'codeName': 'Location51091', '$clusterTime': {'clusterTime': Timestamp(1675780897, 4), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'keyId': 0}}}
```

**Comment by northwestwitch** [comment]
Yes, last famous words! 😆
