### ISSUE TITLE
'str' object has no attribute 'bai'

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3708]
2022-12-08 16:27:33,705 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /cust000/SWEDAC-2019-HG-05-Trio-NovaSeq/str/variant/d9af6eeae76f8394a39ce098b40be430 [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/worker/app/scout/server/utils.py", line 85, in decorated_function
    context = func(*args, **kwargs)
  File "/home/worker/app/scout/server/blueprints/variant/views.py", line 117, in reviewer_aln
    data = str_variant_reviewer(store, case_obj, variant_id)
  File "/home/worker/app/scout/server/blueprints/variant/controllers.py", line 586, in str_variant_reviewer
    if os.path.exists(ind_reviewer.get("alignment").bai)
AttributeError: 'str' object has no attribute 'bai'2022-12-08 16:27:33,705 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /cust000/SWEDAC-2019-HG-05-Trio-NovaSeq/str/variant/d9af6eeae76f8394a39ce098b40be430 [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/worker/app/scout/server/utils.py", line 85, in decorated_function
    context = func(*args, **kwargs)
  File "/home/worker/app/scout/server/blueprints/variant/views.py", line 117, in reviewer_aln
    data = str_variant_reviewer(store, case_obj, variant_id)
  File "/home/worker/app/scout/server/blueprints/variant/controllers.py", line 586, in str_variant_reviewer
    if os.path.exists(ind_reviewer.get("alignment").bai)
AttributeError: 'str' object has no attribute 'bai'

**Comment by dnil** [comment]
Yup, just testing - but it is indeed a "bug", in the PR still. Fixing now.
