### ISSUE TITLE
Bug on STR page with MIP 11.1 (stage)

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3712]
2022-12-12 13:38:06,994 - scout.server.app - ERROR: Exception on /cust002/F0013103/str/variants [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
   response = self.full_dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
   rv = self.dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
 File "/home/worker/app/scout/server/utils.py", line 85, in decorated_function
   context = func(*args, **kwargs)
 File "/home/worker/app/scout/server/blueprints/variants/views.py", line 217, in str_variants
   data = controllers.str_variants(
 File "/home/worker/app/scout/server/blueprints/variants/controllers.py", line 218, in str_variants
   variants(
 File "/home/worker/app/scout/server/blueprints/variants/controllers.py", line 124, in variants
   parse_variant(
 File "/home/worker/app/scout/server/blueprints/variants/controllers.py", line 815, in parse_variant
   variant_obj["str_source_link"] = str_source_link(variant_obj)
 File "/home/worker/app/scout/server/links.py", line 470, in str_source_link
   return url_template.format(source["id"])
UnboundLocalError: local variable 'url_template' referenced before assignment

**Comment by dnil** [comment]
The reason was presumably the "expert" source annotation for POLG, which was not found a valid source by Scout. It kind of makes sense to just accept the type as given and do the best we can with it.
