### ISSUE TITLE
Import phenopacket can crash - on empty json responses?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3734]
```
2022-12-20 15:20:00,503 - scout.server.app - ERROR: Exception on /cust002/F0007523/phenotype_import [POST] [in /venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
   response = self.full_dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
   rv = self.dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
 File "/home/worker/app/scout/server/blueprints/cases/views.py", line 409, in phenotype_import
   phenopacket = phenopacketapi.get_hash(phenopacket_hash)
 File "/home/worker/app/scout/server/extensions/phenopacket_extension.py", line 109, in get_hash
   json_content = json_response.get("content")[0]
TypeError: 'NoneType' object is not subscriptable
```
after doing:
![Screenshot 2022-12-20 at 15 21 02](https://user-images.githubusercontent.com/758570/208688783-d74dd71e-c41b-476b-8312-b21a9b9dcd94.png)
At less prio, the button there should not be labeled "Upload", not to confuse it with the first (file upload) alternative. Perhaps "Retrieve", "Fetch" or the like.

**Comment by northwestwitch** [comment]
This could be a result of me changing the scout_response thing?

**Comment by dnil** [comment]
Possibly; it is using it. Or maybe just some mistake in the last fix to the Phenopackets PR for adding non-id-matching to the case level. 😊

**Comment by northwestwitch** [comment]
While trying to fix this I found another error:

```
2022-12-21 07:06:45 ChiaraRMBP.local scout.server.app[41007] ERROR Exception on /cust000/643594/phenotype_import [POST]
Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/blueprints/cases/views.py", line 412, in phenotype_import
    store, institute_obj, case_obj, user_obj, case_url, phenopacket
UnboundLocalError: local variable 'phenopacket' referenced before assignment
2022-12-21 07:06:45 ChiaraRMBP.local werkzeug[41007] INFO 127.0.0.1 - - [21/Dec/2022 07:06:45] "POST /cust000/643594/phenotype_import HTTP/1.1" 500 -
^C(py38) chiararasi@ChiaraRMBP:~/Documents/work/GITs/scout$
```

Triggered when you click on any of the 2 Upload buttons if you don't provide an uploaded file:

<img width="520" alt="image" src="https://user-images.githubusercontent.com/28093618/208834333-2f55d9f6-d64e-48ef-86bc-6e92f2f92fc4.png">
