### ISSUE TITLE
too many values to unpack in add_case_group

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3745]
2023-01-02 14:54:50,852 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /cust087/unused/add_case_group [POST] [in /venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/worker/app/scout/server/blueprints/cases/views.py", line 880, in add_case_group
    controllers.add_case_group(store, current_user, institute_id, case_name, group_id)
  File "/home/worker/app/scout/server/blueprints/cases/controllers.py", line 923, in add_case_group
    institute_obj, case_obj = institute_and_case(store, institute_id, case_name)
ValueError: too many values to unpack (expected 2)

**Comment by northwestwitch** [comment]
Reproduced locally by trying to add a case to a group, from a cancer case page
