### ISSUE TITLE
ClinVar index save?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3785]
2023-01-31 15:54:25,227 - scout.server.app - ERROR: Exception on /cust002/F0042632/clinvar/save [POST] [in /venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
   response = self.full_dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
   rv = self.dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
 File "/home/worker/app/scout/server/blueprints/clinvar/views.py", line 36, in clinvar_save
   variant_data = controllers.parse_variant_form_fields(request.form)  # dictionary
 File "/home/worker/app/scout/server/blueprints/clinvar/controllers.py", line 248, in parse_variant_form_fields
   _parse_tx_hgvs(clinvar_var, form)
 File "/home/worker/app/scout/server/blueprints/clinvar/controllers.py", line 216, in _parse_tx_hgvs
   clinvar_var["hgvs"] = tx_hgvs.split(":")[1]
IndexError: list index out of range

**Comment by northwestwitch** [comment]
Oh no, a bug. Thankfully before the new release! 🙏🏻
