### ISSUE TITLE
Validating an empty ClinVar submission is crashing the page

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3798]
Given an empty submission like this

<img width="968" alt="image" src="https://user-images.githubusercontent.com/28093618/216571793-1e9ca06a-1445-4313-8630-a73cf20916ea.png">

When you click on Validate:

```
2023-02-03 11:02:05,648 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /638d9b523d6fb365a47d6285/y/validate [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/worker/app/scout/server/blueprints/clinvar/views.py", line 89, in clinvar_validate
    clinvar_id = controllers.validate_submission(submission)
  File "/home/worker/app/scout/server/blueprints/clinvar/controllers.py", line 405, in validate_submission
    code, conversion_res = json_api_submission(submission_id)
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by northwestwitch** [comment]
It crashes also if one of the 2 files is present (ie Variant) and the other (Casedata) is missing
