### ISSUE TITLE
Mitodel problem when loading a case

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3800]
Call ['/home/proj/production/bin/miniconda3/envs/P_scout/bin/scout', '--config', '/home/proj/production/servers/config/hasta.scilifelab.se/scout.yaml', 'load', 'case', '/home/proj/production/housekeeper-bundles/caringcrab/2023-02-01/scout_load.yaml'] exit with a non zero exit code
2023-02-06 13:54:42 [hasta.scilifelab.se](http://hasta.scilifelab.se/) scout.commands.base[93199] INFO Running scout version 4.63
2023-02-06 13:54:42 [hasta.scilifelab.se](http://hasta.scilifelab.se/) scout.commands.base[93199] DEBUG Debug logging enabled.
2023-02-06 13:54:42 [hasta.scilifelab.se](http://hasta.scilifelab.se/) scout.commands.base[93199] WARNING Support for launching Scout using a .yaml config file is deprecated and will be removed in the next major release (5.0). Use a PYTHON (.py) config file instead.
2023-02-06 13:54:42 [hasta.scilifelab.se](http://hasta.scilifelab.se/) scout.adapter.client[93199] INFO Connected to MongoDB 4.4.9
2023-02-06 13:54:42 [hasta.scilifelab.se](http://hasta.scilifelab.se/) scout.adapter.mongo.base[93199] DEBUG Database name: scout
2023-02-06 13:54:42 [hasta.scilifelab.se](http://hasta.scilifelab.se/) scout.server.app[93199] INFO Enable Phenopacket API
2023-02-06 13:54:42 [hasta.scilifelab.se](http://hasta.scilifelab.se/) scout.parse.case[93199] INFO Adding SMN info from /home/proj/production/housekeeper-bundles/caringcrab/2023-02-01/caringcrab_smn.tsv.
2023-02-06 13:54:42 [hasta.scilifelab.se](http://hasta.scilifelab.se/) scout.parse.case[93199] INFO Adding mitosign info from /home/proj/production/housekeeper-bundles/caringcrab/2023-02-01/ACC11276A1_lanes_1234_sorted_md_mitodel.txt to ACC11276A1
Traceback (most recent call last):
 File "/home/proj/production/bin/miniconda3/envs/P_scout/bin/scout", line 8, in <module>
  sys.exit(cli())
 File "/home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
  return self.main(*args, **kwargs)
 File "/home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages/click/core.py", line 1055, in main
  rv = self.invoke(ctx)
 File "/home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
  return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
  return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
  return ctx.invoke(self.callback, **ctx.params)
 File "/home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages/click/core.py", line 760, in invoke
  return __callback(*args, **kwargs)
 File "/home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
  return f(get_current_context(), *args, **kwargs)
 File "/home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages/flask/cli.py", line 357, in decorator
  return __ctx.invoke(f, *args, **kwargs)
 File "/home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages/click/core.py", line 760, in invoke
  return __callback(*args, **kwargs)
 File "/home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages/scout/commands/load/case.py", line 93, in case
  peddy_check=peddy_check,
 File "/home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages/scout/parse/case.py", line 90, in parse_case_data
  add_mitodel_info(config_dict)
 File "/home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages/scout/parse/case.py", line 135, in add_mitodel_info
  individual["mitodel"] = parse_mitodel_file(file_handle)
 File "/home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages/scout/parse/mitodel.py", line 26, in parse_mitodel_file
  ind_mitodel_info = dict(zip(HEADER_ABBREV, contents.groups()))
AttributeError: 'NoneType' object has no attribute 'groups'
Traceback (most recent call last):
 File "/home/proj/production/bin/miniconda3/envs/P_main/bin/cg", line 8, in <module>
  sys.exit(base())
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
  return self.main(*args, **kwargs)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/core.py", line 697, in main
  rv = self.invoke(ctx)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
  return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
  return Command.invoke(self, ctx)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
  return ctx.invoke(self.callback, **ctx.params)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
  return callback(*args, **kwargs)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
  return f(get_current_context(), *args, **kwargs)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/cg/cli/upload/base.py", line 73, in upload
  upload_api.upload(ctx=context, case_obj=case_obj, restart=restart)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/cg/meta/upload/mip_dna/mip_dna.py", line 53, in upload
  ctx.invoke(scout, case_id=case_obj.internal_id, re_upload=restart)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
  return callback(*args, **kwargs)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
  return f(get_current_context(), *args, **kwargs)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/cg/cli/upload/scout.py", line 49, in scout
  context.invoke(upload_case_to_scout, case_id=case_id, re_upload=re_upload)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
  return callback(*args, **kwargs)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
  return f(get_current_context().obj, *args, **kwargs)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/cg/cli/upload/scout.py", line 146, in upload_case_to_scout
  scout_api.upload(scout_load_config=scout_config_file.full_path, force=re_upload)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/cg/apps/scout/scoutapi.py", line 48, in upload
  self.process.run_command(load_command)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/cg/utils/commands.py", line 108, in run_command
  raise CalledProcessError(res.returncode, command)
subprocess.CalledProcessError: Command '['/home/proj/production/bin/miniconda3/envs/P_scout/bin/scout', '--config', '/home/proj/production/servers/config/hasta.scilifelab.se/scout.yaml', 'load', 'case', '/home/proj/production/housekeeper-bundles/caringcrab/2023-02-01/scout_load.yaml']' returned non-zero exit status 1.

**Comment by northwestwitch** [comment]
Prod case `caringcrab`

**Comment by dnil** [comment]
```
intermediate discordant   normal  263369 ratio ppk 0
```
In a way its more of an issue for MIP / mitosign - seems there were perhaps no discordant reads at all, but it was output like `""` instead of 0? Or an error occurred?

We could be a bit more forthcoming with reporting errors in parsing from Scout though... 😊

**Comment by dnil** [comment]
If it was actually 0, we could just handle it as such - but let's check that first perhaps?

**Comment by dnil** [comment]
I can amend it to 0 for now if you like, and we investigate later?

**Comment by northwestwitch** [comment]
> I can amend it to 0 for now if you like, and we investigate later?

Sounds good. Shouldn't affect the analysis no?

**Comment by dnil** [comment]
Its an insanely low mito count anyway, so I kind of doubt this was a muscle sample to begin with.. :)

**Comment by dnil** [comment]
Done. Try again!

**Comment by dnil** [comment]
Once you see it loading ok, you could transfer this to MIP and we can look at it to make sure we always output a number there even if there were no discordant pairs - or fix whatever went wrong with the actual run.

**Comment by northwestwitch** [comment]
> Once you see it loading ok, you could transfer this to MIP and we can look at it to make sure we always output a number there even if there were no discordant pairs - or fix whatever went wrong with the actual run.

Will do, thanks!

**Comment by northwestwitch** [comment]
Case uploaded successfully, moving this issue to MIP!
