### ISSUE TITLE
Fix template autoreload 

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3961]
Some time ago when you used to change a template then the page was refreshed in real time without the need to relaunch the Flask app. Would be nice to restore this functionality, it's very useful especially during development

**Comment by northwestwitch** [comment]
Ok templates get reloaded if you run the scout instance with the following command:

`scout server --livereload (or -l)`

Because of the code here: https://github.com/Clinical-Genomics/scout/blob/166cc2a7413eb29c95270ac2a0db29d1a9f26f82/scout/commands/serve.py#L35

But since serving scout with the serve command shouldn't be used in production (where you want to start a WSGI server instead) what about having the livereload set as default when we use the serve command?

**Comment by dnil** [comment]
I don´t mind much either way: I basically never use the "serve" command for testing either - gunicorn is so much smoother - and it is documented, at least as an option. If you want to change it to default for serve, feel free, but it kind of works already.  😊 

For posteriority, gunicorn has a similar devel option: `--reload`: https://docs.gunicorn.org/en/stable/settings.html?highlight=reload#reload

**Comment by northwestwitch** [comment]
The serve command could also be removed since it is not meant for production and can be replaced by gunicorn, as you mentioned, but then it becomes a major :roll_eyes:

Let's leave it like this for now, I have the impression that perhaps it's just me. It's not a big effort to add a -l at the end.

**Comment by northwestwitch** [comment]
Wait a minute, if you run the demo with the scout serve and usethe --livereload option then it looks like it's working, but if you open the browser at` http://localhost:5000/` then it crashes!

```
(py38) chiararasi@ChiaraRaMBP scout % scout --demo serve --livereload
2023-05-30 15:01:45 ChiaraRaMBP.local scout.commands.base[82483] INFO Running scout version 4.66
2023-05-30 15:01:45 ChiaraRaMBP.local scout.commands.base[82483] DEBUG Debug logging enabled.
2023-05-30 15:01:45 ChiaraRaMBP.local scout.adapter.client[82483] INFO Connected to MongoDB 6.0.5
2023-05-30 15:01:45 ChiaraRaMBP.local scout.adapter.mongo.base[82483] DEBUG Database name: scout-demo
2023-05-30 15:01:45 ChiaraRaMBP.local scout.server.app[82483] INFO Enable Phenopacket API
[I 230530 15:01:45 server:335] Serving on http://localhost:5000
2023-05-30 15:01:45 ChiaraRaMBP.local livereload[82483] INFO Serving on http://localhost:5000
2023-05-30 15:01:45 ChiaraRaMBP.local asyncio[82483] DEBUG Using selector: KqueueSelector
[I 230530 15:01:45 handlers:58] Watch current working directory
2023-05-30 15:01:45 ChiaraRaMBP.local livereload[82483] INFO Watch current working directory
[I 230530 15:01:45 handlers:62] Start watching changes
2023-05-30 15:01:45 ChiaraRaMBP.local livereload[82483] INFO Start watching changes
[I 230530 15:01:45 handlers:64] Start detecting changes
2023-05-30 15:01:45 ChiaraRaMBP.local livereload[82483] INFO Start detecting changes
[E 230530 15:01:47 web:1854] Uncaught exception GET / (::1)
    HTTPServerRequest(protocol='http', host='localhost:5000', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/tornado/web.py", line 1746, in _execute
        result = self.prepare()
      File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/tornado/web.py", line 3112, in prepare
        self.fallback(self.request)
      File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/livereload/server.py", line 133, in __call__
        WSGIContainer.environ(request), start_response)
    TypeError: environ() missing 1 required positional argument: 'request'
2023-05-30 15:01:47 ChiaraRaMBP.local tornado.application[82483] ERROR Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/tornado/web.py", line 1746, in _execute
    result = self.prepare()
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/tornado/web.py", line 3112, in prepare
    self.fallback(self.request)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/livereload/server.py", line 133, in __call__
    WSGIContainer.environ(request), start_response)
TypeError: environ() missing 1 required positional argument: 'request'
[E 230530 15:01:47 web:2327] 500 GET / (::1) 6.57ms
2023-05-30 15:01:47 ChiaraRaMBP.local tornado.access[82483] ERROR 500 GET / (::1) 6.57ms
```

<img width="294" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/56dee405-9e70-43a1-b652-28ffc6dcb035">

**Comment by dnil** [comment]
Hm, what branch and page? My local works just fine with
```
(scout39n) ➜  scout git:(main) ✗ scout --demo serve --livereload
```
and clicking a few pages, although I must admit I dont use it often so there could be issues..

**Comment by dnil** [comment]
I'm on python 3.9 I guess, but...

**Comment by northwestwitch** [comment]
> I'm on python 3.9 I guess, but...

I can try with 3.9

**Comment by northwestwitch** [comment]
> I can try with 3.9

Nope, same error also with 3.9

**Comment by dnil** [comment]
My local scout 3.8 barfs on `ModuleNotFoundError: No module named 'importlib_resources'` and I dont particularly care to fight with that. 😄 But 3.9 is just fine. Hmm, I'm guessing some requirement version then?

**Comment by northwestwitch** [comment]
> I have `tornado==6.1`. You?

tornado==6.3.2

**Comment by dnil** [comment]
Yep, thats it.

```
(scout39n) ➜  scout git:(main) ✗ pip install -U tornado
Requirement already satisfied: tornado in /usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages (6.1)
Collecting tornado
  Downloading tornado-6.3.2-cp38-abi3-macosx_10_9_x86_64.whl (422 kB)
     |████████████████████████████████| 422 kB 20.6 MB/s
Installing collected packages: tornado
  Attempting uninstall: tornado
    Found existing installation: tornado 6.1
    Uninstalling tornado-6.1:
      Successfully uninstalled tornado-6.1
Successfully installed tornado-6.3.2
(scout39n) ➜  scout git:(main) ✗ scout --demo serve --livereload
2023-05-30 15:22:48 macbook-pro-3.gaia.sll.se scout.commands.base[68122] INFO Running scout version 4.67
2023-05-30 15:22:48 macbook-pro-3.gaia.sll.se scout.commands.base[68122] DEBUG Debug logging enabled.
2023-05-30 15:22:48 macbook-pro-3.gaia.sll.se scout.adapter.client[68122] INFO Connected to MongoDB 6.0.1
2023-05-30 15:22:48 macbook-pro-3.gaia.sll.se scout.adapter.mongo.base[68122] DEBUG Database name: scout-demo
2023-05-30 15:22:48 macbook-pro-3.gaia.sll.se scout.server.app[68122] INFO Enable Phenopacket API
[I 230530 15:22:48 server:335] Serving on http://localhost:5000
2023-05-30 15:22:48 macbook-pro-3.gaia.sll.se livereload[68122] INFO Serving on http://localhost:5000
2023-05-30 15:22:48 macbook-pro-3.gaia.sll.se asyncio[68122] DEBUG Using selector: KqueueSelector
[I 230530 15:22:48 handlers:58] Watch current working directory
2023-05-30 15:22:48 macbook-pro-3.gaia.sll.se livereload[68122] INFO Watch current working directory
[I 230530 15:22:48 handlers:62] Start watching changes
2023-05-30 15:22:48 macbook-pro-3.gaia.sll.se livereload[68122] INFO Start watching changes
[I 230530 15:22:48 handlers:64] Start detecting changes
2023-05-30 15:22:48 macbook-pro-3.gaia.sll.se livereload[68122] INFO Start detecting changes
[E 230530 15:22:54 web:1871] Uncaught exception GET /cust000/643594/4c7d5c70d955875504db72ef8e1abe77 (::1)
    HTTPServerRequest(protocol='http', host='localhost:5000', method='GET', uri='/cust000/643594/4c7d5c70d955875504db72ef8e1abe77', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/tornado/web.py", line 1763, in _execute
        result = self.prepare()
      File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/tornado/web.py", line 3138, in prepare
        self.fallback(self.request)
      File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/livereload/server.py", line 133, in __call__
        WSGIContainer.environ(request), start_response)
    TypeError: environ() missing 1 required positional argument: 'request'
2023-05-30 15:22:54 macbook-pro-3.gaia.sll.se tornado.application[68122] ERROR Uncaught exception GET /cust000/643594/4c7d5c70d955875504db72ef8e1abe77 (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='GET', uri='/cust000/643594/4c7d5c70d955875504db72ef8e1abe77', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/tornado/web.py", line 1763, in _execute
    result = self.prepare()
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/tornado/web.py", line 3138, in prepare
    self.fallback(self.request)
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/livereload/server.py", line 133, in __call__
    WSGIContainer.environ(request), start_response)
TypeError: environ() missing 1 required positional argument: 'request'
[E 230530 15:22:54 web:2344] 500 GET /cust000/643594/4c7d5c70d955875504db72ef8e1abe77 (::1) 9.81ms
2023-05-30 15:22:54 macbook-pro-3.gaia.sll.se tornado.access[68122] ERROR 500 GET /cust000/643594/4c7d5c70d955875504db72ef8e1abe77 (::1) 9.81ms
```

**Comment by northwestwitch** [comment]
> Methinks they are perhaps not fully implementing semantic versioning and had a breaking change between the minors?

I am reading the specs of the new versions but I haven't seen it so far, so yes, perhaps!

**Comment by dnil** [comment]
6.2 is still fine..

**Comment by dnil** [comment]
This: https://github.com/lepture/python-livereload/issues/270
