### ISSUE TITLE
load_mongo not working

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#40]
Trying to load case 1 on clinical-db. Getting error related to ODM.

I already fixed and issue with calling "split" on a list:

```python
-      ind['capture_kits'] = config_info.get('capture_kit', '').split(',')
+      ind['capture_kits'] = config_info.get('capture_kit', [])
```

```bash
[scout@clinical-db scout-new]$ vex scout-new scouttools load_mongo -u robin -p andeer -scout_config tests/for_clinical_db/1/scout_config_clinical.ini -vt clinical
```

```python
Traceback (most recent call last):
  File "/home/scout/.virtualenvs/scout-new/bin/scouttools", line 8, in <module>
    execfile(__file__)
  File "/home/scout/scoutApp/scout-new/scripts/scouttools", line 66, in <module>
    scouttools()
  File "/home/scout/.virtualenvs/scout-new/lib/python2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/home/scout/.virtualenvs/scout-new/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/home/scout/.virtualenvs/scout-new/lib/python2.7/site-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/scout/.virtualenvs/scout-new/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/scout/.virtualenvs/scout-new/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/scout/scoutApp/scout-new/scout/commands/load_mongo.py", line 150, in load_mongo
    verbose=verbose
  File "/home/scout/scoutApp/scout-new/scout/ext/backend/load_mongo.py", line 229, in load_mongo_db
    if case not in institute.cases:
  File "/home/scout/.virtualenvs/scout-new/lib/python2.7/site-packages/mongoengine/base/fields.py", line 208, in __get__
    name=self.name
  File "/home/scout/.virtualenvs/scout-new/lib/python2.7/site-packages/mongoengine/dereference.py", line 65, in __call__
    self.object_map = self._fetch_objects(doc_type=doc_type)
  File "/home/scout/.virtualenvs/scout-new/lib/python2.7/site-packages/mongoengine/dereference.py", line 131, in _fetch_objects
    doc = doc_type._from_son(ref)
  File "/home/scout/.virtualenvs/scout-new/lib/python2.7/site-packages/mongoengine/base/document.py", line 587, in _from_son
    raise InvalidDocumentError(msg)
mongoengine.errors.InvalidDocumentError: Invalid data to create a `Case` instance.
research_gene_lists - 'unicode' object has no attribute 'get'
```

**Comment by robinandeer** [comment]
This was resolved by deleting the cases before loading the new data. It was probably cased by changes in the ODM.
