### ISSUE TITLE
Error while running scout demo via docker-compose

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4025]
Could be due to to the fact that I'm running it using a Mac M2 chip? The Dockerfile seems to compile fine but the cli container gets this error:

```
scout-cli          | Traceback (most recent call last):
scout-cli          |   File "/venv/bin/scout", line 33, in <module>
scout-cli          |     sys.exit(load_entry_point('scout-browser', 'console_scripts', 'scout')())
scout-cli          |   File "/venv/bin/scout", line 25, in importlib_load_entry_point
scout-cli          |     return next(matches).load()
scout-cli          |   File "/usr/local/lib/python3.8/importlib/metadata.py", line 77, in load
scout-cli          |     module = import_module(match.group('module'))
scout-cli          |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
scout-cli          |     return _bootstrap._gcd_import(name[level:], package, level)
scout-cli          |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
scout-cli          |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
scout-cli          |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
scout-cli          |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
scout-cli          |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
scout-cli          |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
scout-cli          |   File "/home/worker/app/scout/commands/__init__.py", line 1, in <module>
scout-cli          |     from .base import cli
scout-cli          |   File "/home/worker/app/scout/commands/base.py", line 12, in <module>
scout-cli          |     from scout.commands.convert import convert
scout-cli          |   File "/home/worker/app/scout/commands/convert.py", line 8, in <module>
scout-cli          |     from scout.server.extensions import store
scout-cli          |   File "/home/worker/app/scout/server/extensions/__init__.py", line 3, in <module>
scout-cli          |     from authlib.integrations.flask_client import OAuth
scout-cli          |   File "/venv/lib/python3.8/site-packages/authlib/integrations/flask_client/__init__.py", line 2, in <module>
scout-cli          |     from .integration import FlaskIntegration, token_update
scout-cli          |   File "/venv/lib/python3.8/site-packages/authlib/integrations/flask_client/integration.py", line 3, in <module>
scout-cli          |     from ..base_client import FrameworkIntegration
scout-cli          |   File "/venv/lib/python3.8/site-packages/authlib/integrations/base_client/__init__.py", line 3, in <module>
scout-cli          |     from .sync_openid import OpenIDMixin
scout-cli          |   File "/venv/lib/python3.8/site-packages/authlib/integrations/base_client/sync_openid.py", line 1, in <module>
scout-cli          |     from authlib.jose import jwt, JsonWebToken, JsonWebKey
scout-cli          |   File "/venv/lib/python3.8/site-packages/authlib/jose/__init__.py", line 15, in <module>
scout-cli          |     from .rfc7518 import (
scout-cli          |   File "/venv/lib/python3.8/site-packages/authlib/jose/rfc7518/__init__.py", line 6, in <module>
scout-cli          |     from .jwe_encs import JWE_ENC_ALGORITHMS, CBCHS2EncAlgorithm
scout-cli          |   File "/venv/lib/python3.8/site-packages/authlib/jose/rfc7518/jwe_encs.py", line 16, in <module>
scout-cli          |     from cryptography.hazmat.primitives.padding import PKCS7
scout-cli          |   File "/venv/lib/python3.8/site-packages/cryptography/hazmat/primitives/padding.py", line 13, in <module>
scout-cli          |     from cryptography.hazmat.bindings._padding import lib
scout-cli          | ImportError: /venv/lib/python3.8/site-packages/cryptography/hazmat/bindings/_padding.abi3.so: cannot open shared object file: No such file or directory
```

**Comment by northwestwitch** [comment]
Yes, as I suspected it's related to the architecture. All good when running the command from my old computer (linux/amd64). Still, would be good to propose a solution in the howto, so those who get to try scout with an arm processor don't get stuck on the same issue

**Comment by northwestwitch** [comment]
Closing this issue
