### ISSUE TITLE
Error caused by term without description makes HPO terms update fail

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4030]
```
2023-08-09 09:57:18 n177-p182.local scout.build.hpo[9088] DEBUG Building hpo term HP:4000072
2023-08-09 09:57:18 n177-p182.local scout.build.hpo[9088] DEBUG Building hpo term HP:4000073
2023-08-09 09:57:18 n177-p182.local scout.build.hpo[9088] DEBUG Building hpo term HP:4000074
2023-08-09 09:57:18 n177-p182.local scout.build.hpo[9088] DEBUG Building hpo term HP:4000075
2023-08-09 09:57:18 n177-p182.local scout.build.hpo[9088] DEBUG Building hpo term HP:4000076
2023-08-09 09:57:18 n177-p182.local scout.build.hpo[9088] DEBUG Building hpo term HP:4000077
2023-08-09 09:57:18 n177-p182.local scout.build.hpo[9088] DEBUG Building hpo term HP:4000078
2023-08-09 09:57:18 n177-p182.local scout.build.hpo[9088] DEBUG Building hpo term HP:4000079
2023-08-09 09:57:18 n177-p182.local scout.build.hpo[9088] DEBUG Building hpo term HP:4000080

Traceback (most recent call last):
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/build/hpo.py", line 31, in build_hpo_term
    description = hpo_info["description"]
KeyError: 'description'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/py38/bin/scout", line 33, in <module>
    sys.exit(load_entry_point('scout-browser', 'console_scripts', 'scout')())
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/commands/update/hpo.py", line 53, in hpo
    load_hpo_terms(
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/load/hpo.py", line 127, in load_hpo_terms
    hpo_bulk.append(build_hpo_term(hpo_info))
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/build/hpo.py", line 33, in build_hpo_term
    raise KeyError("Hpo terms has to have a description")
KeyError: 'Hpo terms has to have a description'
```

**Comment by dnil** [comment]
Added a PR to HPO: https://github.com/obophenotype/human-phenotype-ontology/pull/10192

**Comment by dnil** [comment]
Ok, with #4332 we can close this - automated updates work fine again.
