### ISSUE TITLE
'dict object' has no attribute 'tumor' error in variant/variant_details.html"

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4052]
```
2023-08-23 13:07:30,987 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /cust002/F0047382-2023-15642-02-Balsamic/cancer/1189dd6a8f082e2c2f5779b500b4662a [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/worker/app/scout/server/utils.py", line 90, in decorated_function
    return render_template(template_name, **context)
  File "/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/venv/lib/python3.8/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/worker/app/scout/server/blueprints/variant/templates/variant/cancer-variant.html", line 281, in top-level template code
    {{ alignments(institute, case, variant, current_user, config, igv_tracks, splice_junctions_tracks) }}
  File "/home/worker/app/scout/server/templates/layout.html", line 1, in top-level template code
    {% extends "bootstrap_global.html" %}
  File "/home/worker/app/scout/server/templates/bootstrap_global.html", line 62, in top-level template code
    {% block body %}
  File "/home/worker/app/scout/server/templates/bootstrap_global.html", line 65, in block 'body'
    {% block content %}
  File "/home/worker/app/scout/server/templates/layout.html", line 93, in block 'content'
    {% block content_main %}{% endblock %}
  File "/home/worker/app/scout/server/blueprints/variant/templates/variant/cancer-variant.html", line 98, in block 'content_main'
    <div class="col-5">{{ gtcall_panel(variant) }}</div>
  File "/venv/lib/python3.8/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/home/worker/app/scout/server/blueprints/variant/templates/variant/variant_details.html", line 66, in template
    {% if sample.sample_id == variant.tumor.ind_id %}
  File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'tumor'
```

**Comment by northwestwitch** [comment]
UU it's a cancer case without a cancer sample!

**Comment by dnil** [comment]
And not one, a whole set of them! Hm, some balsamic or cg update? Or related to the UMI issue?

**Comment by dnil** [comment]
Ahh, perhaps overgrowth ones rather, like really just somatic not cancer! 😁

**Comment by northwestwitch** [comment]
At least we haven't already published the new release! :)

**Comment by dnil** [comment]
Looks like indeed inherited cancer, re-orders from what was initially MIP cases with Balsamic for singletons.

**Comment by northwestwitch** [comment]
No no, I'm working on the no crash but it's a weird one for sure
