### ISSUE TITLE
New HPO release v2023-09-01 

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4062]
Here is the link:https://github.com/obophenotype/human-phenotype-ontology/releases/tag/v2023-09-01

Let's aim to create a new release of Scout and upgrade both software and databases with week!

**Comment by northwestwitch** [comment]
I've tried to do a local update of the HPO terms from the latest release, but the #4030 bug is not yet fixed it seems. We have to modify the file manually before updating the database!


```
Traceback (most recent call last):
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/build/hpo.py", line 31, in build_hpo_term
    description = hpo_info["description"]
KeyError: 'description'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/py38/bin/scout", line 33, in <module>
    sys.exit(load_entry_point('scout-browser', 'console_scripts', 'scout')())
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/commands/update/hpo.py", line 50, in hpo
    load_hpo_terms(
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/load/hpo.py", line 134, in load_hpo_terms
    hpo_bulk.append(build_hpo_term(hpo_info))
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/build/hpo.py", line 33, in build_hpo_term
    raise KeyError("Hpo terms has to have a description")
KeyError: 'Hpo terms has to have a description'
(py38) chiararasi@n177-p182 scout %
```

**Comment by northwestwitch** [comment]
## Download files for updating:

`scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml download everything --api-key xxxxxxx`


<img width="956" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/9da41df4-61c1-49c8-8997-77c92db9ffd9">


## Update HPO terms - first fixed the error in hpo.obo as described [here](https://github.com/obophenotype/human-phenotype-ontology/issues/9953)

`scout  --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml  update hpo --hpoterms hpo.obo --hpo-to-genes phenotype_to_genes.txt`

<img width="748" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/bce5691e-08b5-4d1a-8c18-06890f4a8308">


## Updating OMIM diseases terms

`scout  --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml  update diseases -f .`

<img width="861" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/978de85f-0442-4684-89d7-cd3c864f3585">


## Updating genes

`scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml  update genes -f .`

<img width="903" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/099de3c1-51cc-4306-a34d-388dfb3def54">


## Update the OMIM-AUTO panel

`scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml  update omim --institute cust002 --genemap2 genemap2.txt --mim2genes mim2genes.txt`

<img width="1049" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/50beb1ab-c0c5-4c4c-90f7-6d558d42fdf8">


OMIM panels is saved with yesterday's date - but fine, I guess

## Update the PanelApp green genes panel

`scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml update panelapp-green -i cust002 --force`

<img width="974" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/76379173-f756-4f24-a196-dbe166b4d95a">

**Comment by northwestwitch** [comment]
Updating of prod DB

## Update HPO terms - first fixed the error in hpo.obo as described [here](https://github.com/obophenotype/human-phenotype-ontology/issues/9953)

`scout  update hpo --hpoterms hpo.obo --hpo-to-genes phenotype_to_genes.txt`

<img width="795" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/52f4e5a2-2e5f-42d9-95b4-988efd6bae03">


## Updating OMIM diseases terms

`scout  update diseases -f .`

<img width="865" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/e058988c-b8b5-4cca-bbf8-aa92a8aef4fe">


## Updating genes

`scout  update genes -f .`

<img width="937" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/54ff9e88-fc8b-4c13-b5a6-6588c67f5070">


## Update the OMIM-AUTO panel

`scout update omim --institute cust002 --genemap2 genemap2.txt --mim2genes mim2genes.txt`

<img width="1088" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/ce02d245-5ab8-414c-a073-184f97d81dfc">


## Update the PanelApp green genes panel

`scout update panelapp-green -i cust002 --force`

<img width="985" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/837b2792-d6e6-4c4b-9ef7-3d27d1373a40">
