### ISSUE TITLE
Issues downloading the hp.obo file

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4066]
I'm downloading all the files required for updating the database (so I can start testing on stage) but the hpo.obo file is not available it seems!

```
2023-09-05 08:51:56 hasta.scilifelab.se scout.utils.scout_requests[57839] ERROR socket timed out - URL https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/hp.obo
Traceback (most recent call last):
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/bin/scout", line 8, in <module>
    sys.exit(cli())
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/scout/commands/download/everything.py", line 35, in everything
    ctx.invoke(hpo, out_dir=out_dir)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/scout/commands/download/hpo.py", line 80, in hpo
    hpo_info = fetch_hpo_files(**kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/scout/utils/scout_requests.py", line 280, in fetch_hpo_files
    hpo_files["hpo_terms"] = fetch_hpo_terms()
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/scout/utils/scout_requests.py", line 198, in fetch_hpo_terms
    return fetch_resource(url)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/scout/utils/scout_requests.py", line 179, in fetch_resource
    content = response.text
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by dnil** [comment]
Weird; it worked yesterday when I tested for the PR?!

**Comment by northwestwitch** [comment]
Me too, it was working yesterday!

**Comment by northwestwitch** [comment]
Ah it works again now I think!

**Comment by dnil** [comment]
I concur - works both via browser and scout cli. Temporary GitHub outage perhaps?
