### ISSUE TITLE
Crash on parsing hpo terms in scout setup

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/scout#4084]
Hello dear developers,

I am working at setting up an instance of Scout on my local computer, following the instructions in the README. Getting the demo instance running went smoothly. But when attempting to initialize it with data using the `scout setup database` I ran into trouble.

The setup starts and successfully retrieves various data. (I had to retry a few times due to connection timeouts). After a few minutes, it crashes on the step "Parsing hpo terms".

Here is the error:

```
2023-09-20 09:17:14 RS30138821 scout.load.hpo[33776] INFO Parsing hpo terms
Traceback (most recent call last):
  File "/home/jakob/.local/bin/scout", line 33, in <module>
    sys.exit(load_entry_point('scout-browser', 'console_scripts', 'scout')())
  File "/home/jakob/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/jakob/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/jakob/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jakob/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jakob/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jakob/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/jakob/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jakob/.local/lib/python3.10/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/jakob/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/jakob/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jakob/src/scout/scout/commands/setup/setup_scout.py", line 182, in database
    setup_scout(
  File "/home/jakob/src/scout/scout/load/setup.py", line 180, in setup_scout
    load_hpo(
  File "/home/jakob/src/scout/scout/load/hpo.py", line 53, in load_hpo
    load_hpo_terms(adapter, hpo_lines, hpo_gene_lines, alias_genes)
  File "/home/jakob/src/scout/scout/load/hpo.py", line 93, in load_hpo_terms
    HpoTerm(**hpo_term)  # Validate basic term using pydantic
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for HpoTerm
description
  field required (type=value_error.missing)
```

I looked through the current issues and saw that you had been looking into updating HPO terms here #4030 , but as this still occurs in the most recent `main` version, I thought this might not be the exact same issue.

**Comment by northwestwitch** [comment]
Hello @Jakob37. Have you checked this other issue: #4030 ? There was an error (probably it's still not fixed) in the latest hpo.obo file. In order to fox it you need to edit this file as described in here: https://github.com/obophenotype/human-phenotype-ontology/issues/9953

I really hope they'll fix the HPO repo soon. let me know if this fix works for you!

**Comment by Jakob37** [comment]
> Hello @Jakob37. Have you checked this other issue: #4030 ? There was an error (probably it's still not fixed) in the latest hpo.obo file. In order to fix it you need to edit this file as described in here: [obophenotype/human-phenotype-ontology#9953](https://github.com/obophenotype/human-phenotype-ontology/issues/9953)
> 
> I really hope they'll fix the HPO repo soon. let me know if this fix works for you!

OK, thank you for letting me know! I'll test it, and let you know how it works out.

**Comment by Jakob37** [comment]
After doing the following steps the setup worked for me.

1. Retrieve the files locally `scout download hpo -o <cache dir>`
2. Update the `hpo.obo` file as mentioned by @northwestwitch (as outlined in https://github.com/obophenotype/human-phenotype-ontology/issues/9953)
3. Use the local file in the setup by using the `scout setup database --files <cache dir>`

Thanks for the quick help!

**Comment by northwestwitch** [comment]
> Thanks for the quick help!

You're very welcome! :)
