### ISSUE TITLE
Error while opening an institute's case due to chanjo-report

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4101]
In current main branch, try to open an institute and then a case. You get this error:

```
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/scout/server/utils.py", line 91, in decorated_function
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case.html", line 510, in top-level template code
    value="{{ button_value if button_value }}"
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/scout/server/templates/layout.html", line 1, in top-level template code
    {% extends "bootstrap_global.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/scout/server/templates/bootstrap_global.html", line 62, in top-level template code
    {% block body %}
  File "/home/worker/app/scout/server/templates/bootstrap_global.html", line 65, in block 'body'
    {% block content %}
  File "/home/worker/app/scout/server/templates/layout.html", line 93, in block 'content'
    {% block content_main %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case.html", line 39, in block 'content_main'
    {{ action_bar(institute, case, causatives, collaborators, current_user, report_types, has_rna_tracks) }} <!-- This is the sidebar -->
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html", line 13, in template
    {{ reports(institute,case, report_types) }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html", line 91, in template
    <form method="POST" id="coverage_html" target="_blank" rel="noopener" action="{{ url_for('report.report', sample_id=case.individual_ids, level=institute.coverage_cutoff, panel_name=case.panel_names|join(', ')) }}">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'report.report' with values ['level', 'panel_name', 'sample_id']. Did you mean 'cases.hpoterms' instead?
```

**Comment by northwestwitch** [comment]
It's a dependency conflict with chanjo or chanjo report for sure!

**Comment by northwestwitch** [comment]
This happened when I merged #4095 earlier today!

**Comment by northwestwitch** [comment]
Ok perhaps it could be this error: chanjo report is created using chanjo. If you try to install chanjo-report into an env containing python 3.11 and you try to run chanjo --help you get:

```
(py311) chiararasi@n177-p182 chanjo-report % chanjo --help
Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/py311/bin/chanjo", line 5, in <module>
    from chanjo.cli import root
  File "/Users/chiararasi/miniconda3/envs/py311/lib/python3.11/site-packages/chanjo/cli/__init__.py", line 2, in <module>
    from .calculate import calculate
  File "/Users/chiararasi/miniconda3/envs/py311/lib/python3.11/site-packages/chanjo/cli/calculate.py", line 7, in <module>
    from chanjo.store.api import ChanjoDB
  File "/Users/chiararasi/miniconda3/envs/py311/lib/python3.11/site-packages/chanjo/store/api.py", line 6, in <module>
    from alchy import Manager
  File "/Users/chiararasi/miniconda3/envs/py311/lib/python3.11/site-packages/alchy/__init__.py", line 15, in <module>
    from .model import ModelBase, make_declarative_base
  File "/Users/chiararasi/miniconda3/envs/py311/lib/python3.11/site-packages/alchy/model.py", line 12, in <module>
    from .utils import (
  File "/Users/chiararasi/miniconda3/envs/py311/lib/python3.11/site-packages/alchy/utils.py", line 9, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/Users/chiararasi/miniconda3/envs/py311/lib/python3.11/collections/__init__.py)
(py311) chiararasi@n177-p182 chanjo-report %
```

Looks like Iterable was removed from Collections already in Python 3.10. --> https://stackoverflow.com/questions/72032032/importerror-cannot-import-name-iterable-from-collections-in-python

So yes, looks like chanjo can be run only with python <= 3.9 😭

**Comment by dnil** [comment]
> Ok perhaps it could be this error: chanjo report is created using chanjo. If you try to install chanjo-report into an env containing python 3.11 and you try to run chanjo --help you get:
> 
> ```
> (py311) chiararasi@n177-p182 chanjo-report % chanjo --help
> Traceback (most recent call last):
>   File "/Users/chiararasi/miniconda3/envs/py311/bin/chanjo", line 5, in <module>
>     from chanjo.cli import root
>   File "/Users/chiararasi/miniconda3/envs/py311/lib/python3.11/site-packages/chanjo/cli/__init__.py", line 2, in <module>
>     from .calculate import calculate
>   File "/Users/chiararasi/miniconda3/envs/py311/lib/python3.11/site-packages/chanjo/cli/calculate.py", line 7, in <module>
>     from chanjo.store.api import ChanjoDB
>   File "/Users/chiararasi/miniconda3/envs/py311/lib/python3.11/site-packages/chanjo/store/api.py", line 6, in <module>
>     from alchy import Manager
>   File "/Users/chiararasi/miniconda3/envs/py311/lib/python3.11/site-packages/alchy/__init__.py", line 15, in <module>
>     from .model import ModelBase, make_declarative_base
>   File "/Users/chiararasi/miniconda3/envs/py311/lib/python3.11/site-packages/alchy/model.py", line 12, in <module>
>     from .utils import (
>   File "/Users/chiararasi/miniconda3/envs/py311/lib/python3.11/site-packages/alchy/utils.py", line 9, in <module>
>     from collections import Iterable
> ImportError: cannot import name 'Iterable' from 'collections' (/Users/chiararasi/miniconda3/envs/py311/lib/python3.11/collections/__init__.py)
> (py311) chiararasi@n177-p182 chanjo-report %
> ```
> 
> Looks like Iterable was removed from collections already in Python 3.10. --> https://stackoverflow.com/questions/72032032/importerror-cannot-import-name-iterable-from-collections-in-python
> 
> So yes, looks like chanjo can be run only with python <= 3.9 😭

We could try-catch that one as well, importing from the old sub category of the new didn’t exist…

**Comment by northwestwitch** [comment]
> We could try-catch that one as well, importing from the old sub category of the new didn’t exist…

In alchy? Mmm I think we should try to switch from chanjo to chanjo2. Perhaps having chanjo2 to be able to create report from the old chanjo database?

**Comment by dnil** [comment]
Absolutely - the report side doesn’t feel that much to cover - only a bit of a backlog to cover on the old cases, but that should be easier with d4 compared to chanjo. Have you started running it on prod cases already?

**Comment by dnil** [comment]
And agree on alchy - I didn’t realize. I’m not entirely sure they would take a PR, kind of rather want ppl to go to SQLservice instead.

**Comment by northwestwitch** [comment]
> And agree on alchy - I didn’t realize. I’m not entirely sure they would take a PR, kind of rather want ppl to go to SQLservice instead.

Could also be that there are further problems once you fix the Iterable thing.  haven't tried. 

Chanjo2 can create a report and a geneS overview page. I have an open PR for this other gene overview page ([this one](https://github.com/Clinical-Genomics/chanjo-report/blob/9ca7a8ad279ab862c148ce4dfe2b2e675fdc4be4/chanjo_report/server/blueprints/report/views.py#L25)), but we haven't tried with prod cases yet. Perhaps we should start @henrikstranneheim
