### ISSUE TITLE
missing acmg classification in report?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4172]
```
2023-10-25 09:29:01,049 - scout.server.app - ERROR: Exception on /cust151/F0056730/pdf_report [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1744]
Traceback (most recent call last):
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 2529, in wsgi_app
   response = self.full_dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
   rv = self.dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
 File "/home/worker/app/scout/server/blueprints/cases/views.py", line 267, in pdf_case_report
   html_report = render_template("cases/case_report.html", format="pdf", **data)
 File "/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
   return _render(app, template, context)
 File "/venv/lib/python3.8/site-packages/flask/templating.py", line 130, in _render
   rv = template.render(context)
 File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
   self.environment.handle_exception()
 File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
   raise rewrite_traceback_stack(source=source)
 File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_report.html", line 1400, in top-level template code
   <span class="badge badge-pill badge-secondary" title="Manual rank">{{ manual_rank_options[variant.manual_rank]['label'] }}</span>
 File "/home/worker/app/scout/server/templates/report_base.html", line 20, in top-level template code
   {% block body %}
 File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_report.html", line 61, in block 'body'
   {{ pinned_panel() }}
 File "/venv/lib/python3.8/site-packages/jinja2/runtime.py", line 777, in _invoke
   rv = self._func(*arguments)
 File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_report.html", line 345, in template
   {{ somatic_variant_table(variants.suspects_detailed) }}
 File "/venv/lib/python3.8/site-packages/jinja2/runtime.py", line 777, in _invoke
   rv = self._func(*arguments)
 File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_report.html", line 1338, in template
   {% for variant in variants|selectattr("acmg_classification.short", "equalto", acmg)|selectattr("first_rep_gene.hgnc_symbol", "defined")|sort(attribute='first_rep_gene.hgnc_symbol')%}
 File "/venv/lib/python3.8/site-packages/jinja2/filters.py", line 409, in do_sort
   return sorted(value, key=key_func, reverse=reverse)
 File "/venv/lib/python3.8/site-packages/jinja2/filters.py", line 1764, in select_or_reject
   for item in value:
 File "/venv/lib/python3.8/site-packages/jinja2/filters.py", line 1765, in select_or_reject
   if func(item):
 File "/venv/lib/python3.8/site-packages/jinja2/filters.py", line 1750, in <lambda>
   return lambda item: modfunc(func(transfunc(item)))
 File "/venv/lib/python3.8/site-packages/jinja2/filters.py", line 70, in attrgetter
   item = environment.getitem(item, part)
 File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 466, in getitem
   return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'acmg_classification'
```

**Comment by dnil** [comment]
Here is another one, this time without obvious issues in ACMG classification so maybe more of a missing key thing after all.
```
2023-10-25 16:47:37,361 - scout.server.app - ERROR: Exception on /cust002/F0016070-2/pdf_report [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1744]
Traceback (most recent call last):
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 2529, in wsgi_app
   response = self.full_dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
   rv = self.dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
 File "/home/worker/app/scout/server/blueprints/cases/views.py", line 267, in pdf_case_report
   html_report = render_template("cases/case_report.html", format="pdf", **data)
 File "/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
   return _render(app, template, context)
 File "/venv/lib/python3.8/site-packages/flask/templating.py", line 130, in _render
   rv = template.render(context)
 File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
   self.environment.handle_exception()
 File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
   raise rewrite_traceback_stack(source=source)
 File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_report.html", line 1400, in top-level template code
   <span class="badge badge-pill badge-secondary" title="Manual rank">{{ manual_rank_options[variant.manual_rank]['label'] }}</span>
 File "/home/worker/app/scout/server/templates/report_base.html", line 20, in top-level template code
   {% block body %}
 File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_report.html", line 61, in block 'body'
   {{ pinned_panel() }}
 File "/venv/lib/python3.8/site-packages/jinja2/runtime.py", line 777, in _invoke
   rv = self._func(*arguments)
 File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_report.html", line 345, in template
   {{ somatic_variant_table(variants.suspects_detailed) }}
 File "/venv/lib/python3.8/site-packages/jinja2/runtime.py", line 777, in _invoke
   rv = self._func(*arguments)
 File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_report.html", line 1338, in template
   {% for variant in variants|selectattr("acmg_classification.short", "equalto", acmg)|selectattr("first_rep_gene.hgnc_symbol", "defined")|sort(attribute='first_rep_gene.hgnc_symbol')%}
 File "/venv/lib/python3.8/site-packages/jinja2/filters.py", line 409, in do_sort
   return sorted(value, key=key_func, reverse=reverse)
 File "/venv/lib/python3.8/site-packages/jinja2/filters.py", line 1764, in select_or_reject
   for item in value:
 File "/venv/lib/python3.8/site-packages/jinja2/filters.py", line 1765, in select_or_reject
   if func(item):
 File "/venv/lib/python3.8/site-packages/jinja2/filters.py", line 1750, in <lambda>
   return lambda item: modfunc(func(transfunc(item)))
 File "/venv/lib/python3.8/site-packages/jinja2/filters.py", line 70, in attrgetter
   item = environment.getitem(item, part)
 File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 466, in getitem
   return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'acmg_classification'
```

**Comment by dnil** [comment]
The issue pertains to touched variants on the somatic general report.

**Comment by dnil** [comment]
- crashes when displaying the report with a pinned variant, but not with other tags e.g. a Other Manual Ranked
