### ISSUE TITLE
Case display name missing causes load to fail

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4197]
But the guide says that the field is optional: https://clinical-genomics.github.io/scout/admin-guide/load-config/

Tested with main branch by removing 'family_name: '643594' from config file:

```
2023-11-09 13:56:48 n187-p80.local scout.parse.panel[27759] INFO Parsing gene panel panel1
2023-11-09 13:56:48 n187-p80.local scout.build.panel[27759] INFO Building panel with name: panel1
2023-11-09 13:56:48 n187-p80.local scout.build.panel[27759] WARNING Symbol in database does not correspond to symbol in panel file for gene 25964
2023-11-09 13:56:48 n187-p80.local scout.build.panel[27759] WARNING Using symbol RETREG1 for gene 25964, instead of FAM134B
2023-11-09 13:56:48 n187-p80.local scout.build.panel[27759] WARNING Symbol in database does not correspond to symbol in panel file for gene 16318
2023-11-09 13:56:48 n187-p80.local scout.build.panel[27759] WARNING Using symbol PPP1R2B for gene 16318, instead of PPP1R2P3
2023-11-09 13:56:48 n187-p80.local scout.adapter.mongo.panel[27759] INFO loading panel Test panel, version 1.0 to database
2023-11-09 13:56:48 n187-p80.local scout.adapter.mongo.panel[27759] INFO Nr genes in panel: 263
2023-11-09 13:56:48 n187-p80.local scout.adapter.mongo.panel[27759] INFO Fetch gene panel panel1, version 1.0 from database
2023-11-09 13:56:48 n187-p80.local scout.adapter.mongo.panel[27759] DEBUG Panel saved
Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/py38/bin/scout", line 33, in <module>
    sys.exit(load_entry_point('scout-browser', 'console_scripts', 'scout')())
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/commands/setup/setup_scout.py", line 204, in demo
    setup_scout(
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/load/setup.py", line 201, in setup_scout
    load_demo_cases(adapter)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/load/setup.py", line 231, in load_demo_cases
    config_data = parse_case_data(config=case_data)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/parse/case.py", line 51, in parse_case_data
    config_dict: dict = parse_case_config(config=config)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/parse/case.py", line 99, in parse_case_config
    return CaseLoader(**config).model_dump()
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/models/case/case_loading_models.py", line 414, in __init__
    super().__init__(vcf_files=vcfs, **data)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for CaseLoader
family_name
  Field required [type=missing, input_value={'vcf_files': VcfFiles(vc...case_id': 'internal_id'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
(py38) chiararasi@n187-p80 scout %
```

**Comment by dnil** [comment]
It is weird with them not having a name.. But I guess they have their ID and are happy with it. 😅
