### ISSUE TITLE
Error in remove_case_group

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4205]
```
2023-11-13 09:44:43,379 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /cust087/F0044881-2/6551e0ef1a1a70ed7468a5b6/remove_case_group [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/worker/app/scout/server/blueprints/cases/views.py", line 910, in remove_case_group
    controllers.remove_case_group(store, current_user, institute_id, case_name, case_group)
  File "/home/worker/app/scout/server/blueprints/cases/controllers.py", line 1075, in remove_case_group
    current_group_ids.remove(ObjectId(case_group))
ValueError: list.remove(x): x not in list
```

**Comment by northwestwitch** [comment]
This happens when there are 2 tabs open and you remove a case from a group in one tab. If you go to the other tab, case groups section, and click on the case that was removed, then you get the error above
