### ISSUE TITLE
Saving MEI research filters crash

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4231]
```
2023-11-24 10:57:30,880 - scout.server.app - ERROR: Exception on /cust002/F0030513-2/mei/variants [POST] [in /venv/lib/python3.8/site-packages/flask/app.py:1744]
Traceback (most recent call last):
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 2529, in wsgi_app
   response = self.full_dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
   rv = self.dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
 File "/home/worker/app/scout/server/utils.py", line 86, in decorated_function
   context = func(*args, **kwargs)
 File "/home/worker/app/scout/server/blueprints/variants/views.py", line 349, in mei_variants
   form = controllers.populate_filters_form(
 File "/home/worker/app/scout/server/blueprints/variants/controllers.py", line 1417, in populate_filters_form
   form = persistent_filter_actions(
 File "/home/worker/app/scout/server/blueprints/variants/controllers.py", line 1485, in persistent_filter_actions
   store.stash_filter(filter_obj, institute_obj, case_obj, user_obj, category)
 File "/home/worker/app/scout/adapter/mongo/filter.py", line 96, in stash_filter
   link = url_for(target, case_name=case_name, **filter_dict)
 File "/venv/lib/python3.8/site-packages/flask/helpers.py", line 256, in url_for
   return current_app.url_for(
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1981, in url_for
   if endpoint[:1] == ".":
TypeError: 'NoneType' object is not subscriptable
```

**Comment by dnil** [comment]
Ah, filter was actually created; could be attempt to filter on empty variant collection. The variants were not loaded on this attempt: since the "request research" flag had already been lowered, a force was needed..

**Comment by northwestwitch** [comment]
I'll start working on this!
