### ISSUE TITLE
BioNanoGenomics Access 1.8 type of count fields changed?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4259]
```
2023-12-01 16:18:18,793 - scout.server.app - ERROR: Exception on /cust002/F0052622/bionano [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1744]
Traceback (most recent call last):
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 2529, in wsgi_app
   response = self.full_dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
   rv = self.dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
 File "/home/worker/app/scout/server/utils.py", line 91, in decorated_function
   return render_template(template_name, **context)
 File "/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
   return _render(app, template, context)
 File "/venv/lib/python3.8/site-packages/flask/templating.py", line 130, in _render
   rv = template.render(context)
 File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
   self.environment.handle_exception()
 File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
   raise rewrite_traceback_stack(source=source)
 File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_bionano.html", line 156, in top-level template code
   This is the processed FSHD report for the case. Please visit your <a href="{{bionano_access_url}}" target="_blank" rel="noopener noreferrer" referrerpolicy="no-referrer">Bionano Access server</a>
 File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_tabular_view.html", line 72, in top-level template code
   <textarea name="synopsis" class="form-control" cols="30" rows="10">{{ case.synopsis }}</textarea>
 File "/home/worker/app/scout/server/templates/layout.html", line 1, in top-level template code
   {% extends "bootstrap_global.html" %}
 File "/home/worker/app/scout/server/templates/bootstrap_global.html", line 62, in top-level template code
   {% block body %}
 File "/home/worker/app/scout/server/templates/bootstrap_global.html", line 65, in block 'body'
   {% block content %}
 File "/home/worker/app/scout/server/templates/layout.html", line 93, in block 'content'
   {% block content_main %}{% endblock %}
 File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_bionano.html", line 22, in block 'content_main'
   {{ fshd_case_page() }}
 File "/venv/lib/python3.8/site-packages/jinja2/runtime.py", line 777, in _invoke
   rv = self._func(*arguments)
 File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_bionano.html", line 33, in template
   <div class="col-xs-12 col-md-12">{{ bionano_individuals_table(case, institute, tissue_types) }}</div>
 File "/venv/lib/python3.8/site-packages/jinja2/runtime.py", line 777, in _invoke
   rv = self._func(*arguments)
 File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_bionano.html", line 89, in template
   <tr {% if d4z4.chromosome == 4 and d4z4.count < 11 and d4z4.haplotype == "4qA" %}
TypeError: '<' not supported between instances of 'str' and 'int'
```
But, at least connectivity seems ok.. 😁

**Comment by dnil** [comment]
Ah. 
![Screenshot 2023-12-01 at 17 06 08](https://github.com/Clinical-Genomics/scout/assets/758570/b4a64689-d955-484f-be80-33391c6022d4)
