### ISSUE TITLE
JSONDecodeError on case MT report

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4267]
```
2023-12-07 15:38:15,069 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /cust003/23444/mt_report [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/worker/app/scout/server/blueprints/cases/views.py", line 297, in mt_report
    if controllers.mt_excel_files(store, case_obj, temp_excel_dir):
  File "/home/worker/app/scout/server/blueprints/cases/controllers.py", line 711, in mt_excel_files
    coverage_stats = mt_coverage_stats(samples)
  File "/home/worker/app/scout/server/blueprints/cases/controllers.py", line 676, in mt_coverage_stats
    ref_cov_data = json.loads(resp.text)  # mean coverage over the transcripts of ref chrom
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by northwestwitch** [comment]
@dnil you've been faster, closing this as duplicate
