### ISSUE TITLE
Phenomizer connection down

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4295]
```
2023-12-20 08:05:17,355 - scout.server.app - ERROR: Exception on /cust002/17083/phenotypes/actions [POST] [in /venv/lib/python3.8/site-packages/flask/app.py:1744]
Traceback (most recent call last):
 File "/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 467, in _make_request
   self._validate_conn(conn)
 File "/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
   conn.connect()
 File "/venv/lib/python3.8/site-packages/urllib3/connection.py", line 642, in connect
   sock_and_verified = _ssl_wrap_socket_and_match_hostname(
 File "/venv/lib/python3.8/site-packages/urllib3/connection.py", line 782, in _ssl_wrap_socket_and_match_hostname
   ssl_sock = ssl_wrap_socket(
 File "/venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 470, in ssl_wrap_socket
   ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
 File "/venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 514, in _ssl_wrap_socket_impl
   return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
 File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
   return self.sslsocket_class._create(
 File "/usr/local/lib/python3.8/ssl.py", line 1073, in _create
   self.do_handshake()
 File "/usr/local/lib/python3.8/ssl.py", line 1342, in do_handshake
   self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
   response = self._make_request(
 File "/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 491, in _make_request
   raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "/venv/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
   resp = conn.urlopen(
 File "/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 844, in urlopen
   retries = retries.increment(
 File "/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 515, in increment
   raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='[compbio.charite.de](http://compbio.charite.de/)', port=443): Max retries exceeded with url: /phenomizer/phenomizer/PhenomizerServiceURI?mobilequery=true&terms=HP%3A0001250&username=scout&password=scout123 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 2529, in wsgi_app
   response = self.full_dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
   rv = self.dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
 File "/home/worker/app/scout/server/blueprints/cases/views.py", line 469, in phenotypes_actions
   diseases = controllers.phenomizer_diseases(hpo_ids, case_obj)
 File "/home/worker/app/scout/server/blueprints/cases/controllers.py", line 78, in phenomizer_diseases
   diseases = [result for result in results if result["p_value"] <= p_value_treshold]
 File "/home/worker/app/scout/server/blueprints/cases/controllers.py", line 78, in <listcomp>
   diseases = [result for result in results if result["p_value"] <= p_value_treshold]
 File "/venv/lib/python3.8/site-packages/query_phenomizer/utils.py", line 120, in query
   raw_result = query_phenomizer(usr, pwd, *hpo_terms)
 File "/venv/lib/python3.8/site-packages/query_phenomizer/utils.py", line 95, in query_phenomizer
   r = requests.get(base_string, params=questions, timeout=10)
 File "/venv/lib/python3.8/site-packages/requests/api.py", line 73, in get
   return request("get", url, params=params, **kwargs)
 File "/venv/lib/python3.8/site-packages/requests/api.py", line 59, in request
   return session.request(method=method, url=url, **kwargs)
 File "/venv/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
   resp = self.send(prep, **send_kwargs)
 File "/venv/lib/python3.8/site-packages/requests/sessions.py", line 725, in send
   history = [resp for resp in gen]
 File "/venv/lib/python3.8/site-packages/requests/sessions.py", line 725, in <listcomp>
   history = [resp for resp in gen]
 File "/venv/lib/python3.8/site-packages/requests/sessions.py", line 266, in resolve_redirects
   resp = self.send(
 File "/venv/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
   r = adapter.send(request, **kwargs)
 File "/venv/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
   raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='[compbio.charite.de](http://compbio.charite.de/)', port=443): Max retries exceeded with url: /phenomizer/phenomizer/PhenomizerServiceURI?mobilequery=true&terms=HP%3A0001250&username=scout&password=scout123 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
```
The site appears up; new or expired cert perhaps?

**Comment by dnil** [comment]
The site is indeed operational, but the API does not seem to work currently.

Trying also with the corresponding "https" url from the CLI:
```
[2023-12-20 08:26:36,300] query_phenomizer.cli      INFO     HPO terms used: HP:0001250
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='compbio.charite.de', port=443): Max retries exceeded with url: /phenomizer/phenomizer/PhenomizerServiceURI?mobilequery=true&terms=HP%3A0001250&username=scout&password=scout123 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/scout39n/bin/query_phenomizer", line 33, in <module>
    sys.exit(load_entry_point('query-phenomizer', 'console_scripts', 'query_phenomizer')())
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/dannil/sandbox/query_phenomizer/query_phenomizer/cli.py", line 88, in cli
    if not validate_term(username, password, term):
  File "/Users/dannil/sandbox/query_phenomizer/query_phenomizer/utils.py", line 146, in validate_term
    for line in query(usr, pwd, hpo_term):
  File "/Users/dannil/sandbox/query_phenomizer/query_phenomizer/utils.py", line 120, in query
    raw_result = query_phenomizer(usr, pwd, *hpo_terms)
  File "/Users/dannil/sandbox/query_phenomizer/query_phenomizer/utils.py", line 95, in query_phenomizer
    r = requests.get(base_string, params=questions, timeout=10)
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/miniconda3/envs/scout39n/lib/python3.9/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='compbio.charite.de', port=443): Max retries exceeded with url: /phenomizer/phenomizer/PhenomizerServiceURI?mobilequery=true&terms=HP%3A0001250&username=scout&password=scout123 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
```

**Comment by dnil** [comment]
It does look like the Phenomizer website certificated was recently renewed: perhaps there is a separate one for the API site that wasn't?

![Screenshot 2023-12-20 at 10 31 43](https://github.com/Clinical-Genomics/scout/assets/758570/edcbf0a1-4993-416e-9b04-130d4df34b13)

Contacted Sebastian Köhler per email.

**Comment by dnil** [comment]
Hmm, in a plot twist this now works locally from a browser, but e.g. scout-stage still fails with the same SSL error.

https://compbio.charite.de/phenomizer/phenomizer/PhenomizerServiceURI?mobilequery=true&terms=HP%3A0001250&username=xxxx&password=xxxxxxx

<img width="992" alt="Screenshot 2024-01-09 at 09 30 54" src="https://github.com/Clinical-Genomics/scout/assets/758570/af79ee3a-252f-405a-828b-2a387a25552d">

**Comment by dnil** [comment]
I'll unblock it I think - while the error was most likely triggered by the Charite certificate change, it does appear it is in order now. Maybe the `query_phenomizer` is using an old version of some crypto stuff?

**Comment by dnil** [comment]
No, it is still probably the server; perhaps they switched the cert / TLS version without updating all configs to say they support that version?

Setting verify to false on the request does seem to solve it: 
```
[2024-01-09 11:04:43,276] query_phenomizer.cli      INFO     HPO terms used: HP:0001250
/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'compbio.charite.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
[2024-01-09 11:04:45,489] query_phenomizer.cli      INFO     HPO term : HP:0001250 does exist!
```

**Comment by dnil** [comment]
before 

```
[2024-01-09 10:57:22,750] query_phenomizer.cli      INFO     HPO terms used: HP:0001250
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/urllib3/connection.py", line 782, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 470, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 514, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='compbio.charite.de', port=443): Max retries exceeded with url: /phenomizer/phenomizer/PhenomizerServiceURI?mobilequery=true&terms=HP%3A0001250&username=scout&password=scout123 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/phenomizer/bin/query_phenomizer", line 33, in <module>
    sys.exit(load_entry_point('query-phenomizer', 'console_scripts', 'query_phenomizer')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dannil/sandbox/query_phenomizer/query_phenomizer/cli.py", line 88, in cli
    if not validate_term(username, password, term):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dannil/sandbox/query_phenomizer/query_phenomizer/utils.py", line 146, in validate_term
    for line in query(usr, pwd, hpo_term):
  File "/Users/dannil/sandbox/query_phenomizer/query_phenomizer/utils.py", line 120, in query
    raw_result = query_phenomizer(usr, pwd, *hpo_terms)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dannil/sandbox/query_phenomizer/query_phenomizer/utils.py", line 95, in query_phenomizer
    r = requests.get(base_string, params=questions, timeout=10)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='compbio.charite.de', port=443): Max retries exceeded with url: /phenomizer/phenomizer/PhenomizerServiceURI?mobilequery=true&terms=HP%3A0001250&username=scout&password=scout123 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
```

after 

```
[2024-01-09 11:04:43,276] query_phenomizer.cli      INFO     HPO terms used: HP:0001250
/usr/local/miniconda3/envs/phenomizer/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'compbio.charite.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
[2024-01-09 11:04:45,489] query_phenomizer.cli      INFO     HPO term : HP:0001250 does exist!
Aborted!
```

**Comment by dnil** [comment]
Fixed in https://github.com/Clinical-Genomics/query_phenomizer/pull/1

**Comment by dnil** [comment]
Ah, no auto pip-deploy there. Just a moment..

**Comment by dnil** [comment]
Ok, that may be a longer moment; only @moonso has write on that pypi repo. See https://github.com/moonso/query_phenomizer/issues/7.

**Comment by dnil** [comment]
Yup, installing query_phenomizer 1.2.1 resolves the issue. By not checking the Charite cert. It is still https, but vulnerable to more middleman attacks. We dont expect a lot of issues with that and the return of phenotypes, so on the balance we should prefer keeping the service operational.

<img width="1715" alt="Screenshot 2024-01-09 at 14 50 27" src="https://github.com/Clinical-Genomics/scout/assets/758570/7a1ec91c-45db-4ba1-8e79-0f7d2c09ad3f">
