### ISSUE TITLE
Scout view users can fail on broken entries...

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4303]
```
θ62° [daniel.nilsson@hasta:~/tmp]└2 [S_base] 3s $ scout view users
2023-12-20 17:07:50 hasta.scilifelab.se scout.commands.base[87494] INFO Running scout version 4.75
2023-12-20 17:07:50 hasta.scilifelab.se scout.commands.base[87494] DEBUG Debug logging enabled.
2023-12-20 17:07:50 hasta.scilifelab.se scout.commands.base[87494] WARNING Support for launching Scout using a .yaml config file is deprecated and will be removed in the next major release (5.0). Use a PYTHON (.py) config file instead.
2023-12-20 17:07:50 hasta.scilifelab.se scout.adapter.client[87494] INFO Connected to MongoDB 7.0.2
2023-12-20 17:07:50 hasta.scilifelab.se scout.adapter.mongo.base[87494] DEBUG Database name: scout-stage
2023-12-20 17:07:50 hasta.scilifelab.se scout.server.app[87494] INFO Enable Phenopacket API
2023-12-20 17:07:51 hasta.scilifelab.se scout.commands.view.users[87494] INFO Running scout view users
#name   email   roles   institutes
Traceback (most recent call last):
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/bin/scout", line 8, in <module>
    sys.exit(cli())
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/scout/commands/view/users.py", line 27, in users
    user_obj["name"],
KeyError: 'name'
```
Works on prod and local, so very likely an old or otherwise broken user on stage. We'll fix that, but in general, little reason to crash, right?

**Comment by northwestwitch** [comment]
If you check the user list on the web portal you'll notice that there is a user which which has no data. 

<img width="1436" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/90e5554b-121f-4f90-8fd3-dce86545086b">


In the database it looks like this:

<img width="424" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/3a952cf8-f5b9-432d-b383-5432371a62cb">

I've removed it. I have no idea how it might have happened. Perhaps we just clicked on insert document on compass by mistake? I'm closing this issue but let's re-open and fix it in the code if this happens again!
