### ISSUE TITLE
Removing variant from clinvar submission crash

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4327]
```
2024-01-10 15:38:49,063 - scout.server.app - ERROR: Exception on /63f8de51e1420fe95c99c925/variant_data [POST] [in /venv/lib/python3.8/site-packages/flask/app.py:1744]
Traceback (most recent call last):
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 2529, in wsgi_app
   response = self.full_dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
   rv = self.dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
 File "/home/worker/app/scout/server/blueprints/clinvar/views.py", line 82, in clinvar_delete_object
   store.delete_clinvar_object(
 File "/home/worker/app/scout/adapter/mongo/clinvar.py", line 395, in delete_clinvar_object
   linking_id = variant_object.get(
AttributeError: 'NoneType' object has no attribute 'get'
```
Kind of looks like re-adding the variant worked ok.

**Comment by northwestwitch** [comment]
Ah I see, this is another of those cases where the user has more than one tab open and interacts with stuff previously removed in another tab. Should be an easy fix!
