### ISSUE TITLE
Error while updating genes

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4368]
```
2024-01-25 10:29:14 hasta.scilifelab.se scout.load.hgnc_gene[12732] INFO Nr of genes without coordinates in build 38: 43840
2024-01-25 10:29:14 hasta.scilifelab.se scout.load.hgnc_gene[12732] INFO Loading 0 genes to database
2024-01-25 10:29:14 hasta.scilifelab.se scout.adapter.mongo.hgnc[12732] INFO Loading gene bulk with length 0
Traceback (most recent call last):
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/bin/scout", line 8, in <module>
    sys.exit(cli())
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/scout/commands/update/genes.py", line 165, in genes
    build=genome_build,
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/scout/load/hgnc_gene.py", line 98, in load_hgnc_genes
    adapter.load_hgnc_bulk(gene_objects)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/scout/adapter/mongo/hgnc.py", line 39, in load_hgnc_bulk
    result = self.hgnc_collection.insert_many(gene_objs)
  File "/home/proj/stage/bin/miniconda3/envs/S_scout/lib/python3.7/site-packages/pymongo/collection.py", line 755, in insert_many
    raise TypeError("documents must be a non-empty list")
TypeError: documents must be a non-empty list
```

**Comment by northwestwitch** [comment]
This was fixed temporarily by downloading the ensembl files in build 38: `scout download ensembl --build38`

I think it's a temporary problem due to their servers so I'm closing the issue, but let's reopen if it happens again!
