### ISSUE TITLE
ZeroDivisionError: division by zero while loading case report

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4418]
2024-02-09 11:40:37,309 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /cust087/F0059097/pdf_report [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/worker/app/scout/server/blueprints/cases/views.py", line 276, in pdf_case_report
    html_report = render_template("cases/case_report.html", format="pdf", **data)

  File "/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/venv/lib/python3.8/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_report.html", line 1416, in top-level template code
    <span class="badge badge-pill badge-secondary" title="Manual rank">{{ manual_rank_options[variant.manual_rank]['label'] }}</span>
  File "/home/worker/app/scout/server/templates/report_base.html", line 19, in top-level template code
    {% block body %}
  File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_report.html", line 61, in block 'body'
    {{ pinned_panel() }}
  File "/venv/lib/python3.8/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_report.html", line 347, in template
    {{ somatic_variant_table(variants.suspects_detailed) }}
  File "/venv/lib/python3.8/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_report.html", line 1359, in template
    {{ variant_table_line(variant) }}
  File "/venv/lib/python3.8/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_report.html", line 1379, in template
    <td>{% for sample in variant.samples %}{% if sample.is_affected %} {{ (sample.allele_depths[1]/sample.read_depth*100)|round|int }}{% endif %} {% endfor %}</td>
ZeroDivisionError: division by zero

**Comment by dnil** [comment]
Heh, there is something new every day! Variants with read-depth zero - where is the world headed.. 😂

**Comment by dnil** [comment]
Confirmed with the user that it was the DUP with 0 read depth causing the issue. If the variant is unmarked the report with only SNVs can be generated. The resident on call checked the case directly in Scout, so the answer to the patient is out anyway.
