### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'cancer_rank_options' is undefined

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4554]
```
2024-04-08 14:11:22,266 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /cust000/F0045564-RNAreanalys/case_report [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/worker/app/scout/server/utils.py", line 92, in decorated_function
    return render_template(template_name, **context)
  File "/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/venv/lib/python3.8/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_report.html", line 1439, in top-level template code
    <span class="badge badge-pill badge-secondary" title="Manual rank">{{ manual_rank_options[variant.manual_rank]['label'] }}</span>
  File "/home/worker/app/scout/server/templates/report_base.html", line 19, in top-level template code
    {% block body %}
  File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_report.html", line 63, in block 'body'
    {{ tagged_panel() }}
  File "/venv/lib/python3.8/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_report.html", line 419, in template
    {{ variant_content(variant, loop.index) }}
  File "/venv/lib/python3.8/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_report.html", line 444, in template
    {{ sv_variant_content(variant, index) }}
  File "/venv/lib/python3.8/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case_report.html", line 1030, in template
    <span class="badge badge-pill badge-secondary" title="Tier">{{ cancer_rank_options[variant.cancer_tier]['label'] }}</span>
  File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 466, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'cancer_rank_options' is undefined
```

**Comment by northwestwitch** [comment]
Ah OK, this error happens on stage. Perhaps it's fixed now?

**Comment by northwestwitch** [comment]
> Ah OK, this error happens on stage. Perhaps it's fixed now?

Nope!
