### ISSUE TITLE
No chanjo-report endpoint found

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4614]
2024-05-08 11:10:03,162 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /cust002/F0043487-2 [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:838]

```

Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/worker/app/scout/server/utils.py", line 92, in decorated_function
    return render_template(template_name, **context)
  File "/venv/lib/python3.8/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/venv/lib/python3.8/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case.html", line 540, in top-level template code
    {{ data.label }}
  File "/home/worker/app/scout/server/templates/layout.html", line 1, in top-level template code
    {% extends "bootstrap_global.html" %}
  File "/home/worker/app/scout/server/templates/bootstrap_global.html", line 62, in top-level template code
    {% block body %}
  File "/home/worker/app/scout/server/templates/bootstrap_global.html", line 65, in block 'body'
    {% block content %}
  File "/home/worker/app/scout/server/templates/layout.html", line 93, in block 'content'
    {% block content_main %}{% endblock %}
  File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case.html", line 37, in block 'content_main'
    {{ action_bar(institute, case, causatives, collaborators, current_user, report_types, has_rna_tracks) }} <!-- This is the sidebar -->
  File "/venv/lib/python3.8/site-packages/jinja2/runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
  File "/home/worker/app/scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html", line 15, in template
    {{ reports(institute,case, report_types) }}
  File "/venv/lib/python3.8/site-packages/jinja2/runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
  File "/home/worker/app/scout/server/blueprints/cases/templates/cases/collapsible_actionbar.html", line 101, in template
    <form method="POST" id="coverage_html" target="_blank" rel="noopener" action="{{ url_for('report.report', sample_id=case.individual_ids, level=institute.coverage_cutoff, panel_name=case.panel_names|join(', ')) }}">
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/venv/lib/python3.8/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'report.report' with values ['level', 'panel_name', 'sample_id']. Did you mean 'cases.hpoterms' instead?
```

**Comment by dnil** [comment]
Yes, reproduces on local when and only when chanjo is turned on.

<img width="1553" alt="Screenshot 2024-05-08 at 11 29 38" src="https://github.com/Clinical-Genomics/scout/assets/758570/8820cc96-497e-4633-b52e-0d6c086709ba">

**Comment by dnil** [comment]
The longer term solution is to go through with https://github.com/Clinical-Genomics/chanjo/issues/251 but that will in all likelyhood require at least a few days of effort. We have tried unfreezing Flask-SQLAlchemy and SQLAlchemy all the way down to chanjo, which does kind of solve the issue, but we then run into other more fatal Alchy 2.2.2 incompatibilities with SQLalchemy 2.0, which is in turn needed to use Flask-SQLAlchemy >= 3. And Flask-SQLAlchemy < 3 is incompatible with current werkzeug and Flask. In conclusion, we revert, at least partially.
