### ISSUE TITLE
Empty phenotype_terms - after editing genes perhaps?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4642]
2024-05-24 10:13:09,500 - scout.server.app - ERROR: Exception on /cust002/F0058805 [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1414]
Traceback (most recent call last):
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
   response = self.full_dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
   rv = self.dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
 File "/home/worker/app/scout/server/utils.py", line 92, in decorated_function
   return render_template(template_name, **context)
 File "/venv/lib/python3.8/site-packages/flask/templating.py", line 151, in render_template
   return _render(app, template, context)
 File "/venv/lib/python3.8/site-packages/flask/templating.py", line 132, in _render
   rv = template.render(context)
 File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
   self.environment.handle_exception()
 File "/venv/lib/python3.8/site-packages/jinja2/environment.py", line 939, in handle_exception
   raise rewrite_traceback_stack(source=source)
 File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case.html", line 540, in top-level template code
   {{ data.label }}
 File "/home/worker/app/scout/server/templates/layout.html", line 1, in top-level template code
   {% extends "bootstrap_global.html" %}
 File "/home/worker/app/scout/server/templates/bootstrap_global.html", line 62, in top-level template code
   {% block body %}
 File "/home/worker/app/scout/server/templates/bootstrap_global.html", line 65, in block 'body'
   {% block content %}
 File "/home/worker/app/scout/server/templates/layout.html", line 93, in block 'content'
   {% block content_main %}{% endblock %}
 File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case.html", line 38, in block 'content_main'
   {{ case_page() }}
 File "/venv/lib/python3.8/site-packages/jinja2/runtime.py", line 782, in _invoke
   rv = self._func(*arguments)
 File "/home/worker/app/scout/server/blueprints/cases/templates/cases/case.html", line 190, in template
   {{ hpo_panel(case, institute, config) }}
 File "/venv/lib/python3.8/site-packages/jinja2/runtime.py", line 782, in _invoke
   rv = self._func(*arguments)
 File "/home/worker/app/scout/server/blueprints/cases/templates/cases/phenotype.html", line 239, in template
   {% for hpo_term in case.phenotype_terms %}
TypeError: 'NoneType' object is not iterable

**Comment by dnil** [comment]
Ah, or rather to do with manual adding-removing to the gene list!
