### ISSUE TITLE
failed to load the example config

### ISSUE THREAD

**Issue by J35P312** [Clinical-Genomics/scout#469]
**Hello there!**
I followed the scout user examples, I managed to run the following commands:
scout setup database
scout load panel tests/fixtures/gene_lists/panel_1.txt
scout load case tests/fixtures/643594.config.yaml

Then I copied the example config file and ran scout serve --config ./config.py, which produced the following error:

```python
130-229-9-204-dhcp:scout jespereisfeldt$ scout serve --config ./config.py 
chanjo report not installed!
2017-04-11 11:52:53 130-229-9-204-dhcp.wlan.ki.se scout.commands.base[1016] INFO Running scout version 3.0.0b1
Traceback (most recent call last):
  File "/Users/jespereisfeldt/miniconda2/bin/scout", line 11, in <module>
    load_entry_point('scout-browser', 'console_scripts', 'scout')()
  File "/Users/jespereisfeldt/miniconda2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jespereisfeldt/miniconda2/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/jespereisfeldt/miniconda2/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jespereisfeldt/miniconda2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jespereisfeldt/miniconda2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/jespereisfeldt/miniconda2/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jespereisfeldt/scout/scout/commands/serve.py", line 28, in serve
    app = create_app(config=pymongo_config, config_file=config)
  File "/Users/jespereisfeldt/scout/scout/server/app.py", line 31, in create_app
    configure_extensions(app)
  File "/Users/jespereisfeldt/scout/scout/server/app.py", line 61, in configure_extensions
    extensions.mongo.init_app(app)
  File "/Users/jespereisfeldt/miniconda2/lib/python2.7/site-packages/flask_pymongo/__init__.py", line 253, in init_app
    db.authenticate(username, password)
  File "/Users/jespereisfeldt/miniconda2/lib/python2.7/site-packages/pymongo/database.py", line 1048, in authenticate
    connect=True)
  File "/Users/jespereisfeldt/miniconda2/lib/python2.7/site-packages/pymongo/mongo_client.py", line 505, in _cache_credentials
    sock_info.authenticate(credentials)
  File "/Users/jespereisfeldt/miniconda2/lib/python2.7/site-packages/pymongo/pool.py", line 523, in authenticate
    auth.authenticate(credentials, self)
  File "/Users/jespereisfeldt/miniconda2/lib/python2.7/site-packages/pymongo/auth.py", line 470, in authenticate
    auth_func(credentials, sock_info)
  File "/Users/jespereisfeldt/miniconda2/lib/python2.7/site-packages/pymongo/auth.py", line 450, in _authenticate_default
    return _authenticate_scram_sha1(credentials, sock_info)
  File "/Users/jespereisfeldt/miniconda2/lib/python2.7/site-packages/pymongo/auth.py", line 201, in _authenticate_scram_sha1
    res = sock_info.command(source, cmd)
  File "/Users/jespereisfeldt/miniconda2/lib/python2.7/site-packages/pymongo/pool.py", line 419, in command
    collation=collation)
  File "/Users/jespereisfeldt/miniconda2/lib/python2.7/site-packages/pymongo/network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/Users/jespereisfeldt/miniconda2/lib/python2.7/site-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.
```

the scout demo worked with no errors, so I guess it is the config file causing me troubles. Should I change the example config.py file in any way in order to make it work?
Thanks!
//Jesper

**Comment by moonso** [comment]
Yes sounds like there are some problems with the config stuff or what do you think @robinandeer

**Comment by dnil** [comment]
Looks like it would prefer to eat a yaml file rather than a .py file, doesn’t it?

By the way I gave loading a FindSV-vcf a shot. Needs relaxing a few things: I got as far as allowing loading of only SV-variants, 
ignoring “.” on QUAL. Next up something is not quite ok with variable genotype calls, but there I think I should update my FindSV installation before proceeding.. :)
Could you point me to some up-to-date FindSV vcfs I could test with Jesper? UPPMAX? Thanks!

**Comment by dnil** [comment]
Sorry, no, thats a py config.. Just ignore.. :)

**Comment by moonso** [comment]
Hi @J35P312 , is this still a problem?

**Comment by J35P312** [comment]
Hello again!
I downloaded the latest scout and tested the examples, now when I run the following command:
scout load panel tests/fixtures/gene_lists/panel_1.txt

I get this error:

Usage: scout load panel [OPTIONS] PATH

Error: Invalid value for "path": Path "tests/fixtures/gene_lists/panel_1.txt" does not exist.

I double checked, but could not find the fixtures folder either, is the fixtures folder renamed?

**Comment by moonso** [comment]
Ok we have moved this so it has to be updated. Thank you

**Comment by moonso** [comment]
Meanwhile you could try with `scout/demo/panel_1.txt`

**Comment by J35P312** [comment]
Thanks, now I had no troubles running scout load panel!

I tried rerunning the scout serve --config ./config.py step, but I still got the same autentication error as last time(I copied the example config from the latest readme file). I'm using python 3.6.1, could it be some problems with that version of python?

**Comment by robinandeer** [comment]
You need to customize the database authentication parameters in the config to suit your setup - the example in the README is simply showing which options are available

However, I suggest you try the demo setup and run: `scout --demo serve`
