### ISSUE TITLE
dbVar track unreachable?

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4720]
Today I keep getting this error:

```
2024-07-25 11:18:48,332 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /remote/cors/https://ftp.ncbi.nlm.nih.gov/pub/dbVar/sandbox/dbvarhub/hg19/common_global.bb [GET] [in /venv/lib/python3.11/site-packages/flask/app.py:838]
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7fbfcbf60ad0>: Failed to resolve '[ftp.ncbi.nlm.nih.gov](http://ftp.ncbi.nlm.nih.gov/)' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='[ftp.ncbi.nlm.nih.gov](http://ftp.ncbi.nlm.nih.gov/)', port=443): Max retries exceeded with url: /pub/dbVar/sandbox/dbvarhub/hg19/[common_global.bb](http://common_global.bb/) (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fbfcbf60ad0>: Failed to resolve '[ftp.ncbi.nlm.nih.gov](http://ftp.ncbi.nlm.nih.gov/)' ([Errno -3] Temporary failure in name resolution)"))
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='[ftp.ncbi.nlm.nih.gov](http://ftp.ncbi.nlm.nih.gov/)', port=443): Max retries exceeded with url: /pub/dbVar/sandbox/dbvarhub/hg19/[common_global.bb](http://common_global.bb/) (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fbfcbf60ad0>: Failed to resolve '[ftp.ncbi.nlm.nih.gov](http://ftp.ncbi.nlm.nih.gov/)' ([Errno -3] Temporary failure in name resolution)"))
```

**Comment by northwestwitch** [comment]
Yes, that was it!

**Comment by northwestwitch** [comment]
Weird because the files are there and are downloadable. But perhaps something is blocking them on the server?

**Comment by northwestwitch** [comment]
Looks like it was a temporary glitch and now the error is not occurring again (Tested on stage and prod, both fine). Let's close this one!
