### ISSUE TITLE
track items issue

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4974]
Thank you for taking the time to contribute an issue! 

**Describe the bug**

```
2024-10-21 15:34:19,398 - scout.server.app - ERROR: Exception on /cust143/K13031-24WGS/9024e860230f396b652f2ba78c531d34/22/29692575/29693575/igv [GET] [in /venv/lib/python3.11/site-packages/flask/app.py:838]
Traceback (most recent call last):
 File "/venv/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
   response = self.full_dispatch_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
   rv = self.handle_user_exception(e)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 194, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
                                               ^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
   rv = self.dispatch_request()
        ^^^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/worker/app/scout/server/blueprints/alignviewers/views.py", line 146, in igv
   display_obj = controllers.make_igv_tracks(case_obj, variant_id, chrom, start, stop)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/worker/app/scout/server/blueprints/alignviewers/controllers.py", line 110, in make_igv_tracks
   set_sample_tracks(display_obj, grouped_cases, chromosome)
 File "/home/worker/app/scout/server/blueprints/alignviewers/controllers.py", line 327, in set_sample_tracks
   "url": case[track_items][count],
          ~~~~~~~~~~~~~~~~~^^^^^^^
IndexError: list index out of range
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dnil** [comment]
The are a large number of `null` value keys on each individual, and in particular there is a `bam_file` null for the normal sample of this case, `trustylocust`. Investigating.

**Comment by dnil** [comment]
The main issue is with cg scout load config generation. I will label this a bug here as well, since we again don't really need to crash on it. But the fix in cg is more urgent, as a no-crash here will only bring back one of the alignments. The one that is missing from the config will still be missing.

**Comment by dnil** [comment]
No, seems this can still happen, under slightly different circumstances. Let's fix it properly.
