### ISSUE TITLE
Unmatched closing parentheses in HPO term API search?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4979]
**Describe the bug**
```
2024-10-22 11:27:50,738 - scout.server.app - ERROR: Exception on /api/v1/hpo-terms [GET] [in /venv/lib/python3.11/site-packages/flask/app.py:838]
Traceback (most recent call last):
 File "/venv/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
   response = self.full_dispatch_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
   rv = self.handle_user_exception(e)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 194, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
                                               ^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
   rv = self.dispatch_request()
        ^^^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/worker/app/scout/server/blueprints/cases/views.py", line 646, in hpoterms
   terms = sorted(store.hpo_terms(query=query), key=itemgetter("hpo_number"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/pymongo/synchronous/cursor.py", line 1281, in __next__
   return self.next()
          ^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/pymongo/synchronous/cursor.py", line 1257, in next
   if len(self._data) or self._refresh():
                         ^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/pymongo/synchronous/cursor.py", line 1205, in _refresh
   self._send_message(q)
 File "/venv/lib/python3.11/site-packages/pymongo/synchronous/cursor.py", line 1100, in _send_message
   response = client._run_operation(
              ^^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 119, in csot_wrapper
   return func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 1754, in _run_operation
   return self._retryable_read(
          ^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 1863, in _retryable_read
   return self._retry_internal(
          ^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 119, in csot_wrapper
   return func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 1830, in _retry_internal
   ).run()
     ^^^^^
 File "/venv/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 2554, in run
   return self._read() if self._is_read else self._write()
          ^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 2697, in _read
   return self._func(self._session, self._server, conn, read_pref)  # type: ignore
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 1745, in _cmd
   return server.run_operation(
          ^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/pymongo/synchronous/helpers.py", line 45, in inner
   return func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/pymongo/synchronous/server.py", line 227, in run_operation
   _check_command_response(first, conn.max_wire_version)
 File "/venv/lib/python3.11/site-packages/pymongo/helpers_shared.py", line 247, in _check_command_response
   raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Regular expression is invalid: unmatched closing parenthesis, full error: {'ok': 0.0, 'errmsg': 'Regular expression is invalid: unmatched closing parenthesis', 'code': 51091, 'codeName': 'Location51091', '$clusterTime': {'clusterTime': Timestamp(1729589266, 1), 'signature': {'hash': b'\xad\xa1r\xa5\xa4,9 \xbf\tY\xbbj9v\xb1\x87`R,', 'keyId': 7385197240429576193}}, 'operationTime': Timestamp(1729589266, 1)}
```

**Comment by dnil** [comment]
This could be considered a (more concrete) duplicate of https://github.com/Clinical-Genomics/scout/issues/2814?

**Comment by dnil** [comment]
Thank you for checking - I'm generally not super happy to see syntax issues with user input data, safety wise, although this now looks trivial enough.

**Comment by northwestwitch** [comment]
We could just add a HTML5 check that that field so the user can't enter weird chars?
