### ISSUE TITLE
Error executing CLI commands using python 3.9

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#5032]
```
(py39) chiararasi@n140-p127 scout % scout --demo update --help
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/bin/scout", line 33, in <module>
    sys.exit(load_entry_point('scout-browser', 'console_scripts', 'scout')())
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/bin/scout", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/commands/__init__.py", line 1, in <module>
    from .base import cli
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/commands/base.py", line 13, in <module>
    from scout.commands.convert import convert
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/commands/convert.py", line 8, in <module>
    from scout.server.extensions import store
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/extensions/__init__.py", line 8, in <module>
    from scout.adapter import MongoAdapter
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/adapter/__init__.py", line 1, in <module>
    from scout.adapter.mongo.base import MongoAdapter
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/adapter/mongo/__init__.py", line 1, in <module>
    from .base import MongoAdapter
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/adapter/mongo/base.py", line 35, in <module>
    from .case import CaseHandler
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/adapter/mongo/case.py", line 16, in <module>
    from scout.parse.variant.ids import parse_document_id
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/parse/variant/__init__.py", line 1, in <module>
    from .variant import parse_variant
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/parse/variant/variant.py", line 12, in <module>
    from .clnsig import parse_clnsig
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/parse/variant/clnsig.py", line 11, in <module>
    ) -> list(Dict[str, Union[str, int]]):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/typing.py", line 277, in inner
    return func(*args, **kwds)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/typing.py", line 767, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/typing.py", line 767, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39/lib/python3.9/typing.py", line 166, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Parameters to generic types must be types. Got 0.
```

**Comment by northwestwitch** [comment]
Oh, I get the same error also if I run `scout --demo serve`

**Comment by dnil** [comment]
Nice catch. Hm, should we add back a set of version for testing? It's quite a compute cost, but if we are serious about keeping compatibilty with the older versions, it will be hard otherwise.

**Comment by northwestwitch** [comment]
> Nice catch. Hm, should we add back a set of version for testing? It's quite a compute cost, but if we are serious about keeping compatibilty with the older versions, it will be hard otherwise.

Or I can keep using the oldest version so I'm the check ;)
