### ISSUE TITLE
STR variants export is still broken

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#5034]
```
2024-11-18 13:41:43,330 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /cust002/F0040465/str/variants [POST] [in /venv/lib/python3.11/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/scout/server/utils.py", line 87, in decorated_function
    context = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/scout/server/blueprints/variants/views.py", line 246, in str_variants
    return controllers.download_str_variants(case_obj, variants_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/scout/server/blueprints/variants/controllers.py", line 1024, in download_str_variants
    export_lines.append(",".join(variant_line))
                        ^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 1: expected str instance, NoneType found

```

**Comment by northwestwitch** [comment]
The export of STRs is still broken, sadly. Found out while testing the release branch. I'll work on a fix!

**Comment by northwestwitch** [comment]
Ah it's the estimated size column:

<img width="249" alt="image" src="https://github.com/user-attachments/assets/cb456533-0fb5-48e7-b1fb-054c69ebfe09">
