### ISSUE TITLE
gene panel duplicate key

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#5066]
```
2024-11-25 10:57:22,790 - scout.server.app - ERROR: Exception on /panels/6744481459648760728fb97d/update [POST] [in /venv/lib/python3.11/site-packages/flask/app.py:875]
Traceback (most recent call last):
 File "/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
   response = self.full_dispatch_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
   rv = self.handle_user_exception(e)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 194, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
                                               ^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
   rv = self.dispatch_request()
        ^^^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/worker/app/scout/server/blueprints/panels/views.py", line 197, in panel_update
   new_panel_id = store.apply_pending(panel_obj, update_version)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/worker/app/scout/adapter/mongo/panel.py", line 513, in apply_pending
   inserted_id = self.panel_collection.insert_one(new_panel).inserted_id
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/pymongo/synchronous/collection.py", line 891, in insert_one
   self._insert_one(
 File "/venv/lib/python3.11/site-packages/pymongo/synchronous/collection.py", line 831, in _insert_one
   self._database.client._retryable_write(
 File "/venv/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 1898, in _retryable_write
   return self._retry_with_session(retryable, func, s, bulk, operation, operation_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 1784, in _retry_with_session
   return self._retry_internal(
          ^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 119, in csot_wrapper
   return func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 1830, in _retry_internal
   ).run()
     ^^^^^
 File "/venv/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 2554, in run
   return self._read() if self._is_read else self._write()
                                             ^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 2676, in _write
   return self._func(self._session, conn, self._retryable)  # type: ignore
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/venv/lib/python3.11/site-packages/pymongo/synchronous/collection.py", line 829, in _insert_command
   _check_write_command_response(result)
 File "/venv/lib/python3.11/site-packages/pymongo/helpers_shared.py", line 285, in _check_write_command_response
   _raise_last_write_error(write_errors)
 File "/venv/lib/python3.11/site-packages/pymongo/helpers_shared.py", line 255, in _raise_last_write_error
   raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: scout.gene_panel index: panel_name_1_version_1 dup key: { panel_name: "BrOvCa", version: 1.0 }, full error: {'index': 0, 'code': 11000, 'errmsg': 'E11000 duplicate key error collection: scout.gene_panel index: panel_name_1_version_1 dup key: { panel_name: "BrOvCa", version: 1.0 }', 'keyPattern': {'panel_name': 1, 'version': 1}, 'keyValue': {'panel_name': 'BrOvCa', 'version': 1.0}}
```

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by northwestwitch** [comment]
Good that we are creating a new patch! Are you working on this one?

**Comment by dnil** [comment]
No, feel free! I checked with KLR, and she had just attempted to name the next version "1.0" again, but understood that it didn't work and fixed herself. A less generic error message could be nice for less experienced users, but it is not really bug prio. 😸

**Comment by northwestwitch** [comment]
Weird, the same thing doesn't trigger error on the demo database:

<img width="270" alt="image" src="https://github.com/user-attachments/assets/6ee6de87-c337-4b3f-b6c2-684a5a915ec0">
