### ISSUE TITLE
General report "novel" filter tags

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#5075]
```
2024-11-26 11:42:21 MacBook-Pro-4.local scout.server.app[513] ERROR Exception on /cust000/cancer_case/case_report [GET]
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/scout312/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/scout312/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/scout312/lib/python3.12/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/scout312/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/miniconda3/envs/scout312/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dannil/sandbox/scout/scout/server/utils.py", line 87, in decorated_function
    context = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dannil/sandbox/scout/scout/server/blueprints/cases/views.py", line 267, in case_report
    data = controllers.case_report_content(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dannil/sandbox/scout/scout/server/blueprints/cases/controllers.py", line 713, in case_report_content
    case_report_variants(store, case_obj, institute_obj, data)
  File "/Users/dannil/sandbox/scout/scout/server/blueprints/cases/controllers.py", line 634, in case_report_variants
    _append_evaluated_variant_by_type(
  File "/Users/dannil/sandbox/scout/scout/server/blueprints/cases/controllers.py", line 667, in _append_evaluated_variant_by_type
    _get_decorated_var(var_obj=var_obj, institute_obj=institute_obj, case_obj=case_obj)
  File "/Users/dannil/sandbox/scout/scout/server/blueprints/cases/controllers.py", line 643, in _get_decorated_var
    return variant_decorator(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/dannil/sandbox/scout/scout/server/blueprints/variant/controllers.py", line 322, in variant
    variant_obj["filters"] = get_filters(variant_obj)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dannil/sandbox/scout/scout/server/blueprints/variant/utils.py", line 619, in get_filters
    return [
           ^
  File "/Users/dannil/sandbox/scout/scout/server/blueprints/variant/utils.py", line 629, in <lambda>
    for f in map(lambda x: x.lower(), variant_obj["filters"])
                           ^^^^^^^
AttributeError: 'dict' object has no attribute 'lower'
```

**Describe the bug**
Including a variant with (multiple) filter tags does induces crash in generating general report.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dnil** [comment]
The issue is with redecoration of the same decorated variant if it is in more than one category. We allow this currently, and it didn't break until my addition to `get_callers()`. I'm tempted to refactor to have them not be re-decorated, but a lot of the logic for what to show where is in the jinja template currently, so it might be error prone. I think I will do a two step thing, first just pamper with a type check in `get_callers` to make it not crash, and then we can refactor whenever it feels like we have time for it. It would save some time on report generation, not having to do each variant multiple times. 😂
