### ISSUE TITLE
Nothing annotated in "exon" field for Transcript

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#60]
Error in Transcript ODM.
Question: What should I expect in this "exon" field? Does it make sense that it's ``None``? Should I account for that? What does it mean biologically?

```python
Traceback (most recent call last):
[...]
File "/home/scout/new/src/scout/scout/core/templates/variant.html", line 5, in top-level template code
    {% set page_title = 'Variant' %}
  File "/home/scout/new/src/scout/scout/templates/layouts/scroll-header.html", line 2, in top-level template code
    {% from 'macros/_polymer.html' import core_item %}
  File "/home/scout/new/src/scout/scout/templates/layouts/base.html", line 40, in top-level template code
    {% block body %}{% endblock %}
  File "/home/scout/new/src/scout/scout/templates/layouts/scroll-header.html", line 68, in block "body"
    {% block content %}{% endblock %}
  File "/home/scout/new/src/scout/scout/core/templates/variant.html", line 756, in block "content"
    <li>{{ transcript.stringify() }}</li>
  File "/home/scout/new/src/scout/scout/models/variant.py", line 140, in stringify
    .format(this=self))
  File "/home/scout/new/src/scout/scout/models/variant.py", line 134, in absolute_exon
    return (self.exon or '').rpartition('/')[0]
AttributeError: 'NoneType' object has no attribute 'rpartition'
```

**Comment by robinandeer** [comment]
All of these variants have the problem:
https://clinical-db.scilifelab.se:8083/cust000/2014-04606fam/clinical?gene_lists=
