### ISSUE TITLE
Scout setup demo fails due to NameError ('transcripts38_reduced_path')

### ISSUE THREAD

**Issue by PeterARBork** [Clinical-Genomics/scout#670]
Having just gotten a fresh scout version 3.5.0 and after starting a fresh mongo service, I ran the commands copy+paste style from the install.md document step 2, and arrived at the the following output:

```
[petbor@risoe-r07-g001 scout]$ scout setup demo
/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/weasyprint/text.py:29: UserWarning: There are known rendering problems with Cairo <= 1.14.0
  warnings.warn('There are known rendering problems with Cairo <= 1.14.0')
2017-11-22 14:21:59 risoe-r07-g001 scout.commands.base[10913] INFO Running scout version 3.5.0
2017-11-22 14:21:59 risoe-r07-g001 scout.commands.setup.setup_scout[10913] INFO Loading hgnc genes from /services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/scout/demo/resources/hgnc_reduced_set.txt.gz
2017-11-22 14:21:59 risoe-r07-g001 scout.commands.setup.setup_scout[10913] INFO Loading exac genes from /services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/scout/demo/resources/forweb_cleaned_exac_r03_march16_z_data_pLI_reduced.txt.gz
2017-11-22 14:21:59 risoe-r07-g001 scout.commands.setup.setup_scout[10913] INFO Loading mim2gene info from /services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/scout/demo/resources/mim2gene_reduced.txt.gz
2017-11-22 14:21:59 risoe-r07-g001 scout.commands.setup.setup_scout[10913] INFO Loading genemap info from /services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/scout/demo/resources/genemap2_reduced.txt.gz
2017-11-22 14:21:59 risoe-r07-g001 scout.commands.setup.setup_scout[10913] INFO Loading hpo gene info from /services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/scout/demo/resources/ALL_SOURCES_ALL_FREQUENCIES_genes_to_phenotype_reduced.txt.gz
2017-11-22 14:21:59 risoe-r07-g001 scout.commands.setup.setup_scout[10913] INFO Loading hpo disease info from /services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/scout/demo/resources/ALL_SOURCES_ALL_FREQUENCIES_diseases_to_genes_to_phenotypes_reduced.txt.gz
2017-11-22 14:21:59 risoe-r07-g001 scout.commands.setup.setup_scout[10913] INFO Loading hpo terms from /services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/scout/demo/resources/ALL_SOURCES_ALL_FREQUENCIES_phenotype_to_genes_reduced.txt.gz
2017-11-22 14:21:59 risoe-r07-g001 scout.commands.setup.setup_scout[10913] INFO Loading omim disease info from /services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/scout/demo/resources/genemap2_reduced.txt.gz
2017-11-22 14:21:59 risoe-r07-g001 scout.commands.setup.setup_scout[10913] INFO Loading transcripts build 37 info from /services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/scout/demo/resources/ensembl_transcripts_reduced.txt.gz
Traceback (most recent call last):
  File "/services/tools/anaconda3/4.0.0/bin/scout", line 11, in <module>
    sys.exit(cli())
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/scout/commands/setup/setup_scout.py", line 295, in setup
    transcripts38 = get_file_handle(transcripts38_reduced_path)
NameError: name 'transcripts38_reduced_path' is not defined
```

What can I do to help debug?

**Comment by moonso** [comment]
Thanks, I will have a look. Meanwhile  you could just try to setup the regular way.
That is `scout setup database`

**Comment by moonso** [comment]
I cheated a bit here so the gene defenitions for build 38 is the same as 37 in the demo version. At least it should work. We will need to look through all the demo data at some point
