### ISSUE TITLE
load user fails due to NameError: 'institute_name' is not defined

### ISSUE THREAD

**Issue by PeterARBork** [Clinical-Genomics/scout#673]
Using scout 3.5.0 on a fresh mongo database, the following sequence of commands results in a NameError:

```
$ scout setup database
$ scout serve &
$ scout load institute -i bonkolab -d bonkolab
$ scout load user --institute-id bonkolab --user-name "Peter Bork" --user-mail peter.aleksander.rousing.bork@regionh.dk
```

I've run the same sequence with and without `scout setup database` and `scout serve`, with the same outcome.

Full show:
```
[petbor@risoe-r04-cn086 scout]$ scout load institute -i bonkolab
/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/weasyprint/text.py:29: UserWarning: There are known rendering problems with Cairo <= 1.14.0
  warnings.warn('There are known rendering problems with Cairo <= 1.14.0')
2017-11-23 13:34:17 risoe-r04-cn086 scout.commands.base[8712] INFO Running scout version 3.5.0
2017-11-23 13:34:17 risoe-r04-cn086 scout.commands.base[8712] INFO Setting database name to scout
2017-11-23 13:34:17 risoe-r04-cn086 scout.commands.base[8712] INFO Test if mongod is running
2017-11-23 13:34:17 risoe-r04-cn086 scout.adapter.client[8712] INFO Try to connect to mongodb://localhost:27017
2017-11-23 13:34:17 risoe-r04-cn086 scout.adapter.client[8712] INFO Connection established
2017-11-23 13:34:17 risoe-r04-cn086 scout.commands.base[8712] INFO Setting up a mongo adapter
2017-11-23 13:34:17 risoe-r04-cn086 scout.build.institute[8712] INFO Building institute bonkolab with display name bonkolab
2017-11-23 13:34:17 risoe-r04-cn086 scout.load.institute[8712] INFO Loading institute bonkolab with display name bonkolab into database
2017-11-23 13:34:17 risoe-r04-cn086 scout.adapter.mongo.institute[8712] INFO Adding institute with internal_id: bonkolab and display_name: bonkolab
2017-11-23 13:34:17 risoe-r04-cn086 scout.adapter.mongo.institute[8712] INFO Institute saved
[petbor@risoe-r04-cn086 scout]$ scout load user --institute-id bonkolab --user-name "Peter Bork" --user-mail peter.aleksander.rousing.bork@regionh.dk
/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/weasyprint/text.py:29: UserWarning: There are known rendering problems with Cairo <= 1.14.0
  warnings.warn('There are known rendering problems with Cairo <= 1.14.0')
2017-11-23 13:34:23 risoe-r04-cn086 scout.commands.base[8767] INFO Running scout version 3.5.0
2017-11-23 13:34:23 risoe-r04-cn086 scout.commands.base[8767] INFO Setting database name to scout
2017-11-23 13:34:23 risoe-r04-cn086 scout.commands.base[8767] INFO Test if mongod is running
2017-11-23 13:34:23 risoe-r04-cn086 scout.adapter.client[8767] INFO Try to connect to mongodb://localhost:27017
2017-11-23 13:34:23 risoe-r04-cn086 scout.adapter.client[8767] INFO Connection established
2017-11-23 13:34:23 risoe-r04-cn086 scout.commands.base[8767] INFO Setting up a mongo adapter
Traceback (most recent call last):
  File "/services/tools/anaconda3/4.0.0/bin/scout", line 11, in <module>
    sys.exit(cli())
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/services/tools/anaconda3/4.0.0/lib/python3.5/site-packages/scout/commands/load/load_database.py", line 55, in user
    institute = adapter.institute(institute_id=institute_name)
NameError: name 'institute_name' is not defined
```

**Comment by PeterARBork** [comment]
Ah, looking into the code it seems line 55 in load_database.py was changed about a month ago so the line no longer uses `institute_name` but `institute_id`.

Perhaps the problem will be solved when I get the newest version. I'll try that.

**Comment by PeterARBork** [comment]
Yes, scoute version 3.5.1 no longer has the error.

**Comment by moonso** [comment]
thx
