### ISSUE TITLE
Loading panel fails due to code error in commands/load/panel.py

### ISSUE THREAD

**Issue by PeterARBork** [Clinical-Genomics/scout#683]
In line 62 of  [commands/load/panel.py](scout/scout/commands/load/panel.py), "name" is used instead of "field":
https://github.com/Clinical-Genomics/scout/blob/a9a388455380907507983cd86567a13f8baffa40/scout/commands/load/panel.py#L44-L63

Command and error stacktrace:

```
(scout_env) [petbor@risoe-r03-cn008 scout]$ scout load panel scout/demo/pb_panel.txt
2017-12-05 15:50:37 risoe-r03-cn008 scout.commands.base[29982] INFO Running scout version 3.5.2
2017-12-05 15:50:37 risoe-r03-cn008 scout.commands.base[29982] INFO Setting database name to scout
2017-12-05 15:50:37 risoe-r03-cn008 scout.commands.base[29982] INFO Test if mongod is running
2017-12-05 15:50:37 risoe-r03-cn008 scout.adapter.client[29982] INFO Try to connect to mongodb://localhost:27017
2017-12-05 15:50:37 risoe-r03-cn008 scout.adapter.client[29982] INFO Connection established
2017-12-05 15:50:37 risoe-r03-cn008 scout.commands.base[29982] INFO Setting up a mongo adapter
Traceback (most recent call last):
  File "/home/projects/dp_00005/apps/scout/scout_env/bin/scout", line 11, in <module>
    load_entry_point('scout-browser', 'console_scripts', 'scout')()
  File "/home/projects/dp_00005/apps/scout/scout_env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/projects/dp_00005/apps/scout/scout_env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/projects/dp_00005/apps/scout/scout_env/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/projects/dp_00005/apps/scout/scout_env/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/projects/dp_00005/apps/scout/scout_env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/projects/dp_00005/apps/scout/scout_env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/projects/dp_00005/apps/scout/scout_env/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/projects/dp_00005/apps/scout/scout/commands/load/panel.py", line 62, in panel
    elif name == 'display_name':
NameError: name 'name' is not defined
```

**Comment by moonso** [comment]
Thx I will fix that tomorrow 👍
