### ISSUE TITLE
Error when viewing whitelisted users

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/scout#717]
Steps to reproduce:
1. In the Hippo-environment run command: scout view users

Expected result: 
List of users

Actual result: 
List of users and then a crash:
Traceback (most recent call last):
  File ".../bin/scout", line 11, in <module>
    sys.exit(cli())
  File ".../lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File ".../lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File ".../lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".../lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".../lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File ".../lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File ".../lib/python3.6/site-packages/scout/commands/view/view_command.py", line 68, in users
    ', '.join(user_obj.get('institutes',[])),
TypeError: sequence item 0: expected str instance, dict found

**Comment by moonso** [comment]
I'm quite sure that this is has to do with old code on Hippo.
Try the same command from rasta.

**Comment by moonso** [comment]
There was a error in the database
