### ISSUE TITLE
ModuleNotFoundError requires python version 3.6

### ISSUE THREAD

**Issue by PeterARBork** [Clinical-Genomics/scout#721]
Now that Scout requires python version 3.6 (since ModuleNotFoundError is new in the line below), I though it might be helpful to write that version requirement on the github frontpage or somewhere else visible.

Perhaps the line below could even have a try-except clause with a hint printed to help people realize that the reason they get an error is that their python is too old - I found realized it relatively quickly, but with a bit of luck (I looked up the Error in the [docs](https://docs.python.org/3/library/exceptions.html#ModuleNotFoundError) and saw that it was new in version 3.6).

https://github.com/Clinical-Genomics/scout/blob/180b9c3f43fb81794e98b2ac1b01464b0cb449bb/scout/commands/base.py#L33

Stacktrace after installing according to front-page:

```
(scout_env) [petbor@risoe-r03-cn004 scout]$ scout --version
Traceback (most recent call last):
  File "/home/projects/dp_00005/apps/petbor/scout/scout/commands/base.py", line 32, in <module>
    from scoutconfig import *
ImportError: No module named 'scoutconfig'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/projects/dp_00005/apps/petbor/scout_env/bin/scout", line 11, in <module>
    load_entry_point('scout-browser', 'console_scripts', 'scout')()
  File "/home/projects/dp_00005/apps/petbor/scout_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/projects/dp_00005/apps/petbor/scout_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2752, in load_entry_point
    return ep.load()
  File "/home/projects/dp_00005/apps/petbor/scout_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/home/projects/dp_00005/apps/petbor/scout_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/projects/dp_00005/apps/petbor/scout/scout/commands/__init__.py", line 1, in <module>
    from .base import cli
  File "/home/projects/dp_00005/apps/petbor/scout/scout/commands/base.py", line 33, in <module>
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined
```

**Comment by moonso** [comment]
Sure I will look at that
