### ISSUE TITLE
Error when diagnosing case

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#740]
```python
2018-02-15 08:07:20,958 - scout.server.app - ERROR: Exception on /custxxx/casex/diagnose [POST] [in python3.5/site-packages/flask/app.py:1587]
Traceback (most recent call last):
  File "python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "scout/server/blueprints/cases/views.py", line 89, in case_diagnosis
    omim_id=omim_id, remove=remove)
  File "scout/adapter/mongo/event.py", line 1088, in diagnose
    omim_number = int(omim_id.split(':')[-1])
ValueError: invalid literal for int() with base 10: ''
```

**Comment by northwestwitch** [comment]
This looks similar to the other, I believe I can fix it!

**Comment by moonso** [comment]
👍 👍 👍
