### ISSUE TITLE
Error when updating gene panel

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#741]
```python
2018-02-16 12:18:09,659 - scout.server.app - ERROR: Exception on /panels/5a782ffc124f63138ce1ff86 [POST] [in python3.5/site-packages/flask/app.py:1587]
Traceback (most recent call last):
  File "python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "scout/scout/server/utils.py", line 19, in decorated_function
    context = f(*args, **kwargs)
  File "scout/scout/server/blueprints/panels/views.py", line 68, in panel
    hgnc_id = int(raw_hgnc_id)
ValueError: invalid literal for int() with base 10: 'GFM1'
```

**Comment by ingkebil** [comment]
```python
2018-02-22 09:17:22,046 - scout.server.app - ERROR: Exception on /panels/5a659baf124f63029e8acca1 [POST] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py:1587]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 19, in decorated_function
    context = f(*args, **kwargs)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/panels/views.py", line 68, in panel
    hgnc_id = int(raw_hgnc_id)
ValueError: invalid literal for int() with base 10: ''
```

**Comment by moonso** [comment]
Yes I also got this, do you have any idea what happened when the error occurred?

**Comment by ingkebil** [comment]
Nor really. I remembered you had opened an issue non this and that the input that causednthe error was different than the one I just posted. So its just some more information.

**Comment by moonso** [comment]
This is almost exactly the same issue, the problem is the input format.
This is a perfect issue for @patrikgrenfeldt or @northwestwitch to start with

**Comment by northwestwitch** [comment]
I can take a look at it!

**Comment by moonso** [comment]
Thank you @northwestwitch ! Just shout at me if you need any help. I'm not sure but I would recommend you to look at https://flask-wtf.readthedocs.io/en/stable/
