### ISSUE TITLE
Error when not authenticated

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#747]
```
2018-02-23 12:24:05,233 - scout.server.app - ERROR: Exception on /authorized [GET] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py:1587]
Traceback (most recent call last):
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/login/views.py", line 70, in authorized
    oauth_response = google.authorized_response()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask_oauthlib/client.py", line 677, in authorized_response
    data = self.handle_oauth2_response()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask_oauthlib/client.py", line 664, in handle_oauth2_response
    type='invalid_response', data=data
flask_oauthlib.client.OAuthException: Invalid response from google

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/login/views.py", line 72, in authorized
    current_app.logger.warn(oauth_response.message)
UnboundLocalError: local variable 'oauth_response' referenced before assignment
```

**Comment by moonso** [comment]
We should write something that takes care of 
```python
UnboundLocalError: local variable 'oauth_response' referenced before assignment
```

Another one for @northwestwitch ? 👀

**Comment by northwestwitch** [comment]
Don't get too used it :)

**Comment by ingkebil** [comment]
Got another email regarding this. I guess this hasn't been pushed to production?

**Comment by northwestwitch** [comment]
Or it was not the solution, I don't know!

**Comment by moonso** [comment]
No it is not updated on the server
