### ISSUE TITLE
Error when displaying manual rank

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#761]
```bash
2018-03-08 09:52:50,938 - scout.server.app - ERROR: Exception on /cust004/918720601791fam/230a08d64b1155c803bbabacca088b4b/update [POST] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py:1587]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/views.py", line 133, in variant_update
    flash("reset variant tag: {}".format(variant_obj['manual_rank']), 'info')
KeyError: 'manual_rank'
```

**Comment by moonso** [comment]
Should be a `get` when fetching `manual_rank`
