### ISSUE TITLE
Loading SVs annotated by VEP fails

### ISSUE THREAD

**Issue by PeterARBork** [Clinical-Genomics/scout#765]
Having just annotated a candidatesSV.vcf from MANTA with VEP using the command below, I started Scout with a single case given the path to the annotated vcf and ran into the issue seen in Scouts output below.

```
2018-03-12 13:34:41 risoe-r03-cn017 scout.commands.base[25297] INFO Running scout version 3.5.2
2018-03-12 13:34:41 risoe-r03-cn017 scout.commands.base[25297] INFO Setting database name to scout
2018-03-12 13:34:41 risoe-r03-cn017 scout.commands.base[25297] INFO Test if mongod is running
2018-03-12 13:34:41 risoe-r03-cn017 scout.adapter.client[25297] INFO Try to connect to mongodb://localhost:27017
2018-03-12 13:34:41 risoe-r03-cn017 scout.adapter.client[25297] INFO Connection established
2018-03-12 13:34:41 risoe-r03-cn017 scout.commands.base[25297] INFO Setting up a mongo adapter
2018-03-12 13:34:41 risoe-r03-cn017 scout.commands.load.case[25297] INFO Use family 57PGF
2018-03-12 13:34:41 risoe-r03-cn017 scout.build.case[25297] INFO build case with id: 57PGF
2018-03-12 13:34:41 risoe-r03-cn017 scout.build.individual[25297] INFO Building Individual with id:57PGF
2018-03-12 13:34:41 risoe-r03-cn017 scout.adapter.mongo.panel[25297] INFO Fething gene panels panel1 from database
2018-03-12 13:34:41 risoe-r03-cn017 scout.adapter.mongo.panel[25297] INFO Fething gene panels pb_panel from database
2018-03-12 13:34:41 risoe-r03-cn017 scout.adapter.mongo.panel[25297] INFO Fething gene panels genes_of_interest_panel from database
2018-03-12 13:34:41 risoe-r03-cn017 scout.adapter.mongo.panel[25297] INFO Fething gene panels acmg_genes_panel from database
2018-03-12 13:34:41 risoe-r03-cn017 scout.adapter.mongo.panel[25297] INFO Fething gene panels pharma_genes_panel from database
2018-03-12 13:34:41 risoe-r03-cn017 scout.adapter.mongo.case[25297] INFO Fetching case bonkolab-57PGF
2018-03-12 13:34:41 risoe-r03-cn017 scout.adapter.mongo.case[25297] INFO Fetching case 57PGF
2018-03-12 13:34:41 risoe-r03-cn017 scout.adapter.mongo.hgnc[25297] INFO Fetching all genes
2018-03-12 13:34:42 risoe-r03-cn017 scout.adapter.mongo.panel[25297] INFO Building gene to panels
2018-03-12 13:34:42 risoe-r03-cn017 scout.adapter.mongo.panel[25297] INFO Fetch gene panel panel1, version 1.0 from database
2018-03-12 13:34:42 risoe-r03-cn017 scout.adapter.mongo.panel[25297] INFO Fetch gene panel pb_panel, version 1.0 from database
2018-03-12 13:34:42 risoe-r03-cn017 scout.adapter.mongo.panel[25297] INFO Fetch gene panel genes_of_interest_panel, version 1.0 from database
2018-03-12 13:34:42 risoe-r03-cn017 scout.adapter.mongo.panel[25297] INFO Fetch gene panel acmg_genes_panel, version 1.0 from database
2018-03-12 13:34:42 risoe-r03-cn017 scout.adapter.mongo.panel[25297] INFO Fetch gene panel pharma_genes_panel, version 1.0 from database
2018-03-12 13:34:42 risoe-r03-cn017 scout.adapter.mongo.panel[25297] INFO Gene to panels done
2018-03-12 13:34:42 risoe-r03-cn017 scout.adapter.mongo.hgnc[25297] INFO Building hgncid_to_gene
2018-03-12 13:34:42 risoe-r03-cn017 scout.adapter.mongo.hgnc[25297] INFO Building interval trees...
2018-03-12 13:34:45 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO Start inserting variants into database
2018-03-12 13:34:46 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 1000 variants inserted
2018-03-12 13:34:46 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 2000 variants inserted
2018-03-12 13:34:47 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 3000 variants inserted
2018-03-12 13:34:48 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 4000 variants inserted
2018-03-12 13:34:49 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 5000 variants inserted
2018-03-12 13:34:49 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 5000 variants parsed
2018-03-12 13:34:49 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO Time to parse variants: 0:00:03.622505
2018-03-12 13:34:50 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 6000 variants inserted
2018-03-12 13:34:50 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 7000 variants inserted
2018-03-12 13:34:51 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 8000 variants inserted
2018-03-12 13:34:52 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 9000 variants inserted
2018-03-12 13:34:53 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 10000 variants inserted
2018-03-12 13:34:53 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 10000 variants parsed
2018-03-12 13:34:53 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO Time to parse variants: 0:00:04.035877
2018-03-12 13:34:54 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 11000 variants inserted
2018-03-12 13:34:54 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 12000 variants inserted
2018-03-12 13:34:55 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 13000 variants inserted
2018-03-12 13:34:56 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 14000 variants inserted
2018-03-12 13:34:57 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 15000 variants inserted
2018-03-12 13:34:57 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 15000 variants parsed
2018-03-12 13:34:57 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO Time to parse variants: 0:00:03.916278
2018-03-12 13:34:58 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 16000 variants inserted
2018-03-12 13:34:59 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 17000 variants inserted
2018-03-12 13:35:00 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 18000 variants inserted
2018-03-12 13:35:00 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 19000 variants inserted
2018-03-12 13:35:01 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 20000 variants inserted
2018-03-12 13:35:01 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 20000 variants parsed
2018-03-12 13:35:01 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO Time to parse variants: 0:00:04.703000
2018-03-12 13:35:02 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO All variants inserted, time to insert variants: 0:00:16.534816
2018-03-12 13:35:02 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO Nr variants parsed: 20360
2018-03-12 13:35:02 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO Nr variants inserted: 20360
2018-03-12 13:35:02 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO Updating variant_rank for all variants
2018-03-12 13:35:06 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO Updating variant_rank done
2018-03-12 13:35:06 risoe-r03-cn017 scout.adapter.mongo.hgnc[25297] INFO Fetching all genes
2018-03-12 13:35:07 risoe-r03-cn017 scout.adapter.mongo.panel[25297] INFO Building gene to panels
2018-03-12 13:35:07 risoe-r03-cn017 scout.adapter.mongo.panel[25297] INFO Fetch gene panel panel1, version 1.0 from database
2018-03-12 13:35:07 risoe-r03-cn017 scout.adapter.mongo.panel[25297] INFO Fetch gene panel pb_panel, version 1.0 from database
2018-03-12 13:35:07 risoe-r03-cn017 scout.adapter.mongo.panel[25297] INFO Fetch gene panel genes_of_interest_panel, version 1.0 from database
2018-03-12 13:35:07 risoe-r03-cn017 scout.adapter.mongo.panel[25297] INFO Fetch gene panel acmg_genes_panel, version 1.0 from database
2018-03-12 13:35:07 risoe-r03-cn017 scout.adapter.mongo.panel[25297] INFO Fetch gene panel pharma_genes_panel, version 1.0 from database
2018-03-12 13:35:07 risoe-r03-cn017 scout.adapter.mongo.panel[25297] INFO Gene to panels done
2018-03-12 13:35:07 risoe-r03-cn017 scout.adapter.mongo.hgnc[25297] INFO Building hgncid_to_gene
2018-03-12 13:35:07 risoe-r03-cn017 scout.adapter.mongo.hgnc[25297] INFO Building interval trees...
2018-03-12 13:35:10 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO Start inserting variants into database
2018-03-12 13:36:04 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 1000 variants inserted
2018-03-12 13:36:56 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 2000 variants inserted
2018-03-12 13:37:46 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] INFO 3000 variants inserted
2018-03-12 13:38:20 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] ERROR unexpected error
Traceback (most recent call last):
  File "/home/projects/dp_00005/apps/petbor/scout/scout/adapter/mongo/variant_loader.py", line 587, in load_variants
    sample_info = sample_info
  File "/home/projects/dp_00005/apps/petbor/scout/scout/adapter/mongo/variant_loader.py", line 407, in _load_variants
    category=category,
  File "/home/projects/dp_00005/apps/petbor/scout/scout/parse/variant/variant.py", line 172, in parse_variant
    for parsed_transcript in parse_transcripts(raw_transcripts, parsed_variant['alternative']):
  File "/home/projects/dp_00005/apps/petbor/scout/scout/parse/variant/transcript.py", line 112, in parse_transcripts
    regional.append(SO_TERMS[annotation]['region'])
KeyError: ''
2018-03-12 13:38:20 risoe-r03-cn017 scout.adapter.mongo.variant_loader[25297] WARNING Deleting inserted variants
2018-03-12 13:38:20 risoe-r03-cn017 scout.adapter.mongo.variant[25297] INFO Deleting old clinical None variants for case None
2018-03-12 13:38:21 risoe-r03-cn017 scout.adapter.mongo.variant[25297] INFO 23868 variants deleted
2018-03-12 13:38:21 risoe-r03-cn017 scout.adapter.mongo.case[25297] WARNING ''
2018-03-12 13:38:21 risoe-r03-cn017 scout.adapter.mongo.case[25297] INFO Loading case 57PGF into database
2018-03-12 13:38:21 risoe-r03-cn017 scout.adapter.mongo.case[25297] INFO Fetching case 57PGF
```

VEP annotation command:
```
vep -i $norm_vcf --force_overwrite --everything -o $vep_out --vcf --cache --dir $annotation_cache_dir --offline --fasta $vep_database_fasta --assembly GRCh38 && \
```

Since it seems the key is an empty string, I think it might be a loose reading of the vcf or something similar which could be solved by removing keys which are empty strings. What do you think?

**Comment by moonso** [comment]
@PeterARBork yes I think you are right. How comfortable are you with git and python? This would be an excellent start to contribute😃. Just add an `if` and create a pull request! If it look weird I can help out.

**Comment by PeterARBork** [comment]
I contribute python via git at my other job, so I'm reasonably comfortable with both.

First I removed the empty functional annotations to get rid of the KeyError, and the KeyError disappeared. I did this by adding the line
`functional_annotations = [a for a in functional_annotations if a is not '']`

Everything seemed to work, until I accessed the SV variants webpage, which gave an internal server error.

So I scratched a little bit at the surface of the code and saw that some of the entry-dictionary values had a "]" in them, such as `'Allele': ']chr9'`.

Removing lines with "]" from the vcf (and using original code without my "fix" above) gave the same symptoms (no KeyError during startup, but internal server error when presenting SV variants).

In both cases, the scout.log presented an error with region annotation
`jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'region_annotations'`.

Full scout.log below, identical for both error situations.

Does any of this ring a bell for you?

```
2018-03-26 11:33:22 risoe-r03-cn055 scout.commands.base[26001] INFO Running scout version 3.5.2
2018-03-26 11:33:22 risoe-r03-cn055 scout.commands.serve[26001] INFO Test if mongod is running
2018-03-26 11:33:22 risoe-r03-cn055 scout.adapter.mongo.base[26001] INFO connecting to database: localhost:27017/scout
2018-03-26 11:33:23 risoe-r03-cn055 werkzeug[26001] INFO  * Running on http://localhost:5000/ (Press CTRL+C to quit)
2018-03-26 11:34:03 risoe-r03-cn055 scout.adapter.mongo.user[26001] INFO Fetching user peter.aleksander.rousing.bork@regionh.dk
2018-03-26 11:34:03 risoe-r03-cn055 werkzeug[26001] INFO 127.0.0.1 - - [26/Mar/2018 11:34:03] "GET / HTTP/1.1" 200 -
2018-03-26 11:34:05 risoe-r03-cn055 werkzeug[26001] INFO 127.0.0.1 - - [26/Mar/2018 11:34:05] "GET /static/bootstrap/css/bootstrap.min.css?bootstrap=3.3.7.1.dev1 HTTP/1.1" 200 -
2018-03-26 11:34:05 risoe-r03-cn055 werkzeug[26001] INFO 127.0.0.1 - - [26/Mar/2018 11:34:05] "GET /static/styles.css HTTP/1.1" 200 -
2018-03-26 11:34:05 risoe-r03-cn055 werkzeug[26001] INFO 127.0.0.1 - - [26/Mar/2018 11:34:05] "GET /public/static/logo-scilifelab.png HTTP/1.1" 200 -
2018-03-26 11:34:05 risoe-r03-cn055 werkzeug[26001] INFO 127.0.0.1 - - [26/Mar/2018 11:34:05] "GET /public/static/swedac.png HTTP/1.1" 200 -
2018-03-26 11:34:06 risoe-r03-cn055 werkzeug[26001] INFO 127.0.0.1 - - [26/Mar/2018 11:34:06] "GET /public/static/logo-karolinska.png HTTP/1.1" 200 -
2018-03-26 11:34:06 risoe-r03-cn055 werkzeug[26001] INFO 127.0.0.1 - - [26/Mar/2018 11:34:06] "GET /static/bootstrap/jquery.min.js?bootstrap=3.3.7.1.dev1 HTTP/1.1" 200 -
2018-03-26 11:34:06 risoe-r03-cn055 werkzeug[26001] INFO 127.0.0.1 - - [26/Mar/2018 11:34:06] "GET /static/bootstrap/js/bootstrap.min.js?bootstrap=3.3.7.1.dev1 HTTP/1.1" 200 -
2018-03-26 11:34:06 risoe-r03-cn055 werkzeug[26001] INFO 127.0.0.1 - - [26/Mar/2018 11:34:06] "GET /static/bootstrap/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 -
2018-03-26 11:35:35 risoe-r03-cn055 scout.adapter.mongo.user[26001] INFO Fetching user peter.aleksander.rousing.bork@regionh.dk
2018-03-26 11:35:35 risoe-r03-cn055 scout.adapter.mongo.case[26001] INFO Get cases with query {'collaborators': 'bonkolab'}
2018-03-26 11:35:35 risoe-r03-cn055 scout.adapter.mongo.case[26001] INFO Get cases with query {'collaborators': 'cust000'}
2018-03-26 11:35:35 risoe-r03-cn055 werkzeug[26001] INFO 127.0.0.1 - - [26/Mar/2018 11:35:35] "GET /institutes HTTP/1.1" 200 -
2018-03-26 11:38:07 risoe-r03-cn055 scout.adapter.mongo.user[26001] INFO Fetching user peter.aleksander.rousing.bork@regionh.dk
2018-03-26 11:38:07 risoe-r03-cn055 scout.adapter.mongo.case[26001] INFO Get cases with query {'collaborators': 'bonkolab'}
2018-03-26 11:38:07 risoe-r03-cn055 werkzeug[26001] INFO 127.0.0.1 - - [26/Mar/2018 11:38:07] "GET /bonkolab HTTP/1.1" 200 -
2018-03-26 11:38:16 risoe-r03-cn055 scout.adapter.mongo.user[26001] INFO Fetching user peter.aleksander.rousing.bork@regionh.dk
2018-03-26 11:38:16 risoe-r03-cn055 scout.adapter.mongo.case[26001] INFO Fetching case 57PGF institute bonkolab
2018-03-26 11:38:16 risoe-r03-cn055 scout.adapter.mongo.institute[26001] INFO Fetching all institutes
2018-03-26 11:38:17 risoe-r03-cn055 werkzeug[26001] INFO 127.0.0.1 - - [26/Mar/2018 11:38:17] "GET /bonkolab/57PGF HTTP/1.1" 200 -
2018-03-26 11:38:17 risoe-r03-cn055 werkzeug[26001] INFO 127.0.0.1 - - [26/Mar/2018 11:38:17] "GET /cases/static/madeline.js HTTP/1.1" 304 -
2018-03-26 11:38:23 risoe-r03-cn055 scout.adapter.mongo.user[26001] INFO Fetching user peter.aleksander.rousing.bork@regionh.dk
2018-03-26 11:38:23 risoe-r03-cn055 scout.adapter.mongo.case[26001] INFO Fetching case 57PGF institute bonkolab
2018-03-26 11:38:23 risoe-r03-cn055 scout.adapter.mongo.user[26001] INFO Fetching user peter.aleksander.rousing.bork@regionh.dk
2018-03-26 11:38:23 risoe-r03-cn055 scout.adapter.mongo.event[26001] INFO Creating event for updating status of 57PGF to active
2018-03-26 11:38:23 risoe-r03-cn055 scout.adapter.mongo.event[26001] INFO Updating 57PGF to status active
2018-03-26 11:38:24 risoe-r03-cn055 werkzeug[26001] INFO 127.0.0.1 - - [26/Mar/2018 11:38:24] "GET /bonkolab/57PGF/variants?variant_type=clinical&gene_panels=genes_of_interest_panel HTTP/1.1" 200 -
2018-03-26 11:38:34 risoe-r03-cn055 scout.adapter.mongo.user[26001] INFO Fetching user peter.aleksander.rousing.bork@regionh.dk
2018-03-26 11:38:34 risoe-r03-cn055 scout.adapter.mongo.case[26001] INFO Fetching case 57PGF institute bonkolab
2018-03-26 11:38:34 risoe-r03-cn055 scout.adapter.mongo.institute[26001] INFO Fetching all institutes
2018-03-26 11:38:34 risoe-r03-cn055 werkzeug[26001] INFO 127.0.0.1 - - [26/Mar/2018 11:38:34] "GET /bonkolab/57PGF HTTP/1.1" 200 -
2018-03-26 11:38:42 risoe-r03-cn055 scout.adapter.mongo.user[26001] INFO Fetching user peter.aleksander.rousing.bork@regionh.dk
2018-03-26 11:38:42 risoe-r03-cn055 scout.adapter.mongo.case[26001] INFO Fetching case 57PGF institute bonkolab
[2018-03-26 11:38:42,587] ERROR in app: Exception on /bonkolab/57PGF/sv/variants [GET]
Traceback (most recent call last):
  File "/home/projects/dp_00005/apps/petbor/scout_dev/dev_env/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/projects/dp_00005/apps/petbor/scout_dev/dev_env/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/projects/dp_00005/apps/petbor/scout_dev/dev_env/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/projects/dp_00005/apps/petbor/scout_dev/dev_env/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/projects/dp_00005/apps/petbor/scout_dev/dev_env/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/projects/dp_00005/apps/petbor/scout_dev/dev_env/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/projects/dp_00005/apps/petbor/scout_dev/scout/server/utils.py", line 24, in decorated_function
    return render_template(template_name, **context)
  File "/home/projects/dp_00005/apps/petbor/scout_dev/dev_env/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/projects/dp_00005/apps/petbor/scout_dev/dev_env/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/projects/dp_00005/apps/petbor/scout_dev/dev_env/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/projects/dp_00005/apps/petbor/scout_dev/dev_env/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/projects/dp_00005/apps/petbor/scout_dev/dev_env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/projects/dp_00005/apps/petbor/scout_dev/dev_env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/projects/dp_00005/apps/petbor/scout_dev/scout/server/blueprints/variants/templates/variants/sv-variants.html", line 294, in top-level template code
    <a href="{{ url_for('variants.sv_variants', institute_id=institute._id, case_name=case.display_name, page=(page + 1), **form.data) }}">
  File "/home/projects/dp_00005/apps/petbor/scout_dev/scout/server/templates/layout.html", line 2, in top-level template code
    {% from "utils.html" import flash_messages %}
  File "/home/projects/dp_00005/apps/petbor/scout_dev/dev_env/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/projects/dp_00005/apps/petbor/scout_dev/dev_env/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/projects/dp_00005/apps/petbor/scout_dev/dev_env/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/projects/dp_00005/apps/petbor/scout_dev/dev_env/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/projects/dp_00005/apps/petbor/scout_dev/scout/server/blueprints/variants/templates/variants/sv-variants.html", line 86, in block "content"
    {{ variant_row(variant) }}
  File "/home/projects/dp_00005/apps/petbor/scout_dev/dev_env/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/home/projects/dp_00005/apps/petbor/scout_dev/scout/server/blueprints/variants/templates/variants/sv-variants.html", line 255, in template
    {% for annotation in variant.region_annotations[:3] %}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'region_annotations'
2018-03-26 11:38:43 risoe-r03-cn055 werkzeug[26001] INFO 127.0.0.1 - - [26/Mar/2018 11:38:43] "GET /bonkolab/57PGF/sv/variants?variant_type=clinical HTTP/1.1" 500 -
2018-03-26 11:38:43 risoe-r03-cn055 scout.adapter.mongo.user[26001] INFO Fetching user peter.aleksander.rousing.bork@regionh.dk
2018-03-26 11:38:43 risoe-r03-cn055 werkzeug[26001] INFO 127.0.0.1 - - [26/Mar/2018 11:38:43] "GET /favicon.ico HTTP/1.1" 404 -
```

**Comment by moonso** [comment]
Hmm I do not recognise this problem. Could you provide us with some more information? Like how the VCF looks like? Or have you found out any solution for this?

**Comment by moonso** [comment]
Closing this for now, please reopen and send files if there are any further problems
