### ISSUE TITLE
Scout install on ubuntu 

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#816]
Installing scout on Ubuntu gives the following error and installing urllib3 fixed it : ` conda install urllib3` . It should be included in the requirements.txt ?

```Traceback (most recent call last):
  File "/home/user/miniconda2/bin/scout", line 11, in <module>
    load_entry_point('scout-browser', 'console_scripts', 'scout')()
  File "/home/user/miniconda2/lib/python3.6/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/user/miniconda2/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/home/user/miniconda2/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/user/miniconda2/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/user/dev/scout/scout/commands/__init__.py", line 1, in <module>
    from .base import cli
  File "/home/user/dev/scout/scout/commands/base.py", line 10, in <module>
    from scout.adapter.mongo import MongoAdapter
  File "/home/user/dev/scout/scout/adapter/__init__.py", line 1, in <module>
    from scout.adapter.mongo.base import MongoAdapter
  File "/home/user/dev/scout/scout/adapter/mongo/__init__.py", line 1, in <module>
    from .base import MongoAdapter
  File "/home/user/dev/scout/scout/adapter/mongo/base.py", line 38, in <module>
    from .panel import PanelHandler
  File "/home/user/dev/scout/scout/adapter/mongo/panel.py", line 15, in <module>
    from scout.utils.requests import fetch_mim_files
  File "/home/user/dev/scout/scout/utils/requests.py", line 2, in <module>
    import urllib.request
ImportError: No module named request```

**Comment by moonso** [comment]
Hmm [request](https://docs.python.org/3/library/urllib.request.html) is a part of python3 standard library. It looks like you are using python 3.6 so I don't really understand why it doesn't work...

**Comment by moonso** [comment]
I guess something is messy with you're environment. Please make sure you are using python version > 3.6

**Comment by hassanfa** [comment]
I tried again in a clean ubuntu installation right now, and I couldn't replicated it. Probably something was missing in the environment. Let's close this issue.
