### ISSUE TITLE
SCOUT-STAGE: scout load research -c usablemarten not working

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/scout#831]
Trying to upload research variants via the CLI for case usablemarten gives a python error:

```
Traceback (most recent call last):
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda//envs/stage/bin/scout", line 11, in <module>
    load_entry_point('scout-browser==3.5.2', 'console_scripts', 'scout')()
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python3.6/site-packages/scout/commands/load/research.py", line 29, in research
    institute, case_id = case_id.split('-', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

Also tried it with a more recently added case from may this year (that should have the angrybird name for sure) with the same result.

Code is exactly the same for v4 as production version, which works with the angrybird names.
@moonso @northwestwitch might be a bug in how the names are retrieved?

**Comment by moonso** [comment]
Use `-i` and provide institute id, then it should work.
so:
```
scout load research -c usablemarten -I cust000
```

**Comment by emiliaol** [comment]
Yeah, you are right. It worked using that. Thanks
