### ISSUE TITLE
Some PDF reports not linked correctly

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#89]
```python
2015-05-05 12:49:34,077 - scout - ERROR: Exception on /remote/static/one [GET] [in /home/scout/miniconda/envs/prod/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/home/scout/miniconda/envs/prod/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/scout/miniconda/envs/prod/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/scout/miniconda/envs/prod/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/scout/miniconda/envs/prod/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/scout/miniconda/envs/prod/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/scout/src/scout/scout/browser/views.py", line 23, in remote_static
    return send_file_partial('/' + path)
  File "/home/scout/src/scout/scout/helpers.py", line 57, in send_file_partial
    return send_file(path)
  File "/home/scout/miniconda/envs/prod/lib/python2.7/site-packages/flask/helpers.py", line 520, in send_file
    file = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: u'/one'
```

**Comment by robinandeer** [comment]
From CMMS:

> Hej Robin,
> Det verkar vara ett problem med coverage report för familjen 156.  När jag klickar på knappen kommer jag till en :( sida.  Vet du vad har hänt med rapporten?
> Hälsningar,
> Nicole

**Comment by moonso** [comment]
Where is the problem? Backend?

**Comment by robinandeer** [comment]
I'm not quite sure so I should look into this and get back to you...

**Comment by moonso** [comment]
Ok

**Comment by Bianca-T** [comment]
Hi,

I also get the following screen when clicking on coverage report for two of my families (A1101 and A1132).

![screen shot 2015-07-16 at 15 06 30](https://cloud.githubusercontent.com/assets/5881356/8723224/500e14c2-2bcc-11e5-958b-d09a1834edd8.png)
