### ISSUE TITLE
Re-upload of case has created conflict in the database

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#90]
Perhaps we should add a check in the ODM to make sure the rank for variants are unique?

```python
2015-05-04 13:18:58,518 - scout - ERROR: Exception on /cust004/715720603078fam/variants/f7e7010cb03409066df1cb1324ea73e0 [GET] [in /home/scout/miniconda/envs/prod/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/home/scout/miniconda/envs/prod/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/scout/miniconda/envs/prod/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/scout/miniconda/envs/prod/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/scout/miniconda/envs/prod/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/scout/miniconda/envs/prod/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/scout/src/scout/scout/helpers.py", line 24, in decorated_function
    context = f(*args, **kwargs)
  File "/home/scout/miniconda/envs/prod/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/home/scout/src/scout/scout/core/views.py", line 313, in variant
    next_variant = store.next_variant(document_id=variant_id)
  File "/home/scout/src/scout/scout/ext/backend/mongo.py", line 237, in next_variant
    {'variant_rank': rank+1}
  File "/home/scout/miniconda/envs/prod/lib/python2.7/site-packages/mongoengine/queryset/base.py", line 194, in get
    raise queryset._document.MultipleObjectsReturned(message)
MultipleObjectsReturned: 2 items returned, instead of 1
```

**Comment by moonso** [comment]
This is caused by the same problem as #79
