### ISSUE TITLE
KeyError: 'ensembl_id'

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#999]
This happens when you try to visualize some variants. We should fix it!

Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 19, in decorated_function
    context = f(*args, **kwargs)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/views.py", line 101, in variant
    data = controllers.variant(store, institute_obj, case_obj, variant_id)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/controllers.py", line 490, in variant
    parse_gene(gene_obj, genome_build)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/controllers.py", line 594, in parse_gene
    add_gene_links(gene_obj, build)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/links.py", line 21, in add_gene_links
    ensembl_id = gene_obj['ensembl_id']
KeyError: 'ensembl_id'

**Comment by moonso** [comment]
I have fixed this in #1002
